### ISSUE TITLE
data lacking a spatial reference

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#105]
May relate to the migration from warehouse2 to warehouse1.  There are 9 occurrences without a spatial reference.  See sample report from warehouse1 for website = ABLE.
![ebms samples](https://user-images.githubusercontent.com/2699478/61532376-8dbb0f00-aa21-11e9-89fe-27245dc3ef1b.png).  This data needs correcting.

Possibly related to this is an erroneous point on the map of samples at https://butterfly-monitoring.net/mydata in the middle of the sea off Africa.
![ebms map](https://user-images.githubusercontent.com/2699478/61532414-a3c8cf80-aa21-11e9-8b58-fca0dd86cde0.png)

**Comment by johnvanbreda** [comment]
These are migrated correctly as they had no spatial reference on warehouse2 either, e.g. sample 11544. Strangely the cached data on warehouse2 does contain a point, e.g. for this sample it is near Universita della Calabria in Italy, so is quite possibly valid. Therefore I suspect a bug somewhere along the line. Shall I use the information in the warehouse2 cache tables to try and recover the missing data?

**Comment by DavidRoy** [comment]
Yes, please resolve from warehouse2 data.

**Comment by Gary-van-Breda** [comment]
I have altered the submission code to ensure there is always an sref filled in on the sample, and done a manual fix on the records in question.

**Comment by Gary-van-Breda** [comment]
The erroneous dot is not related: it comes from the EBMS App, sample http://warehouse1.indicia.org.uk/index.php/sample/edit/6129098
It looks like the geometry (a linestring) has been stored in the database in EPSG:4326, rather than EPSG:3857.
I am bouncing this to @kazlauskis in case this represents an issue with the Mobile app, though given that it was created 2 months ago, and is the first EBMS Mobile App data in the database, it may not represent actual data - is it left over development/test data?

**Comment by kazlauskis** [comment]
This single case from the app is from early testing, I have now deleted the record. Feel free to close this ticket if it is just for the app.

**Comment by Gary-van-Breda** [comment]
MyData no longer showing the erroneous dot, Map has been recentred around Europe.
Bouncing back to David to review/close.

**Comment by DavidRoy** [comment]
Thanks, now fixed
