### ISSUE TITLE
Data missing from reports

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#113]
reported by a recorder in Italy and confirmed when I checked.  likely linked to #108 

_apparently, we are having a trouble with the data base: on entering the data for my last walk, I cannot find any of the previous data.
The species grid at the "species I have recorded" option is empty, as are all the report forms.
It seems all data have been lost_

**Comment by johnvanbreda** [comment]
Is this for all users or only 1? Which user?

**Comment by johnvanbreda** [comment]
I'm looking into this - just making notes in case it rings any bells. The data in the database and the data appearing on the Mapping page don't seem to match. I'm getting records appearing that are from a seemingly random set of recorders. It seems like the user_id filter parameter is not being applied correctly. 

I'm pleased to report the new Elastic report seems correct, also because this confirms the data are tagged to the correct users.

**Comment by johnvanbreda** [comment]
Sorry, now realise that My Data > Mapping is actually an All records report, not filtered by user account, and the default filter is the last month of data which is why I can't see the other records.

So, @DavidRoy I think I need more details on which user and how to find the reports they are concerned about before proceeding.

**Comment by DavidRoy** [comment]
This isn't ES related.  It's the main transect reports so may need @Gary-van-Breda to resolve

user 1223

My walks reports shows visits undertaken - https://butterfly-monitoring.net/my-walks

Individual visit shows no data - e.g. https://butterfly-monitoring.net/ebms-input-data?sample_id=6126356.  The data is within the child samples (e.g. 6126366) and can be viewed via the warehouse interface (http://warehouse1.indicia.org.uk/index.php/sample/edit/6126366) to confirm data is capture

No data via the annual report - https://butterfly-monitoring.net/annual-report

**Comment by johnvanbreda** [comment]
Ok, agreed - I can see data in the database which superficially looks OK, so I think this does need @Gary-van-Breda's input.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda , can you confirm whether the equivalent taxa in the new and old lists (251 vs 254) share a taxon_meaning_id?
If not (the forms etc are all dependent on this at the moment), how should I match up the taxa from one list with the taxa of the other?

**Comment by Gary-van-Breda** [comment]
The following pages restrict the data returned to the specified list (251)
Walk data entry (lookup of species recorded by me, or recorded on this transect)
Annual Summary page
Year index Plot
Section plot

The Walk data entry is needed, otherwise the user could enter data using the old list. I will need to change all these forms to use whatever lookup mechanism you suggests to convert the old data to the new taxa.

It will be a lot easier (faster) if we can update all the TTL ids on the occurrences to point to the equivalent IDs in the new list.

**Comment by Gary-van-Breda** [comment]
I need to merge the data on the reporting pages as we will get multiple entries for the same taxa.

**Comment by Gary-van-Breda** [comment]
Yes - entirely a consequence of #108

**Comment by Gary-van-Breda** [comment]
If the taxa don't share a taxon_meaning_id, and we choose not to update the occurrence TTL ids, there is going to have to be some major surgery to the summary_builder.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda the taxa share a search code and external key, but not currently the taxon meaning ID. If this were the only issue, then it would be relatively easy for me to change the taxon meaning IDs in list 254 to the ones in list 251. However if it is easier for us to update all the taxon list IDs in the occurrences so that we only use list 251, then I think that is a cleaner solution in the long run.

@DavidRoy do you have any objection to me updating all the old records to use list 251 so list 254 can eventually be scrapped? Given what Gary says above I think this is cleaner and easier than just linking the lists as previously discussed.

**Comment by DavidRoy** [comment]
@johnvanbreda Yes, happy to move everything over to the latest list (251)

**Comment by johnvanbreda** [comment]
Ok, thanks. 

@Gary-van-Breda I'll try and do this ASAP then...

**Comment by johnvanbreda** [comment]
I've migrated the occurrence data over. The Work Queue will take a few hours to process it all though so the reporting tables won't be up to date yet. 

Here's the script for reference:
```sql
select cttl254.id, cttl251.id as new_id
into temporary to_fix
from cache_taxa_taxon_lists cttl254
left join cache_taxa_taxon_lists cttl251 
  on (cttl251.taxon=cttl254.taxon or cttl251.taxon || ' sp.'=cttl254.taxon)
  and cttl251.taxon_list_id=251
where cttl254.taxon_list_id=254
and cttl254.id in (select distinct taxa_taxon_list_id from occurrences where website_id=118);

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_update', 'occurrence', o.id, 100, 2, now()
from occurrences o
join to_fix tf on tf.id=o.taxa_taxon_list_id;

update occurrences o
set taxa_taxon_list_id=tf.new_id, updated_on=now(), updated_by_id=3
from to_fix tf
where tf.id=o.taxa_taxon_list_id;
```

**Comment by Gary-van-Breda** [comment]
I have reset the summariser and set it into catch up mode for Survey ID 562,
I'll leave it run overnight, and check the Annual summary and Year plot data tomorrow.

**Comment by johnvanbreda** [comment]
I've noted this morning that the cache_occurrences_* tables are not yet updated, due to a large amount of iNaturalist data being added overnight as part of a catchup. This may have a knock on effect as to when other parts of the system reflect the changes correctly.

**Comment by DavidRoy** [comment]
Can we give higher priority to the eBMS/ABLE data.  iNaturalist is lower priority.

**Comment by johnvanbreda** [comment]
Done - iNat work queue tasks now lowered to priority 3.

**Comment by DavidRoy** [comment]
The data is coming through for 2019.  I'm closing. Thanks
