### ISSUE TITLE
Add translations to www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#12]
Add language translations for: 
- [ ] Portugal
- [ ] Italy
- [ ] Germany
- [ ] Greek

**Comment by DavidRoy** [comment]
Yes. We would disable the system for Germany.  Do you think we need German for German-speaking countries?  Also, this list of countries is not complete so please suggest others needed

**Comment by chrisvanswaay** [comment]
The Swiss have a system running, but for Austria this could be very helpful. I can imagine they would start using this system. I can even imagine Andrea Grill (of Butterfly Conservation Austria) could help out in translation, she is a language miracle speaking at least six languages (including Dutch :-) fluently.

**Comment by chrisvanswaay** [comment]
The main thing on the short term is to create a file (or webpage, or google sheets) in which the translation from English to other languages can be done. Then Cristina can start looking for people to help out (eg. Andrea Grill in Austria, Andras in Hungary, Chiara in Italy). Would be good to have a large sets of languages available. And I guess there are not more than appr. 1000 words and sentences to translate.

**Comment by DavidRoy** [comment]
Here are the translations required.
[eBMS Translations required.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/2679052/eBMS.Translations.required.docx)
[eBMS Transect input system.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/2679055/eBMS.Transect.input.system.docx)

**Comment by chrisvanswaay** [comment]
Thanks, I'll inform Cristina.

**Comment by DavidRoy** [comment]
Spanish is not such a priority unless there are new regions that want to use the online system.  I 'think' the existing 3 schemes in Spain already have their own systems?

**Comment by CrisSevilleja** [comment]
Well, I started the Spanish translation to get used to the website because I will explain later to anyone that could translate it in other languages. But yes maybe it is not a priority Spanish. 

I think Spanish BMS has a website or system to input the data but I am not sure. Next week, I will talk with several Spanishes and I can ask where they store the data

**Comment by DavidRoy** [comment]
I agree this is a good place to start, and there is no harm in having multiple languages available

**Comment by DavidRoy** [comment]
Main pages
Full content: e.g. if you edit a basic page like the the front page, there is a “translations” tab which allows you to create/edit the translation for the whole page (http://dev-butterfly-monitoring.pantheonsite.io/node/1/translations )

Menus
Menus: the general process is shown here : https://www.drupal.org/docs/8/multilingual/menu-translation-in-drupal-8 . Most of the set up has already been done, so if you go to the appropriate menu under http://dev-butterfly-monitoring.pantheonsite.io/admin/structure/menu Each Menu item has a ”Translate” drop down operation option, where the translations can be entered for the menu links. 

Individual strings
These are handled under http://dev-butterfly-monitoring.pantheonsite.io/admin/config/regional/translate . It is possible to export all the strings that require translation for a language, edit them off line, and then import back in.

**Comment by DavidRoy** [comment]
Add translations for Czech and Croatian.  
@Gary-van-Breda I attempted to add in these languages via the admin page
http://dev-butterfly-monitoring.pantheonsite.io/admin/config/regional/language

But got error warnings - see: http://dev-butterfly-monitoring.pantheonsite.io/admin/reports/dblog

**Comment by Gary-van-Breda** [comment]
I've cleared the temporary file directory on http://dev-butterfly-monitoring.pantheonsite.io/admin/config/media/file-system (this was the source of the problems as the original value was a carry over from when I migrated the site on my development area, and did not exist on the pantheon site).
I've reloaded all the translations using page http://dev-butterfly-monitoring.pantheonsite.io/admin/reports/translations , There seems to be a bit of a disconnect between this page (which is now reporting that only a couple are missing - because they are not provided by the respective modules?), and the current status on page http://dev-butterfly-monitoring.pantheonsite.io/admin/config/regional/language , which shows rather variable coverage at the moment.
It looks like @DavidRoy only setup the Czech language: I will leave it to you to do the Croatian as a further test of this fix.
9 of the strings where rejected - I think because they had html in. They can be seen on the dblog reports page mentioned in David's comment above

**Comment by DavidRoy** [comment]
@Gary-van-Breda please revert back to English as the base language

**Comment by Gary-van-Breda** [comment]
English translations reinstated on both Dev and Test environments.

**Comment by CrisSevilleja** [comment]
Please could it be possible to add translations for Hungarian and Polish? 

@Gary-van-Breda If I want to include any translation, should it be done in the test environment?? http://test-butterfly-monitoring.pantheonsite.io/

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : yes, as I understand it, the Test site will be the one copied to the Live site. Any changes you wish to see on Live should be done in Test, not Dev.

**Comment by DavidRoy** [comment]
Closing this issue, as translations implemented or in hand
