### ISSUE TITLE
Update European Butterfly checklist for use in www.butterfly-monitoring.net/mydata

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#13]
Update checklist on warehouse 2 using the attached.  

[Euro Butterfly Checklist 2018.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/2729366/Euro.Butterfly.Checklist.2018.xlsx)

**Comment by johnvanbreda** [comment]
A few thoughts:
1) What happens to any existing taxa which are not present on the new list? There are quite a few, though many of them have no records. The following names do have records though:
Polyommatus bellargus
Polyommatus coridon
Argynnis aglaja
Argynnis adippe
Pieris sp.
White sp.
Colias hyale/alfacariensis
Pale/Berger's Clouded Yellow
Pyrgus armoricanus/serratulae
Leptidea sinapsis/juvernica
Wood White/Real's Wood White
Thymelicus sp.
Skipper sp.
2) Is the intention to set up taxon attributes to hold the flag data for each country? Presumably this might be best done as a set of lookup attributes, one per country.
3) If we apply this update to the list, what impact will it have on the existing functionality?

**Comment by DavidRoy** [comment]
1.  Two issues:
- We'll need to link the old names to the new ones, relegating those to synonyms.
- retain recording aggregates as the checklist does not include them
2. That sounds the best option to me.  The app will need to enable switching of species lists by country.  The eBMS online transect system will also need the ability to relate the species list to country of the transect.  Relates to existing work on UKBMS - https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/61.  
3. @kazlauskis @gary-van-breda to advise

**Comment by DavidRoy** [comment]
The source for the list is this paper:
https://zookeys.pensoft.net/article/28712/list/5/

A better format for input might be this file attached to the paper

**Comment by DavidRoy** [comment]
I think a static version for the App is ok as the European list is unlikely to change in the next two years

**Comment by johnvanbreda** [comment]
Regarding the update, my thoughts are that I should create a completely new list since there may be some manipulation required to merge the existing aggregates/synonyms in. I also want the updated list to have at least a basic taxonomic hierarchy. That allows me to manipulate it without affecting the existing list and we can ensure it is correct before deciding to switch the recording form over to the new list. At this point we can update the existing records to point to the matching names on the new list and potentially discard the old list.

@DavidRoy @Gary-van-Breda Any objections to this approach?

**Comment by DavidRoy** [comment]
Agreed, sounds eminently sensible

**Comment by johnvanbreda** [comment]
If we follow this approach, I will try to splice in the existing names which are missing from the new list. This brings about a few questions (probably for @DavidRoy):
* All recording aggregates should be brought over presumably. If so, then is there a set of rules I can use to generate the country codes from the underlying species data? For example, if both species in the aggregate are present for a country, then the aggregate can be present. If one is absent, then can we set the aggregate as also absent? What about when one of the taxa is one of the other codes such as I?
* If a species taxon is in the old list but not in the new list and there are no records, is it safe to ignore it?
* If a species taxon is in the old list and not in the new list and there are records, I can try to work out if it is a synonym and if so of what, or a new taxon. I'll probably need my efforts in this area checked by an expert!

**Comment by johnvanbreda** [comment]
That all sounds fine but for 1 point. I'm not sure I see the benefit of loading the recording aggregates into a separate list. They ideally need to sit in the "hierarchy" provided by this list so will have a parent within the new list anyway. Also they will be flagged as rank=Species aggregate, so will be easily filterable from the species if required. 
Therefore I think the first part of point 3 is changed to:
"We add the recording aggregates into the main list, linking them to the appropriate parent genus and using attributes to link them to countries...".

Also, just to clarify, any names used in the old list which are not in the new list because they are synonyms will not actually be added to the main list, but will be dealt with as a part of point 4.

One final point. Indicia has quite a few reports which use the TVK of both the preferred name and name as recorded to do name mappings. It may be wise at this point to assign some kind of similar unique ID to each taxon name (it would also make the dealing with synonymy in point 4 easier). I had thought that we could use the Catalogue of Life name matching service and use the Catalogue of Life ID for each name (which is how RIS-Ky Cydas works) but I've just tried a small sample of butterfly names and only got a 66% hit rate. An example failure - Erebia aethiopellus - was on the 2011 version of the CoL but not on recent versions and I can't find out why. GBIF could also be used to get a GBIF ID from their "taxonomic backbone" but in my experience this can also be a bit messy, with lots of variations of names offered from different sources and only some of them work. If you don't have any better ideas, I propose that I simulate our own "global ID" system just using Indicia's taxon ids and if necessary, in future we will have to update this to a better system and write a script to update the values across the database.

Let me know your thoughts - if we are going round in circles then we can Skype later in the morning, but often I find an offline conversation gives me the chance to go and do a bit of research for each reply which can be easier!

**Comment by DavidRoy** [comment]
I agree to all these points.
- add recording aggregates to the master list
- creating our own uniqueID to help with reporting
- no need for skype as this works well for me

**Comment by johnvanbreda** [comment]
Thanks. I've prepped the list for import. The one remaining question before I do it is the order of precedence of country codes for an aggregate, i.e. where the 2 constituent species have a different code how do I know which code to pick? Can I assume that if a constituent species is absent that it is OK to flag the aggregate as absent so it does not appear on country lists? What about migrants/extinct etc?
For reference here is the list of codes. I basically need it sorted in order of precedence.
A = Absent
P = Present
P? = Possibly present
M = Regular migrant
I = Irregular vagrant
Ex = Regionally extinct

**Comment by johnvanbreda** [comment]
@DavidRoy do you have any thoughts on the above question?

**Comment by DavidRoy** [comment]
If either segregate has a presence/migrant/vagrant then the aggregate should have these.  So the order of precedence should be:
P = Present
P? = Possibly present
M = Regular migrant
I = Irregular vagrant
Ex = Regionally extinct
A = Absent

@johnvanbreda can you send me a copy of the aggregate/segregates when ready to load so I can review

**Comment by johnvanbreda** [comment]
@DavidRoy I've attached the spreadsheet which has been prepared for loading.
[Euro-butterfly-checklist-formatted.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/2875041/Euro-butterfly-checklist-formatted.xlsx)

**Comment by johnvanbreda** [comment]
@DavidRoy, @Gary-van-Breda - just letting you know I've created an ABLE website registration on warehouse1 so we have somewhere to load this list. ID=118.

**Comment by DavidRoy** [comment]
The checklist file looks good.  @johnvanbreda can you go ahead and load this

We may want to add further recording aggregates but this can happen at a later date.  We will also want to add in common names to the list.

**Comment by Gary-van-Breda** [comment]
Given that we have now taken a decision to stay on Warehouse2 for the immediate future, where does that leave us with the species list? I can see an ABLE list on the warehouse2 - but all the forms on the Test ABLE site (which looks at warehouse2 i.e. the LIVE EBMS data) are currently configured to use the EBMS list.

**Comment by DavidRoy** [comment]
Stick with the current ebms list initially.  We can then test out the new list with less time pressure

**Comment by DavidRoy** [comment]
@johnvanbreda can you please do the following:
1. revise External key to be 'eBMSxx' rather than 'ABLExx' 
2. load the new eBMS list (https://github.com/BiologicalRecordsCentre/ABLE/files/2875041/Euro-2. utterfly-checklist-formatted.xlsx) into warehouse1 so that it is available for the mobile application that Karolis is developing
3. Provide an export for Karolis.  @kazlauskis to define export format needed

**Comment by johnvanbreda** [comment]
I've uploaded the species list. @kazlauskis let me know if you need a report or other export format.

**Comment by johnvanbreda** [comment]
Attaching the actual list uploaded for reference.
[Euro-butterfly-checklist-formatted.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/3148932/Euro-butterfly-checklist-formatted.txt)

**Comment by kazlauskis** [comment]
@johnvanbreda Thanks for the list. If this included the common names then I would be happy to use it as it is. This turned into a report for me to download would be excellent too as I am not sure how often this list will change in the future.

**Comment by DavidRoy** [comment]
@kazlauskis we don't yet common names included but will work on this.  The list will not change for at least two years, other than adding common names.

**Comment by johnvanbreda** [comment]
@kazlauskis What info do you need in the report? Do you want 1 row per concept, or 1 row per name? Incidentally there are a couple of taxa with common names, not many though.

**Comment by kazlauskis** [comment]
As David has suggested, the list won't change any time soon so I suggest just adding the warehouse ids to the CSV file you have attached here and I would be good to go. Thanks!

**Comment by DavidRoy** [comment]
@johnvanbreda are you able to supply the list to Karolis now?

**Comment by johnvanbreda** [comment]
@DavidRoy - I may have misread the above - did you actually mean to request the list to be loaded onto warehouse1? I thought that we were sticking on warehouse1.

**Comment by DavidRoy** [comment]
@johnvanbreda we are sticking on warehouse2 for the current transect input system for 2019, which has the 'old' eBMS species list.  We will migrate to warehouse 1 once the new species list is available

For the mobile app, we will use warehouse1 and this will use the new species list (with country lists)

Can you confirm the current status of the lists?

**Comment by johnvanbreda** [comment]
Ok, the list is now on both warehouses. @karolis, for warehouse1 the list ID is 251. I've extracted the data using the following query (it was easier to aggregate the country data rather than loads of joins):
```sql
select ttl.id as taxa_taxon_list_id, ttl.taxon_meaning_id, ttl.taxon_id,t.external_key, t.taxon,
  (select string_agg(ttla.caption || '=' || t.term, ' | ' order by ttla.caption) 
   from taxa_taxon_list_attributes ttla
   join taxa_taxon_list_attribute_values ttlav on ttlav.taxa_taxon_list_id=ttl.id and ttlav.taxa_taxon_list_attribute_id=ttla.id
   join cache_termlists_terms t on t.id=ttlav.int_value)
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id
where ttl.taxon_list_id=251
order by ttl.taxonomic_sort_order nulls first;
```

The list data are attached. Let me know if you need anything else.
[able-species.csv.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/3213306/able-species.csv.txt)

**Comment by kazlauskis** [comment]
Looks good, thanks.
