### ISSUE TITLE
Improvements to ability to delete occurrences

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#137]
following from #122 

when exploring records and selecting edit option, e.g. https://butterfly-monitoring.net/enter-app-record?occurrence_id=11816913&sample_id=

There is no option to delete an individual occurrence.  Only option to delete entire list of records.

Actions required:
1. ability to delete individual occurrences from a sample
2. ability to delete all occurrences from a sample
3. add information message when deleting that there will be upto a 15 minute delay until reports are updated, due to background processes

**Comment by johnvanbreda** [comment]
The generic record form dynamically adapts to the record you are editing. As this one is the only one in the sample, it behaves like a single record form. If you go to a record which belongs to a sample with other records in it, then you get the ability to remove just one record or delete the list, e.g. https://butterfly-monitoring.net/enter-app-record?occurrence_id=11691100&sample_id=. 

Should the message appear on the form all the time, or only after a deletion? But, shouldn't this message apply to updates as well? So, a message at the top of the form explaining "Changes that you make to records using this form will take up to 15 minutes to be updated on reports due to background processes"?

**Comment by DavidRoy** [comment]
Thanks.  That makes sense.  Please could you add a message to the page (for edits and deletes) that any changes to the record will take 15 minutes for the update.  We can then close this issue

**Comment by johnvanbreda** [comment]
Done
