### ISSUE TITLE
JS Error when editing node with json widget

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#144]
The inclusion of the json.js from the json widget media directory seems to break the admin toolbar. It looks like this version of JSON.parse can't handle being given a null.

Why are we redefining JSON?

I don't know if this has a knock on effect in preventing other JS from running.

**Comment by DavidRoy** [comment]
@BirenRathod is the same issue we've had on other sites with recent Drupal updates?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I suspect this has always been the way since the jsonwidget was a third party library we just copied into our JS. In fact it's even worse as we also include the json2.js file if the json resource is added which does the same.

Having just tested what happens if I strip this all out though, if you click view source on the JSON widget control, then although it works, the source is unprettified. So I guess that's why a modified version was included in the library - in fact it says this in the header comment.

So, I'll do a couple of pull requests for you to review for client_helpers and media which removes the extraneous redeclarations of JSON and I'll modify the widget to use built in prettifying.

**Comment by johnvanbreda** [comment]
I've reviewed again, merged and closed this issue.
