### ISSUE TITLE
Verification page does not reflect verification filter

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#164]
Filters setup as listed at:
https://butterfly-monitoring.net/admin/filters-list

But verification page does not apply these, e.g.
https://butterfly-monitoring.net/admin/filter-edit?filters_user_id=7620

is not applied for user = https://butterfly-monitoring.net/user/1198 
who sees all records in the verification system
https://butterfly-monitoring.net/verification

rather than restricted to country2016= Hungary

**Comment by johnvanbreda** [comment]
This was a caching issue. When we had performance issues in spring, since every report page tends to load a user's report filters and they only change occasionally, they were contributing to the overall problem due to the sheer number of loads. I added caching to the load of the filters to fix this. That does mean after adding a filter it won't appear immediately, but for obvious reasons I'm not keen on reverting this change.

As an alternative to a complete clear of the Indicia cache (which has a performance effect across the site), I have added code so that if you masquerade as the user with the new filter, then visit the verification page, add `&refreshcache` to the page URL and reload it, it will refresh the caching on just that one page. You can then remove the `&refreshcache` parameter and it should be OK going forwards.
