### ISSUE TITLE
geographic verification rule-sets for butterflies

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#187]
require rule-sets imported into Indicia warehouse to be used for ABLE/eBMS data.  May need some discussion on how to implement.

source data comes from processing of GBIF (via Bas Oteman).  Format is:

spName,startDoy,endDoy,lowerX,upperX,lowerY,upperY,maxNumber
Leptotes pirithous,6,118,1666139.334,1744872.883,949408.2163,1028141.765,9999
Leptotes pirithous,6,118,1744872.883,1823606.431,949408.2163,1028141.765,9999
Leptotes pirithous,6,118,1902339.98,1981073.528,949408.2163,1028141.765,9999
Leptotes pirithous,6,118,1981073.528,2059807.077,949408.2163,1028141.765,9999

**Comment by johnvanbreda** [comment]
We could probably script a process which converts these into text files in the correct Record Cleaner format, or perhaps better, import the data direct into the PostgreSQL tables. I presume there will be one set of rules for every species in the eBMS list? What do the lower & upper X/Y values refer to?

**Comment by DavidRoy** [comment]
Max number is the limit to the number of butterflies in a single observations. For exampleaccept a record of 1000 Pieris napi individuals at a single location, but 1000 Parnassia apollo individuals would be highly suspect. However, this field is not populated (i.e. set as default of 9999) so can be ignored for this purpose.  i will copy you into an email thread about the way forward with this requirement.

**Comment by johnvanbreda** [comment]
Information provided on how the x,y values work:

> because flight time strongly depends on location we estimated the start and end day of the year (doy) for each species in all squares they occur (we used a grid covering Europe, the coordinate system is ETRS (epsg:3035)). So in our database we have a list of squares with species present. If a square/species combination is not present the observation is invalid, if it is available the doy is checked against startDoy and endDoy. 

Waiting for the full list before writing an import script and/or custom verification rule tool.

**Comment by DavidRoy** [comment]
Following discussions, start with some scoping of options.
Potential approach is an ElasticSearch Species index which stores:
- geographic range polygons (pre-built)
- phenology by bioclimate zomes (pre-built from BMS data)

@johnvanbreda to scope out scale of work required

**Comment by johnvanbreda** [comment]
Having looked into this further, Elasticsearch's limitations around joining across documents mean I'm not sure this is the right approach. We would have to run multiple queries, probably one per species, rather than use relational joins to do checks in one or two queries.

So, I think we can store range polygons in the existing cache_verification_rules_without_polygons table. Currently this table contains a fairly simple format ideal for the range checks required here - species key and geometry. It is autogenerated and currently gets overwritten when verification rule data are changed so we would want to change this to allow manually created rules to be imported and kept in place. Basically we would then be bypassing the Record Cleaner rule file format to specify what Indicia needs directly.

For phenology by bioclimatic zones, a few questions:
1. Do you have a link to the type of zone map you want to use? The ones I've found are fairly simple and will probably work OK as a standard indexed location layer. Perhaps we ought to flag these types as "zones" as opposed to "locations" but otherwise they can be used in the same way. 
2. Do you need to take into account life stage, or are we working on the basis that will be too complex?
3. What granularity over date is required for phenology checks? Day/week/month?

Depending on the answers to the above we may then need to add a table which links species keys to bioclimatic zone IDs with phenology data for each combination.

One more question:
4. For both types of rule, is there a need to auto-update based on data coming into ABLE, if it is verified?

**Comment by johnvanbreda** [comment]
Given the latest file examples provided by @DavidRoy here are my thoughts on the best approach.
1. Add a new custom warehouse module(s) for combined range/period within year checks. We need custom code because the existing period_within_year checks are not bound by a range.
2. This would declare a custom table, with fields for species TVK (external key), bounding box, start day in year, end day in year.
3. Manually import the spreadsheet and convert to Web Mercator projection (so our queries are faster). 
4. Raise flags against records if:
  The species has at least one defined bounding box but is outside all of them.
  The species is inside one of the bounding boxes but the date is outside the range.
But not if:
  There are verified records if the species within a certain distance and within a certain number of days (TBD) - so it will learn from existing data.

Another complexity is the fact that we would want to be able to control which websites rules are applied to, so these rules do not get applied to UKBMS data or UK rules applied to EBMS data. But I don't think this is actually an issue because the species external keys are different so Indicia will not attach rules from the UK to EBMS data or vice versa.

**Comment by DavidRoy** [comment]
@johnvanbreda a heads up that we returning to this issue and we would like to work on this again in Autumn/Winter 2022/23.  We will provide the range maps and flight periods in advance

Can you estimate the time required to develop this functionality

**Comment by johnvanbreda** [comment]
@DavidRoy I think we should allocate 1 day to reviewing the latest available rule data and building a demo query on the dev warehouse, to ensure that the approach is correct and performant. Then probably a further 2 days to build the combined range/phenology checker verification check module and a further 1 day to cover imports of the rule data.

**Comment by larspett** [comment]
The spatial x phenology checker will need to accommodate the full European range & will then require some careful planning to handle flight times of for instance orange-tip from the far south to the far north to avoid that phenology rules end up too vague/broad

16 maj 2022 kl. 11:35 skrev John van Breda ***@***.***>:

﻿

@DavidRoy<https://github.com/DavidRoy> I think we should allocate 1 day to reviewing the latest available rule data and building a demo query on the dev warehouse, to ensure that the approach is correct and performant. Then probably a further 2 days to build the combined range/phenology checker verification check module and a further 1 day to cover imports of the rule data.

**Comment by DavidRoy** [comment]
Closing so can summarise next steps in a new issue
