### ISSUE TITLE
Add dutch common names

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#225]
Following instructions:
https://github.com/BiologicalRecordsCentre/ABLE/issues/97

1. Make sure any new languages are registered in the Indicia Languages list (under Lookup lists on the warehouse).
2. Create a spreadsheet with the following columns, only for the rows which have a common name:
taxa_taxon_list_id
common name (English)
common name (Swedish)
3. Add a "Common Names" column containing this formula:
=CONCATENATE(IF(ISBLANK(B2),"",CONCATENATE(B2," | eng",CHAR(10))),IF(ISBLANK(C2),"",CONCATENATE(C2," | swe",CHAR(10))))
This gives output like the following:
English | eng
Swedish | swe

But for Dutch (nld) not Swedish.  File is attached.
[dutch names.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/4538248/dutch.names.zip)

@johnvanbreda can you please do this import to make sure it is done correctly.  Please can you give some urgency so we can incorporate in the app for this field season

**Comment by johnvanbreda** [comment]
Done. A few notes:
1. When the Swedish names are added, the spreadsheet should be updated to add the Swedish names to the existing common names data, not replace it. Otherwise the importer would remove existing names.
2. I needed to add set taxon_group to insect - butterfly on first page of importer. The language could be left blank as it's only used when creating the accepted name.
3. Map taxa_taxon_list_id to Taxa taxon list > id. Make sure the common names are mapped, not the other 2 fields.
4. Set lookup of existing records to "Species list and taxa taxon list ID
5. Although not necessary, I used the following query to ensure the common names have their external key filled in (just for completeness).
```sql
update taxa t
set external_key=t2.external_key, updated_on=now(), updated_by_id=3
from taxa_taxon_lists ttl
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id=ttl.taxon_meaning_id and ttl2.preferred=true
join taxa t2 on t2.id=ttl2.taxon_id
where ttl.taxon_id=t.id
and ttl.preferred=false
and t.external_key is null
and ttl.taxon_list_id=251
and ttl2.taxon_list_id=251
```

**Comment by kazlauskis** [comment]
Thanks, I will now add it to the app.

@DavidRoy in Transifex some more languages have species names translated and if we added them all to the warehouse then I could clean import it all to the app. I can provide excel files for these languages. https://www.transifex.com/ceh/ebms/app_species_names

**Comment by DavidRoy** [comment]
@kazlauskis yes, please pass on the names translated in Transifex.  Can you include the taxa_taxon_list_id as well?
