### ISSUE TITLE
Import NUTS 1 region SHP into Warehouse 1 to enable country filtering within www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#23]
@johnvanbreda We also need a 'country' layer within the system to set roles at the country/monitoring scheme level, i.e. above the regional/NUTS 2 level.
@Gary-van-Breda how would this link to the existing country layers in the system?

Import NUTS 1 region SHP into Warehouse 1 to enable regional filtering within http://www.butterfly-monitoring.net

Source as for NUTS 2

**Comment by johnvanbreda** [comment]
@DavidRoy NUTS level 1 isn't actually country level though is it? It's higher than level 2 of course, but still regional. Here's a PDF: https://ec.europa.eu/eurostat/documents/345175/7451602/NUTS1-2013-EN.pdf.

Presumably the layer could add to the existing countries layer we use rather than replace it?

Also I wonder whether we can use the NUTS 2 location codes which contain the country ISO code could be used to simplify the indexing, as it might not be necessary to spatially index against both layers (which has a performance overhead).

**Comment by DavidRoy** [comment]
@johnvanbreda sorry, my misunderstanding.  I think we need three layers for setting up roles and for reporting across Europe:
1. Country
2. NUTS1
3. NUTS2

This could be a single layer as presumably these are hierarchical?

**Comment by johnvanbreda** [comment]
Hi @DavidRoy 
I think they can be 3 layers (3 location types) but have parent_id references across the layers. I've written, but not yet deployed some code so that if the NUTS2 layer is spatially indexed, it would then automatically include the NUTS1 and Country data in the list of location IDs associated with each sample, so reporting becomes easy.
I'll try and get the layers imported (on warehouse2?) ASAP. However we will need to get warehouse2 upgraded to the latest v2 code. @Gary-van-Breda is that OK with you? 
Regards
John

**Comment by johnvanbreda** [comment]
@DavidRoy are you expecting to use the Countries data provided by Eurostat (https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries)? If so, these are layers of world countries, not just EU. Though if we use the NUTS regions to drive the indexing then other countries would be ignored (or perhaps we should just delete them for now to avoid confusion). 

Also the boundaries have no buffering out to sea which means any coastal records could be missed and it also makes the boundaries fairly complex in some places. So, given these caveats are you happy to use the Eurostat layer?

**Comment by DavidRoy** [comment]
@johnvanbreda yes to using the Eurostat layer.  We can keep the full list of countries in the layer as we might extend in the wider Western Palearctic region.  Hopefully we can configure the drupal forms to restrict the drop-down lists?

Butterfly monitoring is also terrestrial so not having the layers out to sea is ok too!

**Comment by johnvanbreda** [comment]
I've added the new layers. For clarity, the setup is now:
1) Existing layer Country (ID 2188), contains the short list of "countries" we've been using in iRecord (e.g. England, Scotland, Bailiwick of Jersey). This is not a complete list, just covers the regions where iRecord is in common use. Spatially indexed and available for filtering in reports.
2) New layer Countries 2016 (ID 16516) contains the entire list of countries from the Eurostat layer (e.g. United Kingdom, Jersey). It does contain the crown dependencies in their own polygon. Spatially indexed, but see the note below and not currently available for reporting filters (though can easily be added). It is loaded at 1:10m precision (low precision).
3) New layer NUTS Level 1 (ID 16517) contains all NUTS level 1 boundaries, with the parent_id set to the relevant country in Countries 2016. Spatially indexed, but see the note below and not currently available for reporting filters (though can easily be added). It is loaded at 1:3m precision (medium precision).
4) Previously loaded layer NUTS Level 2 (ID 14587) contains all NUTS level 2 boundaries, with the parent_id set to the relevant region in NUTS Level 1. Spatially indexed but not currently available for reporting filters (though can easily be added). It is loaded at 1:1m precision (high precision).

To avoid the overhead of spatially querying all the polygons when the spatial index builder links samples to indexed locations, the NUTS Level 1 and Countries 2016 use a new feature whereby they are automatically indexed against a sample if the sample falls within their child NUTS Level 2 polygon. So, a sample which falls inside NUTS Level 2 Devon can be automatically linked to Southwest England and United Kingdom without actually doing a spatial query for the 2 additional polygons. This is efficient but does mean that records outside any NUTS level 2 area won't be linked to a Countries 2016 polygon.
