### ISSUE TITLE
ButterflyCount app - allow users to 'favourite' sites

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#239]
Enable recorders to make sites where they have created 15 minute counts as favourites.

Then enable these sites to be selected for future surveys, then no need for GPS tracking or to draw a survey area.

**Comment by CrisSevilleja** [comment]
Users of the ButterflyCount app mentioned this function as useful for making more repetitions to 15-minute count areas. I don't see clear how this can be integrated into the app, but definitely it would be a great function. 

Although I would include this function inside the 15-min count survey and in the area variable, I would select the option of your favorite route or area saved but continue using the GPS for the coordinates of the individuals.

Not urgent but good to include

**Comment by larspett** [comment]
It is similar to the feature request that we had for our Swedish point sites that essentially are repeated (fixed area) 15-min counts. Would be good to solve that one but am unsure how we can do that without confusing users that don’t have such sites

**Comment by DavidRoy** [comment]
@kazlauskis do you have any ideas for how to implement this?

**Comment by kazlauskis** [comment]
We could build something similar to iRecord App's past locations list. In the app, every new location used for a record is saved to a list. Users can "favourite" places, making them stick to the top of the list. This way, users can override whatever the GPS has recorded by picking a track/location from their past records. The simplest way to build it would be to keep the past locations list locally and don't sync it with the database. i.e. don't sync locations between multiple users' devices.

Here is how it currently looks like in the iRecord App:
![IMG_FF370557FE5C-1](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/9854dbf2-b91f-46fd-915a-cdfc2a36a82d)

**Comment by chrisvanswaay** [comment]
Just thinking out loud. 
To get a better grip on the RL species (now many are missing on the standard transects) we would need recounts of 15-min counts with such species (or at least in the close neighbourhood). A location with an important/threatened/rare species could get a high grade (three stars or so) without disclosing which species makes it so important (to avoid twitchers using it). An option could be that a recorder can ask for 'sites with three stars within 25km' (or whatever) and then you would see where the previous transect was, and you could try to do a recount there. Very often it will be on a path or so, so good chance you walk more or less the same transect as the previous one. That would give us a recount of the rare species on the same spot.
Would something like that be an idea?

**Comment by chrisvanswaay** [comment]
So they don't have to be your own counts. On a holiday on a remote mountain you could do a recount of a 15-min count from someone else two weeks ago.

**Comment by DavidRoy** [comment]
@kazlauskis you suggestion looks good to me.  Based on Chris' post, we should make all locations available.  Could you add a filter for users to restrict to just their own sites or show all?
@chrisvanswaay I like your suggestion but best to consider this after we've got the main functionality in place?

**Comment by chrisvanswaay** [comment]
@DavidRoy I realise this could be a lot of work to set up, but anyway good to keep in mind and see when it will be possible.

**Comment by kazlauskis** [comment]
@DavidRoy this past-locations list is generated from own records only. The current implementation doesn't use a warehouse report to fetch locations, showing only those created on the device. It doesn't mean we couldn't use a report and fetch personal or global locations. It would take more time to build it, though.

**Comment by DavidRoy** [comment]
@kazlauskis understood. Let’s still to original requirement and I’ll add a separate issue for the extended option

**Comment by DavidRoy** [comment]
@kazlauskis understood. Let’s still to original requirement and I’ll add a separate issue for the extended option

**Comment by kazlauskis** [comment]
We are building the past locations + favourites functionality. In this phase, we're not syncing user locations to the database and keeping them locally. Is that right? In such case, the user journey could look like this:

1. User starts a survey, the GPS tracks the walked trail, and the user can edit/draw the location manually. Nothing new up to this point.
2. User presses the survey Finish button, and the current survey location is saved to the past locations list. The location name (not uploaded) defaults to the current date.
3. User starts another survey and the GPS starts tracking the user.
4. The user can open up the locations page and select a location from the past. Selecting a past location, the GPS tracking is stopped. 


Extra thoughts and edge cases:
- By swiping the location to the left and pressing Edit user can make the location a favourite, which pins it to the top of the list. Also, editing the location, its name can be changed from the date it was originally set to whatever other text. Swiping to the left also reveals the location Delete button.
- Editing a survey location that was picked from the previously saved list will update the location in the locations list too. 
   - If the user selects a past location for a survey but then re-enables the GPS tracking, it will not update the past location. 
   - If the user selects a past location for a survey but then deletes the survey track, the past location is not deleted. To delete a past location it has to be swiped to the left and deleted in the past locations list.
- Instead of using favourites, we could instead list locations sorted by distance to the user, the same way as the moth traps list.

**Comment by kazlauskis** [comment]
@DavidRoy, @chrisvanswaay, @CrisSevilleja Is everyone OK with the above? In particular, in this first iteration, saved locations will only exist on the device and won't be uploaded to the site.

**Comment by DavidRoy** [comment]
@kazlauskis This is great - please go ahead.  It is fine for this just to be on the device.

One extra suggestion, could the list of locations be ordered by:
- favourites
- distance to the user
