### ISSUE TITLE
ButterflyCount: searching for common names works only if the language is selected

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#266]
@kazlauskis  @DavidRoy 

Chris van Swaay reported that he couldn't search for Dutch common names on the app while doing a count. It was strange because I could do it. 

We realised that he couldn't search for Dutch common names until he selected the language Dutch in the app settings. He didn't select it before because he saw the whole app in Dutch, so it was no necessary to select the language. 

I think it is something that could happen to more people. How do you think it is the best way to resolve it?

**Comment by kazlauskis** [comment]
@CrisSevilleja Yes, you have to have the language selected before it allows to search for common names. Since Chris was testing the app from the very beginning and we have imported the species names at some time not too long ago this required some initial users to re-select their language to get the full benefits. I think, this shouldn't be a problem to any new users. If it is then please reopen this and I will dig deeper into this. Thanks!
