### ISSUE TITLE
15m count - indicate if moths/dragonflies/bees are included in the count

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#268]
As the species list grows, if other groups (moths, dragonfly, bumblebees) are not included in the species list we do not know if recorders either saw none (i.e. a zero count) or are only recording butterflies (i.e. other taxon groups are missing values).  This difference is important for future analysis.

The requirement is an additional sample attribute(s) with a flag of whether other groups were counted.  Possibly a set of yes/no options for butterflies (default to yes), moths, dragonflies, bumblebee

**Comment by kazlauskis** [comment]
Would something like this work? Another screen where you can select all the recorded groups:

![Screenshot 2020-07-01 at 09 30 17](https://user-images.githubusercontent.com/7383162/86222010-90087180-bb7d-11ea-84d4-29fe65e92d1d.png)

**Comment by larspett** [comment]
I can see that there is presently a strong movement towards adding lots of species and non-butterfly features but am concerned that the complexity and volunteer-deterrence potential grows exponentially the more features we add. Will there be options to **limit** rather than add features? I would need a **lean** rather than a feature-filled app for what I coordinate, or at least a general setting to limit species lists to a) country-specific butterflies and selected moths (burnet moths in my case, many more day-active ones in e.g. Finland) b) optional addition of more (country-specific) taxon groups c) optional addition of add-on features like the mentioned "nice spot" comments etc. I would also like the general 15-min counts to be optional, not the default method since the presence of it will surely lure volunteers away from the standardised methods we currently have and make the inbound flow of data considerably more messy.

**Comment by kazlauskis** [comment]
As an idea, some of the attributes could be moved away from the survey screens into the app settings. Eg. we could have this as a setting in the app menu - `Species I always record`, which if set would hide any unnecessary fields from the surveys and silently set the values in the background.

**Comment by DavidRoy** [comment]
@larspett I understand your concerns and we'll keep the interface as clean and as simple as possible.  Extra species groups are needed as some schemes across Europe record more than butterflies and a selection of day-flying moths.

@kazlauskis having these options as settings is good.  By default, the app should just be for butterflies

**Comment by CrisSevilleja** [comment]
I think this issue can is done and can be closed @DavidRoy
