### ISSUE TITLE
Downloads - Transect counts report improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#289]
https://butterfly-monitoring.net/downloads
![count download](https://user-images.githubusercontent.com/2699478/87063068-c3926e00-c205-11ea-8e3a-541f5298b5a5.png)

To help joining with visit (sample downloads) and site details, add [Location.id] labelled as Transect ID

Date field should be in 'DD/MM/YYYY' format to match format in Visit (samples) file
Remove field 'Survey' as all data is from a single survey
Add 'Parent_id' named as 'Transect Sample ID'
rename 'Sample ID' as 'Section Sample ID'
rename 'Section name' as 'Section Name'
rename 'Species' as 'Species Name (entered)'
rename 'Preferred' as 'Preferred Species name'

Remove the following columns as they included in the Visit (sample) file:
'Recorder name'
'Start time'
'End time'
'Site name'
'Wind direction'
'Wind speed'

**Comment by johnvanbreda** [comment]
Done. A couple of points:
* I also deleted temp (def C) as this column is included in the Visit (sample) file.
* The date format was already correct I think - let me know if you spot cases where it isn't.

**Comment by RetoSchmucki** [comment]
Hi @johnvanbreda , @DavidRoy  ask for date format to be "DD/MM/YYYY", actually it would be better to have the other one that is "YYYY-MM-DD" wich is a POSIX standard. the issue was in the export that David sent me, for example where date format in the count table was "2020-03-07" while in the visit table it was "27/07/2018".
