### ISSUE TITLE
rename ABLE/eBMS websites in Indicia warehouse

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#292]
The website will outlive the ABLE project therefore can the website names be changed:
Website ID renamed from 'EBMS' to 'EBMS old'
Description updated to 'European Butterfly Monitoring (old version no longer used)'

Website ID renamed from 'ABLE' to 'EBMS'
Description updated to 'European Butterfly Monitoring Scheme (EBMS) including the Assessing ButterfLies in Europe (ABLE) project.'

Change to be propagated to cache-tables and ES index.  Test that this change does not affect any functionality on www.butterfly-monitoring.net

**Comment by johnvanbreda** [comment]
Done. Just for info, a website title change is not automatically updated in the cache builder at the moment, since it's a rare case and it could potentially trigger an enormous update (e.g. if you accidentally updated the iRecord website title). So I've queued the records for update, setting the priority to 3 so other changes take precedence:
```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, 100, 3, now()
from occurrences 
where website_id=118;
```
