### ISSUE TITLE
Website Email send issues

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#339]
Hi @kazlauskis  some colleagues from Vlinderstichting were trying to register on eBMS through the app and it doesn't work well. Specifically, Anthonie Stip try to register and the app gives the message that the account was already registered when it was not the case... Now the user is blocked. 

I tried to register another email account from my phone and the app allows me to do it but I didn't receive the confirmation email so the account is block now and I cannot log in on the app then. Could you check what is happening? Thanks

@DavidRoy

**Comment by DavidRoy** [comment]
@BirenRathod can you check the status of emails being sent from butterfly-monitoring.net and whether there is an issue due to recent changes to spam filtering

**Comment by DavidRoy** [comment]
@CrisSevilleja accounts have been activated in the last few days but we'll investigate

**Comment by CrisSevilleja** [comment]
thanks @DavidRoy

**Comment by BirenRathod** [comment]
@DavidRoy This is not due to recent changes of spam filtering module. Although recently last week I have upgraded SMTP module which uses PHPmailer library. In general it is not a problem but sometime it fails to send notification email. This happens only website registered with non CEH email address. Because relaying email blocked by third party email firewall service which has linked with SMTP module and found that registered email address could be spam.

I have been checking last two days all users on butterfly monitoring website, and found out some users (very few) still blocked but most been activated. 
Also, I checked log message and found out, there are some failed smtp notifications. I will investigate more into it and find out about it. Why have then been failed?

**Comment by DavidRoy** [comment]
@BirenRathod I notice that all 4 new registrations today are blocked.  Can you keep an eye on this problem please

**Comment by BirenRathod** [comment]
@DavidRoy When I checked the log message, there is no SMTP's error message logged. In fact those accounts been blocked because users can't able to successfully activated their accounts.

**Comment by DavidRoy** [comment]
thanks for checking @BirenRathod 

@CrisSevilleja would you be able to do some testing on the registration/account setup to confirm it works as expected

**Comment by BirenRathod** [comment]
@CrisSevilleja Please hold on for testing. I will let you soon.

**Comment by BirenRathod** [comment]
@CrisSevilleja You can now do some testing.

**Comment by CrisSevilleja** [comment]
@DavidRoy @BirenRathod  I did some testing of the registration from the website and from the app with different accounts and everything works well, even the translation of the email. Thanks

The only issue is the verification email sometimes reaches the spam folder, and users can miss it. Maybe we can mention it in the welcome message. Another thing is if the account is not active with the verification email, that email account cannot be used again on the eBMS system because it is already used. A bit annoying for some users who don't understand that. 

In general, the registration function works well. Thank you so much
