### ISSUE TITLE
Improve explore reports for 15m counts

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#351]
@johnvanbreda thanks for improving the download reports #345 
Can you  also improve the explore reports to reflect these reports. 

Replace: https://butterfly-monitoring.net/elastic/my-records with two reports.
1. Explore-occurrences to match the report number 3 listed in issue #345 
2. Explore-15 minute counts to match the reports number 1 and 2 listed in issue #345.  Ideally a single report for both together but separate reports for each are ok if simpler to develop

**Comment by johnvanbreda** [comment]
I assume both of these are "My records" reports - let me know if there is a requirement for All records versions.

1. I've updated the test version of elastic/my-records https://test-butterfly-monitoring.pantheonsite.io/elastic/my-records to match report number 3 from #345 - please can you check this is what you intended? In particular do you still want the other tabs, and is it correct that any occurrence which is attached to the top level sample (i.e. where the GPS wasn't available) should be excluded?
2. I've created a demo of a combination of reports 1 & 2 combined at https://test-butterfly-monitoring.pantheonsite.io/explore-15-minute-counts. This needs tweaking for display (rather than download) purposes. I suggest the following:
  * Is addition of a map useful?
  * Remove the Recorder name and Geom (GeoJSON) fields?

**Comment by DavidRoy** [comment]
@CrisSevilleja could you test this please?

**Comment by DavidRoy** [comment]
@johnvanbreda we've had a rethink on the reports and have decided that they need to be led from the sample view first.  Please can you simplify '../my-records' to a simpler version:
![ebms pic 1](https://user-images.githubusercontent.com/2699478/123795187-a6095900-d8db-11eb-9ad9-f77873172936.png)

then to view the sample occurrences, build a popup summary, e.g.
![ebms pic 2](https://user-images.githubusercontent.com/2699478/123795240-b4f00b80-d8db-11eb-8440-bb5711c473a4.png)

then a detailed sample view as:
![ebms pic 3](https://user-images.githubusercontent.com/2699478/123795260-bd484680-d8db-11eb-8aa0-81f23a28620b.png)

I will raise a separate issue about the editing pages

**Comment by DavidRoy** [comment]
@johnvanbreda - are you ok to pick this up

**Comment by johnvanbreda** [comment]
Will do.

**Comment by johnvanbreda** [comment]
@DavidRoy some progress for you at https://butterfly-monitoring.net/elastic/my-records-2. I've not implemented the quick view option yet but the details view should work.

**Comment by CrisSevilleja** [comment]
Nice progress on the 15-min count view. Some comments to suggest: 

_My 15-min counts page__ https://butterfly-monitoring.net/elastic/my-records-2
- I would add the Start and End time variables
- Allow selecting the sample (selecting the row like currently) and see it on the map above
- There are not tabs like before for species, samples, and download. That is okay but there should be a way to download the samples. 

_View details Page_
I like this page showing all the information about the sample. 
- I would include the number of individuals per species, right now you see only the total that is important, but the other numbers as well.
- Add a button to come back to My 15-min count page

I will work on some suggestions for the edition. Thank you

**Comment by CrisSevilleja** [comment]
Sorry I just see on My 15-min counts page that is possible to select the sample and see the sample route on the map, that is really great! However, you can do that when you select the empty spaces between the numbers (see the picture below). 

I would allow to select the complete row. 
Thank you for the improvement!
![image](https://user-images.githubusercontent.com/25052478/127455471-3ac024c4-e51d-49bd-9dae-5e7d639e38a5.png)

**Comment by DavidRoy** [comment]
@CrisSevilleja thanks for the feedback.  
@johnvanbreda is it possible to have a column selector (for sample attributes) as with other explore pages?  Also the download tab?

**Comment by CrisSevilleja** [comment]
Show on View details Page the comments from the sample, under or next to the map.

**Comment by johnvanbreda** [comment]
Please note I've changed the URL to https://butterfly-monitoring.net/mydata/samples, as it fixes some of the navigation issues mentioned.

@CrisSevilleja 
* Start and end time added
* Row selection now clarified in grid styling
* There is now a download button at the bottom. It's a different technology for this report, hence not a tab.
* On the details page, the counts don't show because there is no abundance data for these records. Can the system assume on these data that if there is no specific abundance information, it can be counted as a single individual? @DavidRoy to confirm.
* Rather than a back button, I've fixed the breadcrumb trail at the top by changing the page paths.
* Comments now appear in the attributes where they were supposed to be (there was a bug).

@DavidRoy 
* Download link at the bottom, though this page is not Elasticsearch as it shows empty samples, so doesn't use the tab approach.
* The column selector is implemented in Elasticsearch grids not standard ones. If and when we include empty samples in ES then we can revisit this.

**Comment by DavidRoy** [comment]
@johnvanbreda yes, each occurrence is of 1 individual in this survey type.  Do you think we should set the abundance = 1 for completeness.  I can ask Karolis to include this within the app submission if so

Makes sense that this is not an ES report so we can include empty samples

**Comment by johnvanbreda** [comment]
@DavidRoy it will be tidier if the data are explicit and we don't have survey specific rules about how to interpret them, so yes, my preference would be to set abundance=1 in this case.

**Comment by DavidRoy** [comment]
@johnvanbreda one other requirement for the samples view is to show the sample photos.  Is that possible?

**Comment by johnvanbreda** [comment]
@DavidRoy I've added sample photos. Let me know if there is anything else, otherwise can this be closed?

**Comment by DavidRoy** [comment]
@CrisSevilleja can you review and close this issue if resolved, thanks

**Comment by johnvanbreda** [comment]
@DavidRoy I've done that - it will take an hour or so to process and appear in reports.

**Comment by DavidRoy** [comment]
@CrisSevilleja can you confirm any more work needed on this page?

**Comment by CrisSevilleja** [comment]
@johnvanbreda what I meant with "add a scrolling bar of the samples at the same time you see the map." is to be able to scroll down my list of samples while I see the map. Right now if I scroll down, I can see the list of samples and the map stays on the top. A scrolling bar is already placed on https://butterfly-monitoring.net/elastic/my-records See picture below
![image](https://user-images.githubusercontent.com/25052478/132985685-bdf6f56e-5378-4880-8262-8da1f8a8c489.png)
Also, when the mouse is over the map, I would like to use the scroll-wheel of the mouse to zoom on the map. Currently, it is not possible. 

These are tiny details, so this new page can be activated when you consider. Although the edition of the records and route is still missing, issue #352  Thank you so much for these improvements

**Comment by CrisSevilleja** [comment]
@johnvanbreda thanks for the improvement on the map and on this page, now it is working well, scrolling down and the zoom. From my last records, everything looks great, species and their abundance. From old records, the abundances are still missing but at this point, it would be good to go further on the edition part. 

@DavidRoy

**Comment by johnvanbreda** [comment]
This updated copy of the page now uses the new Elasticsearch samples index, so includes samples containing no records: https://live-brc-ebms.pantheonsite.io/mydata/samples.

**Comment by CrisSevilleja** [comment]
It is not possible to search by species in the records tab of the My samples page https://butterfly-monitoring.net/mydata/samples. Could it be added @johnvanbreda? Thanks

<img width="600" alt="2021-11-11_14h18_10" src="https://user-images.githubusercontent.com/25052478/141305007-02bfe0c1-30e3-43ff-ab59-a9e2ce8e1c75.png">

**Comment by johnvanbreda** [comment]
Yes, it's because the column configuration comes from the first tab which only contains samples, so the occurrence related columns are missing their configuration. @DavidRoy this is 2-3 hours to fix, so let me know if a priority.

**Comment by DavidRoy** [comment]
Not an immediate priority I think.  I'll close this issue and raise a new one
