### ISSUE TITLE
error uploading 15-min counts on the ButterflyCount app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#367]
Hi @DavidRoy @kazlauskis We are using a lot of the app for a project in Madeira. Recently, one of the recorders, Mike Prentice trying to upload 15-min count got an error message and he is not able to upload his data (I don't understand the error). See picture below

The Indicia Warehouse User ID is 227057, his account is active and he logs in well on the app. Also, he uninstalls and installs again the app, and the error continues.
![Error-uploading data](https://user-images.githubusercontent.com/25052478/133894519-b96cfef4-71bf-412d-9764-53de34c66e1f.jpeg)
p.

Another person in Madeira had issues uploading the data, but in the end, she managed to upload it, any error with the server? Thanks for the help

**Comment by kazlauskis** [comment]
Thanks, we'll have a look at it.

**Comment by johnvanbreda** [comment]
I can't see anything related in the warehouse log. 

In the IIS access log, I can see OPTIONS or POST requests to the rest/samples end-point that matches these times (an hour before presumably due to timezone settings somewhere on the server). But no indication of anything wrong.

@BirenRathod I've had a look but can't spot the PHP error log that's being updated now - the one in the usual place hasn't been updated for a few weeks. Do you have any ideas what is happening here?
