### ISSUE TITLE
Download page for individual users - 'my downloads'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#369]
links to https://github.com/BiologicalRecordsCentre/ABLE/issues/345

need equivalent of https://butterfly-monitoring.net/downloads (currently for scheme co-ordinators), using the same download file formats and options but for individual users to download all their data in one place.

**Comment by chrisvanswaay** [comment]
I fear I am a bit lost, as this email series seems to miss context. I don't have access to BiologicalRecordsCentre/ABLE (at least: it doesn't show up in my list on github), so it's hard for me to understand these emails.

[cid:2b009ee9-9cd2-4c9e-b23d-2736c1b468d5]

Bset wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Cristina Sevilleja ***@***.***>
Verzonden: donderdag 28 oktober 2021 15:49
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Download page for individual users - 'my downloads' (#369)


Hi @johnvanbreda<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnvanbreda&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640831325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BeoNccH1FLcRyAYnFEftytpQSBSJOu2jxe%2FMGYUH%2BJM%3D&reserved=0> I downloaded from the page https://live-brc-ebms.pantheonsite.io/mydata/samples<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flive-brc-ebms.pantheonsite.io%2Fmydata%2Fsamples&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640841315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6lSNVveVA3NY4N0VGPemw%2FXCZcUnYGPw9W%2Fd6h0PdEo%3D&reserved=0> and here click the button at the bottom "Download" that generate a zip file with a CSV inside.

But I think you wanted the test for the new page My Downloads https://live-brc-ebms.pantheonsite.io/mydata/downloads<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flive-brc-ebms.pantheonsite.io%2Fmydata%2Fdownloads&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640851312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h3c7A3btZvt7nz3jt7aZ1IDT%2FDURRsZVDMwY4EUf6y0%3D&reserved=0> Sorry I didn't check that one and I see already all the options, occurrences, KML and so on. I will let you know if there is something missing. Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F369%23issuecomment-953863708&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640851312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BaAK9eD9T6%2FUYEcOVxiUXy8DmdPwiEew7pnS56SzWgQ%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFP2NIBQLL7GYY4PMO4CY3UJFPHDANCNFSM5E5C6EVA&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640861308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=akWAobjYO368rlDbhT16CRKPDLNy5qEMzF8NoeJ5f1g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640861308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B98QxAPmJ6gWhhCyFYRC6k5xWJDWrADAbPEoD6bKSCI%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7Cb6ded619944940442a9208d99a19bf69%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637710257640871300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FhDVHSGi8v6KcDimQFrlR7BiiB5FVTFjkzCm%2FIoBjSc%3D&reserved=0>.

**Comment by johnvanbreda** [comment]
@chrisvanswaay the page for downloading your own records is available at https://butterfly-monitoring.net/mydata/downloads now. This is an alternative to the previous downloads page which can be made available to all users since it is filtered to only the data input by the logged in user. Is this page OK for your needs?

**Comment by DavidRoy** [comment]
@johnvanbreda can you standardise the column names. 
1. in the sample download, rename 'Sample ID' to 'Visit Sample ID' to match the occurrences download
2. in the occurrences download, rename 'ID' to 'Occurrence ID'

**Comment by johnvanbreda** [comment]
Column renaming changes done.

**Comment by DavidRoy** [comment]
@johnvanbreda can you implement as a new menu item
My data -> My downloads

Restricted to user's own data

**Comment by CrisSevilleja** [comment]
I checked the new page My downloads https://butterfly-monitoring.net/mydata/downloads and it is working well for single users. 

For downloading transect : Doing some checks on people with one or several transects, the page allows to download well their data from transects or 15-min counts without problems. However, when a user has several transects, for example a regional coordinator has allocated 20 transects, that person doesn't register all the records for those transects, so the download of the transects doesn't include all the records for all the transects assigned. I think the page is restricted to who submitted the records and not to the transect allocation.. would be possible to resolve this? maybe a possibility is going further with the regional coordinator role and allowing those people to download all the data their coordinate in another page. 

About the download files some information need correction: 
- tracks and areas KMLs: showing 3 different dates, leave one and missing length of the route
- occurrences KMLs: missing date. thanks for including the species here
- the csv are good

Thank you!

**Comment by DavidRoy** [comment]
Thanks @CrisSevilleja.  I'll create new issues for the remaining items.

@johnvanbreda can you implement as a new menu item
My data -> My downloads

Restricted to user's own data

Then close this issue?

**Comment by johnvanbreda** [comment]
Done. I also added date to the occurrences KMLs but it will have the same issue as the tracks KML as the visibility flag in the report files is not being respected (fixing that will fix both).
