### ISSUE TITLE
The whole eBMS menu shown to all users - need to hide coord. pages

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#388]
As a supermanager I am able to see all the menu pages on the eBMS website; the normal recorders shouldn't see the pages for coordination as shown in the red square on the picture below. It is confusing showing pages normal recorders don't have available. Before the last website update, this appearance was working well.

<img width="890" alt="2021-12-01_09h56_10" src="https://user-images.githubusercontent.com/25052478/144203010-ec364bf4-a99e-4916-a530-6333a4b9915e.png">

**Comment by DavidRoy** [comment]
@BirenRathod can you fix this please, hiding these 'admin' menu items from standard users

**Comment by BirenRathod** [comment]
@DavidRoy Are these visible to admin only or any other roles to consider for?

**Comment by Irmawyn** [comment]
I am a "normal"user of the page, I cannot see the two tabs Cristina mentioned. However, there is something mixed up with the languages. My Dutch page is English.

Best wishes, Irma


----------------------------------------------------------------------------------------

Dit bericht is verzonden door / This message was sent by

Dr. Irma Wynhoff

De Vlinderstichting / Dutch Butterfly Conservation

Butterfly Conservation Europe

Postbus 506 / P.O. Box 506

NL - 6700 AM  Wageningen

Mennonietenweg 10, Wageningen

[T]  (+31) 0317 467346 / direct (+31) 0317 467320 / mob (+31) 06 44 67 46 49

[E}: ***@***.******@***.***>,

[I]: vlinderstichting.nl<http://www.vlinderstichting.nl/>  bc-europe.e<http://www.bc-europe.org/>u  facebook.com/bluesinthemarshes/<http://www.facebook.com/bluesinthemarshes/>

-----------------------------------------------------------------------------------------

Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------------------------------------------------------------------

No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.



________________________________
Van: Biren ***@***.***>
Verzonden: woensdag 1 december 2021 10:06
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] The whole eBMS menu shown to all users - need to hide coord. pages (Issue #388)


@DavidRoy<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDavidRoy&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C742c751e2da44c50c02308d9b4a9ebb0%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637739464171257294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aOpvf07zBjT02s7xcYth6EJg6UOv1K8HsAHjk0AeJCw%3D&reserved=0> Are these visible to admin only or any other roles to consider for?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F388%23issuecomment-983433410&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C742c751e2da44c50c02308d9b4a9ebb0%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637739464171267259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uJ1XJei0rlkXEFaK8yHXVqVQyhcFcOrWlKETYQ4nY3s%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK6ABCQ46J72DA6ZDSGOXCLUOXQS3ANCNFSM5JD42QTQ&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C742c751e2da44c50c02308d9b4a9ebb0%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637739464171277222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OrO43E58mHUdNnmz1ElGpI%2Fh04xfQ8fpKR51Z3%2BdkZk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C742c751e2da44c50c02308d9b4a9ebb0%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637739464171287160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=62NwU8WizY4Utl8sETDhUYB1qUXZcVLXbsZRnYHeYjo%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C742c751e2da44c50c02308d9b4a9ebb0%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637739464171287160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fpMQR5Xh%2FiIIuBwEkG6Q72J8Tx18ZjywgIEnbXMw%2F7I%3D&reserved=0>.

**Comment by BirenRathod** [comment]
@DavidRoy It has hidden now for all users except "Administrator"

**Comment by DavidRoy** [comment]
@BirenRathod 
The Scheme admin menu needs to be available to these roles:
'Super manager'
'Scheme co-ordinator'

**Comment by BirenRathod** [comment]
@DavidRoy  Done.

**Comment by DavidRoy** [comment]
@CrisSevilleja to review and close this issue if resolved.  And raise a separate one for Irma's translation problem

**Comment by CrisSevilleja** [comment]
thank you @BirenRathod now the appearance is correct.
