### ISSUE TITLE
Add stage term to single-species count survey

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#395]
to enable egg/larval counts for single-species

- add butterfly stage term to additional details page of single-species timed count 
- Or alternatively: when you choose the species for your single species 15 min count, there could be a tick box for egg/larva/adult (default on adult).

**Comment by kazlauskis** [comment]
@DavidRoy @chrisvanswaay at the moment, in the app you can select the occurrence stage (adult, pupa etc) so I understand this is about surveying single-stage occurrences only and not mixing different stages in a single survey, is that right? If you want to mix different stages then we can use this option to 'default' to a certain stage (at the moment it is Adult) and keep the per-occurrence stages but this way you wouldn't know if the user surveyed single stage species only.

We can do both options and it mostly depends where you would like this information to live - if the stage attribute should be at the top survey level then it is easier to add the attribute to the details page (the first option).

**Comment by chrisvanswaay** [comment]
Hello Karolis,
How can you change the stage? Tried to find it again, but no idea how to change it to eggs for Thecla betulae.
Could you help me out?

Best wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Karolis Kazlauskis ***@***.***>
Verzonden: maandag 17 januari 2022 10:26
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Add stage term to single-species count survey (Issue #395)


@DavidRoy<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDavidRoy&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4JTHp2xr1EbYZYh%2FSV4GV7%2FbHZXpvGTn36HZZ1XqaR4%3D&reserved=0> @chrisvanswaay<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrisvanswaay&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LGsklDtJBzkxL3arwrC585PEwiie6KuwAbtTjJi8%2FxY%3D&reserved=0> at the moment, in the app you can select the occurrence stage (adult, pupa etc) so I understand this is about surveying single-stage occurrences only and not mixing different stages in a single survey, is that right? If you want to mix different stages then we can use this option to 'default' to a certain stage (at the moment it is Adult) and keep the per-occurrence stages but this way you wouldn't know if the user surveyed single stage species only.

We can do both options and it mostly depends where you would like this information to live - if the stage attribute should be at the top survey level then it is easier to add the attribute to the details page (the first option).

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F395%23issuecomment-1014309855&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9s4kYB%2FLvFCL9TO8MPSAhJz4%2B31MHuJovtsliqjFjqY%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFP2NP2X4AQBBHQXV4YTVLUWPOFBANCNFSM5L3KYHCA&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q9gln9yCvWleGHvQvA2zmUKFdojBj%2FA0ZtBVggfCL54%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j427SLbz1pD9Xq%2BDBhJXZrvDD1VaskGHBVtwIkMv8LU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C956cf61e60ba4d21f4f308d9d99b791e%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780084043426994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8f5YWVLgx3Rx2f0bO2n6DiSjWp2ujYICuFK%2BfGE6pBw%3D&reserved=0>.

**Comment by kazlauskis** [comment]
1. 
![IMG_2245](https://user-images.githubusercontent.com/7383162/149757570-3d972abd-e81a-42b8-8c18-2fed5a25fb85.PNG)

2.
![IMG_2246](https://user-images.githubusercontent.com/7383162/149757689-8b421982-bbc0-42eb-92d3-09115be6ec0b.PNG)

3.
![IMG_2247](https://user-images.githubusercontent.com/7383162/149757669-7801a2fe-016d-40fc-9a76-c9c33e380ca7.PNG)

4.
![IMG_2245](https://user-images.githubusercontent.com/7383162/149757720-a11568f1-733b-42b6-a252-04b67b4809ee.PNG)

You can't change the stage when the count is 0 though.

**Comment by chrisvanswaay** [comment]
Ah, that helped. I always tried when the count was still 0.
Thanks,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Karolis Kazlauskis ***@***.***>
Verzonden: maandag 17 januari 2022 12:01
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Add stage term to single-species count survey (Issue #395)


  1.

[IMG_2245]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7383162%2F149757570-3d972abd-e81a-42b8-8c18-2fed5a25fb85.PNG&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZLqf0n5fjj6s1bJLcdrZ3txTTnIgE4m%2BGYGPu1GQyJM%3D&reserved=0>

  1.

[IMG_2246]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7383162%2F149757689-8b421982-bbc0-42eb-92d3-09115be6ec0b.PNG&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R774DdXFCCLY6VgghVAyKvljnHGLbb59KcPLDhMk9qs%3D&reserved=0>

  1.

[IMG_2247]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7383162%2F149757669-7801a2fe-016d-40fc-9a76-c9c33e380ca7.PNG&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fpXkWz%2BJZhGCTl3bO8lGiztZZ8Cb2R49H8LSGAb0BOo%3D&reserved=0>

  1.

[IMG_2245]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7383162%2F149757720-a11568f1-733b-42b6-a252-04b67b4809ee.PNG&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gXg8%2F4mRYHNn%2B3w1InYCHNB5n5Odnnxhz8A3fIitr34%3D&reserved=0>

You can't change the stage when the count is 0 though.

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F395%23issuecomment-1014392912&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P%2FtR9TLAVGBPw%2FtXiA78fz0ClaIfR2o%2BXCskfH8lcoY%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFP2NKBDKHHIG42NRGRJATUWPZHBANCNFSM5L3KYHCA&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yKj7zdWGf9Tp18cRIOJ%2B9%2BU5tNVioUNwO2olotuuxWI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bx0dgD8ktZWbTg%2Bf311w60k1AzL%2BvacJ4vctrQOzlrw%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C988344d73e7849bff0d508d9d9a8a8ef%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780140700748674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dCVfjGK4G5x1%2FhKNMJ9RQBcTGrQEdAkuLxgP690Oa%2FA%3D&reserved=0>.

**Comment by DavidRoy** [comment]
So the functionality exists in the app?  
@chrisvanswaay - does this give what is needed and we can close this issue?

**Comment by chrisvanswaay** [comment]
Yes, for now on, though we should think of making this option easier to find or find another way to promote the use, because after using this app since the beginning I either missed this option of forgot about it (old man...). And if I already missed it, many others also will (I think).
Best wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: David Roy (CEH) ***@***.***>
Verzonden: maandag 17 januari 2022 12:11
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Add stage term to single-species count survey (Issue #395)


So the functionality exists in the app?
@chrisvanswaay<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrisvanswaay&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C821b4d74aeba4c38194b08d9d9aa2318%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780147032151178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AwpUiQjVUhl%2BfDohEFncXYqOo%2Fxj64U08UghO4s5KLg%3D&reserved=0> - does this give what is needed and we can close this issue?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F395%23issuecomment-1014403123&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C821b4d74aeba4c38194b08d9d9aa2318%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780147032151178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lvBj5ZtwH02XcahSsxRrHfD2YaR1m0v1X1zMt6Cw6f8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFP2NN6Z4ZCBSXHIML7C6DUWP2OXANCNFSM5L3KYHCA&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C821b4d74aeba4c38194b08d9d9aa2318%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780147032151178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DI5d%2FtpXzNY3uY2M1pyS97CIZ%2BeHfO3nxZ81G6G1VlE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C821b4d74aeba4c38194b08d9d9aa2318%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780147032151178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hQIzXg7S5mrxhd8MN8QnLN1sD%2FzFRqXAgW8%2BOGYuMpM%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C821b4d74aeba4c38194b08d9d9aa2318%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637780147032151178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IJIK%2B3nRGscb76z5E1Sovemzfc1IYBQ2yi46lWzaypQ%3D&reserved=0>.
