### ISSUE TITLE
Import Sweden BMS sites

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#410]
Import transect lines as Location type = transect and transect section

For fixed point sites, create a new location type = fixed point site
Import fixed point sites (polygons) as location type = fixed point site

data to import emailed separately

**Comment by JimBacon** [comment]
The `point_sites` file contains 698 features. We have previously imported 608 features of type 'ABLE fixed point site'

Of the 608 existing points,

- 2 have been removed (2631, 2768)
- 3 have had a name alteration (198, 236, 2781)
- 1 has change location slightly (247)
- 1 has changed location significantly (2662)
- 2 which previously had the same location now have slightly different locations (2791, 2910)

There are 92 new points.

Shall I edit the existing records and add the new ones with the existing type?

The supplied sites are polygons of 50m radius. We have imported them as point locations at the centroid of the polygons.

**Comment by larspett** [comment]
I would prefer to have them as polygons since that is what they are. The centroid midpoint can always be derived (or kept as a separate table field if needed). I would suggest removing all entries present in the db and running a full resupply with the polygon definitions. Is the radius 50 m? I should be 25 m (a diameter of 50 m)

**Comment by JimBacon** [comment]
Sorry, yes, I meant 50m diameter. I was unsure if they would still look circular when projected in EPSG:3857, which is what I think the website will use, but it looks okay in QGIS. I will try what you suggest, thanks.

**Comment by larspett** [comment]
Great! The shape of them will probably change when we allow volunteers to see them and (possibly) edit them, that’s why we have them as polygons with quite a lot of segments. Then a user should be able to adapt it to their garden etc if they want to (and we make the shape editable)

**Comment by larspett** [comment]
Could you send me the id:s of the 33 ones? The Turning Tors one below is a test site and shouldn’t really be in the selected sites. Might make sense to double-check the others too

**Comment by JimBacon** [comment]
565 out of 698 have 33 vertices. That is a lot of checking!
IDs in the attached text file.
[point_sites_33_vertices.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8563716/point_sites_33_vertices.csv)

**Comment by larspett** [comment]
Ah that was a bit surprising, then absolutely yes, please do simplify them to 33. All should be circular, so the two odd ones you sent would be good to double-check. Do you find other non-circular ones? If so, please send the ids. Eventually we will be resupplying updated shapes when necessary (or upload to the site directly.)

**Comment by JimBacon** [comment]
Okay. That's good. They are all circular. The two screenshots were my attempt to show editing in progress and how difficult it is to alter the polygon when there are 361 vertices compared to 33.

**Comment by JimBacon** [comment]
For reference, I have done the following to import the transects.

1. Opened the KML file in QGIS and added additional fields consistent with the existing naming convention for eBMS:
    1. transect code: EBMS:Sweden:<geo_sit_si>
    2. section code: S<geo_seg__1>
    3. section name: <geo_sit_na> - S<geo_sit_si>
2. Added further fields in QGIS to 
     1. count the number of sections in a transect
     2. calculate the length of a transect
2. Used Vector > Analysis Tools > List Unique Values to export a list of transect names, transect codes, transect lengths, and  section counts.
6. Added extra columns to the list of transects having 
    1. a dummy centroid value of 0, 0 for all transects.
    2. the country code for Sweden (216172)
10. Edited https://warehouse1.indicia.org.uk/index.php/location/edit/242505 and changed its code to `EBMS:Sweden:6a` appending the letter 'a' to avoid conflict with the import data.
11. Imported the list of transects as a CSV file, selecting
    1. Website: EBMS
    2. Spatial Ref. System: Latitude and Longitude (WGS84)
    3. Location Type: Transect
    5. Map columns to the Name, Code, Centroid sref, No. of sections, Overall length, Country fields
 12. Exported transect layer from QGIS as SHP file format.
 13. Zipped the .SHP and the .DBF files created by the export together.
 14. Imported the transect sections shape file via the Indicia warehouse website with
     1. Shape file geometries are: location boundaries
     2.  Associate the locations with a parent location?: True
     3. Which field is used to link to the parent location?: Location code
     4. SRID used in shapefile: EPSG:4326
     5. Set imported locations type to: Transect Sections
     6. Default website to attach any new locations to: EBMS
     7. Name?: section name
     8. Parent Code?: transect code
     9. Code?: section code
1.  Updated the centroid information of the transects with the query
 ```
WITH centroids AS (
	SELECT
	p.id, 
	ST_Centroid(ST_Collect(array_agg(l.boundary_geom))) geom,
	ST_Y(ST_Transform(ST_Centroid(ST_Collect(array_agg(l.boundary_geom))), 4326)) lat,
	ST_X(ST_Transform(ST_Centroid(ST_Collect(array_agg(l.boundary_geom))), 4326)) lon
	FROM locations l
	JOIN locations p ON p.id = l.parent_id AND p.deleted = false
	WHERE l.deleted = false
	AND p.code like 'EBMS:Sweden:%'
	AND p.created_on > '2022-04-27'
	GROUP BY p.id
)
UPDATE locations l
SET centroid_sref = concat(round(lat::numeric, 5), 'N ', round(lon::numeric, 5), 'E'),
centroid_geom = geom,
updated_on = now(),
updated_by_id = 2
FROM centroids c
WHERE l.id = c.id
```
11.  Created the section length attributes with the query
```
WITH lengths AS (
    SELECT
	l.id,
	round(ST_Length(ST_Transform(l.boundary_geom, 3006))) sctn_len
	FROM locations l
	JOIN locations p ON p.id = l.parent_id AND p.deleted = false
	WHERE l.deleted = false
	AND p.code like 'EBMS:Sweden:%'
	AND p.created_on > '2022-04-27'
	)
INSERT INTO location_attribute_values
(location_id, location_attribute_id, int_value, created_on, updated_on, created_by_id, updated_by_id)
SELECT id, 220, sctn_len, now(), now(), 2, 2 FROM lengths
```

**Comment by JimBacon** [comment]
Hi @larspett 

Yes, they are visible.

The following 6 transects were already present in eBMS.
Billebjer and Rökepipan are now duplicated. You probably want to delete something to avoid confusion.
Note, I also changed the code for 'test transect 1' so it did not conflict with one of the imported transects.

![image](https://user-images.githubusercontent.com/2545390/165712439-6b77ae49-573e-4605-bffd-d94217d18046.png)

**Comment by larspett** [comment]
Great, I will delete most of them. How much of the metadata from us remains?

28 apr. 2022 kl. 10:45 skrev JimBacon ***@***.***>:

﻿

Hi @larspett<https://github.com/larspett>

Yes, they are visible.

The following 6 transects were already present in eBMS.
Billebjer and Rökepipan are now duplicated. You probably want to delete something to avoid confusion.
Note, I also changed the code for 'test transect 1' so it did not conflict with one of the imported transects.

[image]<https://user-images.githubusercontent.com/2545390/165712439-6b77ae49-573e-4605-bffd-d94217d18046.png>

**Comment by JimBacon** [comment]
The 6 existing transects are unchanged so if you have added metadata to them you may prefer to delete the newly imported versions. One difference is that you have used sequential numbers (1-6) in the codes of the transects you have added while I used your existing transect IDs because I thought that might be more useful. I am now wondering if that was a mistake. If the system has allocated those codes and it expects a sequence, it may get in a muddle at some point in the future.

**Comment by JimBacon** [comment]
Just checked the way codes are created and the number is always one greater than the previous maximum so I don't think I have created any problem there.

**Comment by larspett** [comment]
No the sit_uid that came with those sites (rather, the uid was called geo_sit_siteid) is what we would like to keep. Those 6 old cases are just test sites, one of them might have been used for real but the others are just dummies.

I would very much like to keep those UIDs but am unsure if those are unique in Indicia or just metadata so that the unique id:s are not visible to the ordinary user? I guess the latter is the case, right?

In the future, we would probably like to resupply some sites when needed and also supply new ones. I would be good if we could do that programmatically either via an API or by us making necessary parts of that table visible externally so that you could harvest. Our site Id:s (sit_uid) should be preserved as far as possible.

I suppose we would also need a procedure to handle sites created in Indicia but that is something for later

From: JimBacon ***@***.***>
Reply to: BiologicalRecordsCentre/ABLE ***@***.***>
Date: Thursday, 28 April 2022 at 11:09
To: BiologicalRecordsCentre/ABLE ***@***.***>
Cc: Lars Pettersson ***@***.***>, Mention ***@***.***>
Subject: Re: [BiologicalRecordsCentre/ABLE] Import Sweden BMS sites (Issue #410)


The 6 existing transects are unchanged so if you have added metadata to them you may prefer to delete the newly imported versions. One difference is that you have used sequential numbers (1-6) in the codes of the transects you have added while I used your existing transect IDs because I thought that might be more useful. I am now wondering if that was a mistake. If the system has allocated those codes and it expects a sequence, it may get in a muddle at some point in the future.

**Comment by larspett** [comment]
The important thing is that the unique codes are preserved (sit_uid a.k.a. geo_sit_siteid )

From: JimBacon ***@***.***>
Reply to: BiologicalRecordsCentre/ABLE ***@***.***>
Date: Thursday, 28 April 2022 at 11:23
To: BiologicalRecordsCentre/ABLE ***@***.***>
Cc: Lars Pettersson ***@***.***>, Mention ***@***.***>
Subject: Re: [BiologicalRecordsCentre/ABLE] Import Sweden BMS sites (Issue #410)


Just checked the way codes are created and the number is always one greater than the previous maximum so I don't think I have created any problem there.

**Comment by JimBacon** [comment]
Every location has a unique ID in our database, which the user can occasionally see.
The code field, in which I have kept your site ID, is metadata as far as the database is concerned. 
However, the website uses the code field and expects it to have a pattern and be unique within the context of the EBMS website (our database serves many websites).

I think everything is good and we can close this issue.

The screenshot below is from the EBMS website to illustrate this.

![image](https://user-images.githubusercontent.com/2545390/165726523-7ba31dcb-4ecd-4077-a54b-9f316b1f9ea4.png)

**Comment by larspett** [comment]
Yes looks excellent. Fine with me to close it

28 apr. 2022 kl. 12:05 skrev JimBacon ***@***.***>:

﻿

Every location has a unique ID in our database, which the user can occasionally see.
The code field, in which I have kept your site ID, is metadata as far as the database is concerned.
However, the website uses the code field and expects it to have a pattern and be unique within the context of the EBMS website (our database serves many websites).

I think everything is good and we can close this issue.

The screenshot below is from the EBMS website to illustrate this.

[image]<https://user-images.githubusercontent.com/2545390/165726523-7ba31dcb-4ecd-4077-a54b-9f316b1f9ea4.png>
