### ISSUE TITLE
Verification page: not allowing editing other taxa apart from butterflies

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#457]
On the verification page of ebms https://butterfly-monitoring.net/verification, it is not possible to edit a record adding a moth or dragonfly species. The searching bar is only completing for butterfly species. 

One example for a Lithuanian verifier with the permission to edit records for butterflies, dragonflies and moths not able to include the genus Xanthorhoe (moth), only butterfly species appearing (Nymphalis xanthomelas).
![image](https://user-images.githubusercontent.com/25052478/177728854-05e20486-5387-4bf4-9de7-bbc38df4d3e6.png)

I tried with my account, I am a verifier for all records and I cannot add moth species (e.g. Zygaena genus)
![2022-07-07_10h28_34](https://user-images.githubusercontent.com/25052478/177728878-79830f31-37e1-4db0-8731-bb79124e79b4.png)
![2022-07-07_10h28_20](https://user-images.githubusercontent.com/25052478/177728881-2c1aa5df-5660-4934-987a-6bdd5cb26088.png)

Could someone have a look at this? @DavidRoy @Gary-van-Breda or @johnvanbreda Thank you

**Comment by DavidRoy** [comment]
@JimBacon can you add this to your (long!) list of tasks

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

I think you are reporting two issues here, although they may have similar symptoms.

1. On the Verification page, https://butterfly-monitoring.net/verification, when attempting to redetermine a record, a Lithuanian verifier was unable to select a moth species.

This may relate to permissions of the verifier since it is possible for you to do this. Can you email me their name so that I can try masquerading as them? Screenshot when masquerading as you.
![image](https://user-images.githubusercontent.com/2545390/178302435-07142a73-c25d-46d8-bbc7-08dd86e9a614.png)

2. On the Edit a Record page, https://butterfly-monitoring.net/edit-generic-record, you cannot edit a record and select a moth species. 

That is expected behaviour, based upon the configuration, see screenshot.
![image](https://user-images.githubusercontent.com/2545390/178305538-1c34d1c4-ca91-48b5-86e7-ca2e2c4ff10f.png)
The form allows a second species list to be added, such as the moth list, but not a third like dragonflies.

I don't see a form on the website where a person might enter a dragonfly record. Has the app development overtaken the website development?

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

I've looked in to the issue of re-determining species on the verification page. The situation is this:

With the 'Search all speci' option not ticked

- A butterfly can be changed to another butterfly in the EBMS Butterflies list (ID = 251)
- A moth can be changed to another moth in the EBMS Moths list (ID = 260)
- A dragonfly can be changed to another dragonfly in the EBMS Dragonflies list (ID = 265)

You can not change an observation from one taxonomic group to another.

The 'Search all speci' checkbox has the following comment 

> This record was identified against a restricted list of taxa. Check this box if you want to redetermine to a taxon selected from the unrestricted full list available.

If you tick the box it causes the search to use the list with ID = 254, entitled **EBMS Butterflies - unused**.  This is clearly something old that is no longer correct.

What is the desired behaviour? 

- Is it necessary to re-determine across species groups? This might create a lot of work either restructuring all the species lists as children of a master list or keeping two copies of the species list which is a maintenance headache. 
- Is it okay to only re-determine within a species group? In that case it might need some small code changes (thought not necessarily quick) to remove the checkbox.

**Comment by CrisSevilleja** [comment]
Hi @JimBacon 

Thanks for explaining everything. Regarding the desired behaviour, I think the second option makes sense. I don't think or it shouldn't be that we need to redetermine species across species groups, we expected to redetermine within a species group. @DavidRoy do you agree on this?

**Comment by DavidRoy** [comment]
@JimBacon happy to discuss options around this. Given the related issue #584, we may end up requiring editing/redetermining names across species lists and therefore need a European master list with child lists - hard to see us avoiding this?

**Comment by JimBacon** [comment]
To summarise the above discussion:

- Redetermination currently supports taxonomic changes within a species group but not between groups (because we have created a different species list for each group). This is adequate at present.
- The "Search all species" checkbox on the redetermination dialog does not perform as advertised because there is not a full list of all the taxa we record against. See screenshot below.
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/3709852d-e3a5-47eb-ac41-146d8bdfa3b9)
- The proposed resolution is to remove the option to select from a master list, since there isn't one.

Investigating, I find:

- The `client_helpers/ElasticsearchReportHelper.php::verificationButtons()` function requires a master list to be specified.
- It is set in https://butterfly-monitoring.net/admin/config/iform/settings to 254 ("EBMS Butterflies - no longer used"). 
- The `media/js/indicia.datacomponents/jquery.idc.verificationButtons.js` code updates the form to use the same taxon list as the record was made against. 
- If this is not the same as the master list then the "Search all species" checkbox is displayed.
- This area of code will need modifying to achieve the objective.

**Comment by JimBacon** [comment]
A fix has now been deployed for this issue.
Note, there is no change in the redetermination function. All that has happened is that the checkbox to select "the unrestricted full list" has been hidden because no such list exists for EBMS. You can redetermine within a species group but not from one species group to another.

@CrisSevilleja please review and close if satisfactory.

**Comment by CrisSevilleja** [comment]
@JimBacon thanks for fixing this. The verification page allows to redetermine for moths and dragonflies species. 

One small detail is that the loading time is a bit long. When typing the species name, the suggested list takes a bit to be loaded, a few seconds. If that can be checked the best, but not a high priority. I tried with Libellula or Sympetrum genus of dragonflies.

For now, I close this issue.
