### ISSUE TITLE
Migrate eBMS from Warehouse 2 to Warehouse 1

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#47]
New issue for this task due later in 2019.  Discussion and script is in #14

**Comment by DavidRoy** [comment]
@johnvanbreda are you able to take this on as it makes the mobile app work simpler
Liaise with @Gary-van-Breda for timing and to manage disruption to existing site
Should we test on http://test-butterfly-monitoring.pantheonsite.io before pushing to live?

**Comment by johnvanbreda** [comment]
Ok, I'd definitely recommend that we run this onto the dev server first, then point the test site at the dev server to check it worked, before doing anything with the live site. We can then document the steps required on the site to switch to warehouse 1 since presumably there will be references to things like attribute IDs that will change. This will also give us an idea as to how long any down time will need to be.

@BirenRathod I think it would be best if we started with a fresh backup of the warehouse1 database restored onto the dev server. Do we need to check if any of the developers would be impacted by this? Can you arrange this for me please.

**Comment by BirenRathod** [comment]
The only other person I could think of is Andy. I will find out from him and let you know.

**Comment by BirenRathod** [comment]
& of course Rich Burkmar.

**Comment by BirenRathod** [comment]
@johnvanbreda , @DavidRoy , @burkmarr , @kitenetter , @kazlauskis , @Gary-van-Breda 

Just to let you know that Dev warehouse has now been upgraded with latest live data.

**Comment by DavidRoy** [comment]
@johnvanbreda - are we ready for the migration so @kazlauskis can link the ABLE app directly to warehouse1 from the outset

**Comment by johnvanbreda** [comment]
@DavidRoy I'll make this my priority today.

**Comment by kazlauskis** [comment]
@johnvanbreda I am ready to link the app to the live ebms site, the sooner the site is connected to the warehouse1 the better. Thanks!

**Comment by johnvanbreda** [comment]
@Gary-van-Breda @DavidRoy does the current EBMS site use the indexed layer of locations (i.e. countries) in earnest yet? Currently the countries layer on warehouse1 is incomplete compared to warehouse2 so I'd need to update it if required. 

Also on this note it appears that records entered since 24/01/2019 are not being indexed because the spatial index builder's config file is missing, but were indexed before that date. So presumably the config file was lost during a server move or similar. Which makes me think that keeping the current spatial indexing during the migration is not very important?

**Comment by Gary-van-Breda** [comment]
At the moment there are only 6 schemes, so we are currently only interested in those 6 countries. @DavidRoy will have a better idea of any that are soon to join.

- Austria BMS
- Cyprus BMS
- Hungary BMS
- Italy BMS
- Luxembourg BMS
- Portugal BMS

**Comment by DavidRoy** [comment]
These are the current active schemes, but the system should enable any new country in Europe (and ideally the whole world) to be activated.  

We are exploring the potential to extend to South Africa for example.

Therefore, we should use this opportunity to complete the country spatial layer on Warehouse1

**Comment by johnvanbreda** [comment]
Ok, but as the data currently on warehouse2 are not properly spatially indexed, I'd caution against "scope creep" within this task and raise a separate issue to cover updating the countries layer on warehouse1 to cover World countries. Is that OK?

I've now done a trial import of the data from warehouse2 (website ID 2) to the dev server (website ID 118). I've done a fairly thorough test with diff check on a sample query and fixed a few glitches in the process. @Gary-van-Breda are you OK to update the Pantheon test site to point to the dev warehouse with website ID 118? Here are the mappings for various IDs that I think you might need, let me know if there are any more:
```
Surveys:
2	->	560
3	->	561

Sample attributes:
21	->	1416
22	->	1417
23	->	1418
24	->	1419
28	->	1423
29	->	1424
25	->	1420
26	->	1421
27	->	1422
30	->	1425

Occurrence attributes:
3	->	784

Taxon lists:
1	->	259
3	->	260
```

Plus a few notes for myself for when I do the live run:

> Changes required:
> 	• Modify Export script to skip the list called ABLE butterflies.
> Mappings:
> 	• For websites
> 	update import.websites set id=118 where title='EBMS';
> 	• For termlists:
> 	update import.termlists set id=4, new=false where title='Sample methods';
> 	update import.termlists set id=5, new=false where title='Location types';
> 	update import.termlists set id=92, new=false where title='UKBMS Transect width (m)';
> 	update import.termlists set id=150, new=false where title='UKBMS Wind Speed';
> 	update import.termlists set id=151, new=false where title='UKBMS Wind directions';
> 	• For taxon groups
> update import.taxon_groups set id=104 where title='Butterflies';

**Comment by kazlauskis** [comment]
When do you guys think the warehouse1 would be ready for us to link to the live site?

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you switch onto this as a priority, above the work on micro-sites.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda 
It looks like the attribute "block" configuration has not been copied across to devwarehouse. In this case its only apparent for the location attributes. Locations themselves are good, and the attributes themselves look OK as well.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I've fixed that and applied it to the devwarehouse. Can you check it looks OK please,, if so we then need to plan the down-time. This will involve:
1. Take the EBMS data entry site offline.
2. I'll then take a new snapshot of the data out of warehouse2.
3. I'll then import the snapshot onto warehouse1.
4. I'll provide the mappings as before (which will be slightly different as the warehouse has changed since the backup).
5. Gary to update the EBMS live data entry site with new IDs.

For my part we should allow about an hour but I hope that is an over-estimate as long as it goes smoothly.

Do we need to get @DavidRoy to test the current dev site to check it?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda 
I've done a brief check of other stuff whilst I was switching the forms over:
There now seems to the 2 "Transect" and 2 "Transect section" location types in the location_type termlist: this needs to be sorted as some of the forms look up the location type id from the text value.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @johnvanbreda I'm happy to do some testing

via https://test-butterfly-monitoring.pantheonsite.io?

**Comment by Gary-van-Breda** [comment]
@DavidRoy : there is no point until the location type terms are sorted, as the forms can't link to the locations.

**Comment by johnvanbreda** [comment]
I've implemented a quick fix via the following:
```sql
update locations set location_type_id=777 where location_type_id=15235;
update location_attributes_websites set restrict_to_location_type_id=777 where restrict_to_location_type_id=15235;
delete from cache_termlists_terms where id=15235;
delete from termlists_terms where id=15235;
update locations set location_type_id=778 where location_type_id=15236;
update location_attributes_websites set restrict_to_location_type_id=778 where restrict_to_location_type_id=15236;
delete from cache_termlists_terms where id=15236;
delete from termlists_terms where id=15236;
```

I'm also about to commit a script fix.

**Comment by johnvanbreda** [comment]
@DavidRoy @Gary-van-Breda just leaving a note here to make sure you are aware I think it is ready to test at least from the data perspective.

**Comment by DavidRoy** [comment]
I started some testing by comparing the live and test sites, but I think @Gary-van-Breda need to do some configuration of Indicia forms before I do this?

**Comment by DavidRoy** [comment]
@Gary-van-Breda are you able to progress this issue so we can complete work on the mobile app

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : Can you look at the survey specific bit of the location attribute allocation please? Rather than being allocated to the Transect or Transect Section location types, they seem to be assigned to "England" or "Scotland" ?!

**Comment by Gary-van-Breda** [comment]
Issue also affects the Sample attribute values, where the attribute that should be allocation to a "Transect section" sample method is allocated to "United Kingdon" (the "Transect" looks ok in this case)

All the sample attributes on the "EBMS Timed Count Live" survey suffer a similar problem, though they point to different sample methods, and have ended up with sample methods that are counties.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I've fixed the problems in location and sample attributes.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : are the cache tables (for samples and occurrences) being rebuilt? When I look at the "My sites" page it usually gives a count of the samples and number of species (gleaned from cache_occurrences_functional), but I'm just seeing zeros. (Looks like there are some errors on the work queue on the dev warehouse - not sure if this is related). I think affects some of the other pages' reporting values as well, like Mapping

We also need to translate the "Country" location attribute value - this points to a location_id, a bit like a "parent". It doesn't look like the "Country"s have been loaded into the devwarehouse. This is breaking the "National Walks".

How do we translate the Indicia Warehouse ID of all the Drupal users? This is meaning the "My Walks" isn't working.

I have switched on the Summariser, and will need that to finish before I can check the Annual Summary results, and Year plot.
We'll also have to change the country code for each scheme, though as they are so few that can be done manually.

**Comment by johnvanbreda** [comment]
Several things going on here:
1) Scheduled tasks not completing because the server fails to send out emails. I've commented out the bit of code which tries to send mails so they are now running (meaning the summariser should start running).
2) Also although the script imported species OK, it didn't trigger an update of cache_taxa_taxon_lists. I've fixed the scripts and applied the change to the dev warehouse data, though the scheduled tasks need to catch up before this will actually take effect.
3) The knock-on of 2 is that the cache_occurrences_* tables weren't populated. I've added work_queue tasks to fix this once it all catches up.

Tasks for me to do still:
1) Copy over the countries referred to in location_attribute_values
2) Map the Country location_attribute_values int_values accordingly.

The mappings for users will be available in the import.users table (there is an old_id field) though the current values are wrong because I ran the import again as part of the testing. A sensible approach might be to simply delete the contents of the indicia_user_id field on the Drupal site for all users, then when they log in next time it should re-link them based on email address.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda can you confirm - do we need the entire countries list, only those which have some links in location_attribute_values, or only the European ones?

@DavidRoy the plan is to create a new "ABLE Countries" layer on warehouse1 which will contain the list determined by the question above. This will be a different layer to the partial countries layer currently in use on warehouse 1. The ABLE countries layer will be based on the ISO list (at least I assume that's what was uploaded) whereas the current warehouse1 list is less "pure" but more practical for recording use in the UK. I've noted the following differences:

1) The ABLE list has the United Kingdom as a location. This polygon includes the Isle of Man and the Channel Islands even though they are not technically part of the UK, but Crown Dependencies of it. In fact, as far as I can work it out, the Channel Islands "borrow" the GB country code even though it's wrong! The Warehouse1 countries list separates out England, Northern Ireland, Scotland, Wales, Isle of Man, Bailwick of Jersey, Bailwick of Guernsey (so the Crown Dependencies are considered as separate countries). 

We might want to consider merging these layers into a single master countries layer as previously discussed but when we do this we'll need to consider the above issues.

I just wanted to make a note of the above so we don't forget to tackle these complexities at some point.

**Comment by DavidRoy** [comment]
Thanks.  Ideally we follow the NUTS hierarchy for ABLE.  If we start from that basis we can adjust for geographic oddities/inconsistencies as they arise.

**Comment by johnvanbreda** [comment]
Since this overlaps with #23 I've added the Eurostat Countries layer as a separate layer, plus NUTS level 1. The existing NUTS level 2 layer has been linked to level 1 via parent_id and level 1 to the Countries layer and I've enabled a new feature so that parents of the NUTS 2 layer are automatically included in spatial indexing without actually needing to do a spatial query (so there is no overhead on scheduled tasks).

So - should the location_attribute_values be linked to the Eurostat Countries layer, or NUTS level 1? @Gary-van-Breda as these are new layers, presumably we will want to regenerate the links in location attribute values using a spatial query. Do you have any concerns about doing this?

**Comment by Gary-van-Breda** [comment]
Can I clarify terminology? what do you mean by "layer"? Is it something served by the geoserver, and/or a collection of locations sharing the same location_type_id in the database?

**Comment by johnvanbreda** [comment]
It is a collection of locations sharing the same location_type_id.
No use of GeoServer in this instance.

**Comment by Gary-van-Breda** [comment]
In response to @johnvanbreda query above : for the purposes of this testing using dev warehouse, we only "need" the countries that are in the attribute values: it depends a bit on how representative of the deployment onto Live we want this whole process to be.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I assume it is OK if the locations get relinked to the new countries layer, rather than copying over the old one (or part of)?

**Comment by Gary-van-Breda** [comment]
Yes thats fine: I'll need to know the location_type_id for them, but as long as its consistent I'd don't care.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda on the dev server, the new countries layer is ID 15520. I've mapped across the location attribute values now so I think all the tasks I needed to do are done.

**Comment by Gary-van-Breda** [comment]
I have completed the forms configuration on the test system: they all look OK now apart from:

- There are still >10000 jobs on the warehouse job queue, some of which I assume are cache creation: this leads to a problem on My sites (which is still showing incorrect visit/species summary data for the locations) and Mapping.
- All the parent samples have been loaded with a parent_id = 1 (@johnvanbreda they should be null - is this a script issue?): this breaks the reports etc which look for parent_id=null (My walks and National walks)

I have also reset the country/scheme values for all the users, and set the Indicia warehouse ID value for the admin user only.
As a note - one of the users on the Live site has a country/scheme "Yugoslav Republic (Serbia and Montenegro)" which is not in the "Countries 2016" list.
For the Transect Allocations on the test system: there are differences in the CMS User IDs between Live and Test, so there are some inconsistencies as the Test Drupal site is looking at a Live based warehouse.

**Comment by Gary-van-Breda** [comment]
I've reset all the Indicia warehouse IDs for the Drupal users on test, apart from "David Roy" and "karolis@kazlauskis.com" - both these have possible multiple users.
I think that's me completed on this.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda thanks. I think the above issues are minor enough that we can now plan the migration. @DavidRoy how much notice do we need to give the users? Gary - when would be a good time for you?

**Comment by Gary-van-Breda** [comment]
I'm flexible: OK anytime in the next month(!)

**Comment by johnvanbreda** [comment]
Thanks. Ok, @DavidRoy when is a good time to do the migration? I'd prefer to avoid 2nd and 3rd July myself.

**Comment by DavidRoy** [comment]
At any time, with the drupal site put in maintenance mode.  As soon as possible ideally. Thanks

**Comment by johnvanbreda** [comment]
Ok, Gary, first thing Monday then?

**Comment by Gary-van-Breda** [comment]
Yes - good for me.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda or @BirenRathod please can you send me the admin account details I'll need in order to set the site into maintenance mode when I start doing the migration. Thanks.

**Comment by DavidRoy** [comment]
I'll send over the details

**Comment by johnvanbreda** [comment]
@DavidRoy thanks. Will start the process shortly.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda all done. Here are the ID mappings:

```
Surveys
2 -> 562
3 -> 563

Sample attributes
21 -> 1384
22 -> 1385
23 -> 1386
24 -> 1387
25 -> 1388
26 -> 1389
27 -> 1390
28 -> 1391
29 -> 1392
30 -> 1393

Occurrence attributes
3 -> 780

Location attributes
1 -> 216
2 -> 217
3 -> 218
4 -> 219
5 -> 220
6 -> 221
7 -> 222
8 -> 223
9 -> 224
10 -> 225
11 -> 226
12 -> 227
13 -> 228
14 -> 229
15 -> 230
16 -> 231
17 -> 232
18 -> 233
19 -> 234
20 -> 235
21 -> 236

Taxon lists
1 -> 254
3 -> 255
```

**Comment by Gary-van-Breda** [comment]
OK - I've :

- changed the Indicia configuration on the Drupal site to point to the warehouse1,
- Changed the country/scheme pointer to point to the new location type
- Updated all the forms to use the new attributes/configuration
- Updated the "My Data" block,
- Updated all the users to reset the country/scheme and the warehouse ID

I've left it in maintenance mode because there is a bug in the dis-ambiguation code when multiple warehouse users can be identified for the Drupal user: this crashes and has prevented me resetting the warehouse ID for admin, "David Roy", "Mike Prentice", "karolis@kazlauskis.com": do we want to go live as it is?

**Comment by Gary-van-Breda** [comment]
As a note, because I can't get access into the database on the pantheon site, I can't clear all the values for the warehouse IDs directly, so have had to use the front end.

**Comment by johnvanbreda** [comment]
Thanks Gary. As per our conversation just now I’ve disambiguated the 3 user IDs mentioned below.

John

**Comment by Gary-van-Breda** [comment]
Site now out of maintenance mode: I think that's it.

**Comment by DavidRoy** [comment]
Closing as I think the migration is complete
