### ISSUE TITLE
Fix Bulgaria BMS page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#498]
The current Bulgaria BMS page https://butterfly-monitoring.net/bulgarian-bms is not correct and brings you to the home page of eBMS. 

I know there is a way of creating a new page for scheme pages but I don't know how to do it exactly. Please remove or fix this page that is not working at the moment. At the moment, I cannot place information of the Bulgaria BMS. Thanks

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

The issue here is that the page exists but with url https://butterfly-monitoring.net/bulgaria-bms (bulgaria not bulgaria**n**)

I have corrected the menu configuration so that it points to the correct url. If you see any other links which are wrong then please fix them, if you can, or let me know.

There is inconsistency in the naming used which makes it more difficult to get the names/urls correct. For example Austria becomes austrian-bms but Spain becomes spain-bms rather than spanish-bms. I don't propose changing any of the urls as it might break links that already exist.

**Comment by CrisSevilleja** [comment]
thank you for correcting this. Indeed there is inconsistency in the naming...
