### ISSUE TITLE
Add ability to edit moth records

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#506]
Reported by @Helder-Cardos
On the website, under my Records, when editing a sample it does not allow to add moths species, only butterflies, from the drop-down list

**Comment by CrisSevilleja** [comment]
I don't know if this is the correct issue, but moth records cannot be edited on a visit details https://butterfly-monitoring.net/enter-moth-trap-records?sample_id=18341725 on the visits under My moth trap samples page https://butterfly-monitoring.net/my-moth-trap-samples

![no_edition_moths](https://user-images.githubusercontent.com/25052478/212927479-097a8a94-7e47-49af-a19b-47dd2a9366bc.png)

At the moment you can edit the number of individuals but not the species. This is annoying for the revisions done afterward.

**Comment by johnvanbreda** [comment]
@JimBacon The edit icons being missing (the last comment) are because of the species checklist option `@rowInclusionCheck=checkbox` interacting with this line of code: https://github.com/Indicia-Team/client_helpers/blob/master/data_entry_helper.php#L3673. 

Do you know why this option is needed? It may be that the logic in the code needs a rethink.

When editing a sample (the first comment) I was able to select species from list 260 which are the moths, so I may need further information to understand this one.

**Comment by Helder-Cardos** [comment]
@johnvanbreda . 

From what I realized it's possible to edit moth records in 2 ways: 1. Editing a moth session under "My Records" and through "My moth trap samples", like @CrisSevilleja mentioned.  Unlike CrisSevilleja I can edit through "My moth trap Samples", but under "My Records" the moth list does not show, just butterflies. 

Apparently, I´m the only one having this issue, because some of my colleagues here can edit, also, If I press the button "Edit Sample details" it does not go to edit page, but just goes to project mainpage. To edit I have to use "Quick View". 

![editing](https://user-images.githubusercontent.com/120488162/213431244-ee19e161-5553-42e0-8178-a224e95a66fc.png)

**Comment by JimBacon** [comment]
Hi @johnvanbreda 

It has been created as a checklist-type recording form, with the option to add extra species not in the checklist. Above the data entry grid is a select control to pick the checklist to use. This prepopulates the form dynamically. There is a javascript file, `sites/default/files/indicia/js/node.146.js`, which hides the presence checkbox and sets it automatically according to values entered in the quantity inside and outside columns.

Maybe it would be better to implement this by doing away with the checkbox but delete rows with no quantity at the time of submission.

**Comment by Helder-Cardos** [comment]
Just to give more information on the issue about editing moth samples. 

I´ve found that if I have several samples, like the example I posted before, if I press edit on the first moth session it will redirect to the editing page, but if I press to edit any of the following moth session it will direct to the main ebms page, with this address: **https://butterfly-monitoring.net/undefined?sample_id=21060135**

**Comment by Helder-Cardos** [comment]
The issue of not being able to edit moth record species is creating some problems among participants, any chance of looking into this in the near future? 

Thank you very much.

**Comment by chrisvanswaay** [comment]
This issue also applies to dragonflies and bumblebees. It slowly starts to not only create problems for recorders, it also starts to introduce real mistakes in the datasets. I guess we all agree the data should be good. I think this should now be promoted to one of the more important issues @DavidRoy

**Comment by CrisSevilleja** [comment]
@Helder-Cardos do you continue with this issue? 

Checking the moth entering data on the website, I realised this issue is happening when selecting "View sample detail" on My samples page, however, the link to edit the sample is working when selecting "Edit sample details"

I don't have moth trap samples, but masqueraded as the user ID289556, I saw those issues on several surveys, some as example:

- https://butterfly-monitoring.net/enter-moth-trap-records?sample_id=25933246
- https://butterfly-monitoring.net/mydata/samples/edit?sample_id=25311496 
The error appearing shows "The occurrence attribute 912 requested for the grid is not linked with the survey."
![image](https://github.com/user-attachments/assets/cf1a0576-a594-4ba4-a9ca-314d2d30dd87)

@DavidRoy and @JimBacon I think it is important to solve this, specially the inability to edit submitted species already mentioned on this issue https://github.com/BiologicalRecordsCentre/ABLE/issues/537

**Comment by JimBacon** [comment]
This issue seems to cover multiple problems.

The one in the above comment is caused by the app submitting records without a value for sample.input_form so the website attempts to edit the record using the wrong form. I will raise a separate issue for this.

**Comment by JimBacon** [comment]
I have raised https://github.com/BiologicalRecordsCentre/ABLE/issues/730 to cover the above.

The workaround for editing records is to use the "Edit Sample Details" button on the grid in the My Data > My Samples page.

[Developer note: The edit link works because the normal function is overridden in node.136.js]

**Comment by JimBacon** [comment]
In addition, I have run the following database update so all existing moth records can be edited by both routes. New records from the app will continue to have a problem.

```sql
with sample_updates as (
 update samples
 set input_form = 'enter-moth-trap-records', updated_by_id = 2, updated_on = now()
 where survey_id = 681
 and input_form is null
 returning id
)
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, null, 100, 2, now()
from sample_updates order by id;
```

**Comment by JimBacon** [comment]
The app has been fixed. After it has been released and some time has elapsed to allow people to upgrade, the above query should be re-run.  Keep this issue open until that has been done.

**Comment by CrisSevilleja** [comment]
The issue looks like solved, the direct links to the "View sample details" and  "Edit Sample Details" buttons on the grid in the My Data > My Samples page.

I checked the three surveys, 15-minute counts, transect, and moth traps and all of them responded well. 
Thank you!

**Comment by JimBacon** [comment]
Checked for any samples in survey 681 without an input_form and there are none. No further action needed.
