### ISSUE TITLE
All sites page should not be visible to 'scheme co-ordinator' role

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#51]
Only admin should be able to see this page: http://live-butterfly-monitoring.pantheonsite.io/all-sites

Currently, scheme co-ordinators can also see this page.  This permission to be removed

**Comment by Gary-van-Breda** [comment]
Actually it is the "super manager" and "administrator" roles which have access to this. Care should be taken not to confuse the permission "region coordinator" with the role "scheme coordinator", as the scheme coordinator role is given to the people running a scheme in a particular country, but the permission "region coordinator" is given to the role "super manager" and is given to people who control the site at a pan-country level, i.e. people who manage the schemes en-masse, one level up.
On this front, only a minimum of people should be given the administrator role: I think we should remove "Xavier Mestdagh" and "CristinaSevilleja" from this list, and I'm not sure "CristinaSevilleja" should be a supermanager either. They should be "scheme coordinators" for their countries, and we should make sure that those roles have the permissions required for what they want to do, rather than give them everything!

**Comment by DavidRoy** [comment]
Agree that we should reduce admin role.  Cristina is the co-ordinator for ABLE so needs the wider role. I will adjust the user permissions.  Can you address the original request about 'all-sites' page only being available to 'super manager' and 'admin' roles.

**Comment by DavidRoy** [comment]
I've updated the user accounts on http://live-butterfly-monitoring.pantheonsite.io

**Comment by Gary-van-Breda** [comment]
I think the original comment has been addressed at some point: masquerading as a scheme co-ordinator (and not a supermanager user) shows no "All sites" link on the menu, and the URL gets redirected to the front page.

**Comment by DavidRoy** [comment]
Thanks, now resolved
