### ISSUE TITLE
Rulesets for flagging European Butterfly data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#511]
new issue following on from #187 

After evaluation of options, way forward is to:
separate rule-sets for:
1. checks against species' range
2. checks against time of year by biogeographic range

Approach:
Mirror database table format already in data model:
_cache_verification_rules_without_polygon_ for species range checks
_cache_verification_rules_period_within_year_ for phenology checks
Add to scheduled task process for applying rule-set checks

Next steps
- [x] @DavidRoy to supply speices range maps
- [x] @burkmarr to import speices range maps and add to cache table process
- [x] @DavidRoy to supply biogeographic zone layer
- [x] @burkmarr to import biogeographic zone layer and add to set of indexed locations
- [x] @DavidRoy to supply phenology range checks for species by biogeographic zones
- [x] @burkmarr to import phenology range data and add to cache table process

**Comment by chrisvanswaay** [comment]
@DavidRoy On the phenological data, do you want to use the outcomes of Reto's work? I think he said he also included the altitude btw.

**Comment by DavidRoy** [comment]
@chrisvanswaay yes, I was intending to start with Reto's outputs but will need a manual approach for the rarer species.  I think a relatively crude approach is ok for this as it's main aim to highlight clear errors

**Comment by chrisvanswaay** [comment]
@DavidRoy  We can even use the RL data for that. Lets see, should not be too complicated.

**Comment by DavidRoy** [comment]
@chrisvanswaay good idea.  Do you mean using the opportunistic data for all species.  A single automated approach would be good

**Comment by chrisvanswaay** [comment]
@DavidRoy I could simply check for each BGR for each species in which months >95% of the observations is done (or something like that). That would not be too much work.

**Comment by DavidRoy** [comment]
@chrisvanswaay that would great, thanks

**Comment by chrisvanswaay** [comment]
@DavidRoy Attached a csv with the top 95% per BGR per species. I split up the month into two periods (I and II, divide at day=15).
[flightperiod_95perc.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/10391802/flightperiod_95perc.csv)

**Comment by chrisvanswaay** [comment]
This is all GBIF data from after 2010, so you find a few funny species, simply ignore them.

**Comment by kazlauskis** [comment]
Could this be used in the app itself? Something similar to how we show and hide suggestions in the iRecord Butterflies app.

**Comment by chrisvanswaay** [comment]
As GBIF has no column for stage, there might be non-adults involved in some cases, so you might have to give it a check for that.

**Comment by chrisvanswaay** [comment]
@DavidRoy Apart from this there should be a validation of the photos. Constanti sent me an email to underline that the Spanish moth experts find this very important. We must find some way to get this done, either on this site or by leading it to the observation.org site (but then the validation result should also come back to our data here).

**Comment by DavidRoy** [comment]
@chrisvanswaay there is a already a verification system for reviewing records.  I can setup verification roles if you email me with who needs this (I'd need their email used to register on the system and area covered).

**Comment by chrisvanswaay** [comment]
@DavidRoy Does that include the validation of photos?

**Comment by DavidRoy** [comment]
@chrisvanswaay it is verifying the whole observation, including review/redetermination of photos where they are included

**Comment by chrisvanswaay** [comment]
OK, will ask Constanti for email addresses.

**Comment by burkmarr** [comment]
@chrisvanswaay - is day 15 in period I?

**Comment by burkmarr** [comment]
@DavidRoy - I have the species range data but not biogeographical ranges yet. No rush - I'm just starting to look at this again now.

**Comment by burkmarr** [comment]
In prep for the _checks against species' range_ checks I have loaded the species ranges into a temporary table in the warehouse `iss_able_511_sp_range2` that reflects the structure of the the `cache_verification_rules_without_polygon` table.

@johnvanbreda - looking at my notes from the meeting we had, it looks like you suggested inserting these data directly into the  `cache_verification_rules_without_polygon` table, leaving the `verification_rule_id` field blank. Have I understood that correctly? If not, then can you outline the approach should I take?

**Comment by johnvanbreda** [comment]
It was a thought, I'm not 100% sure it is the cleanest way, but it would be the simplest way to get the desired outcome. Or another thought is a 2nd table extra_verification_rules_without_polygon, then using a union query in the verification rule to get all the data joined together. That would keep the data separate, but I'm not sure if it would affect the query performance. 

Any other thoughts?

**Comment by chrisvanswaay** [comment]
@burkmarr Yes, period I is day 1-15, period II is 16-31.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda. I'm working on something else for a couple of days but will give this some thought for when I return to it.

**Comment by burkmarr** [comment]
@johnvanbreda - I've added a new data cleaner module to address task 2 (checks against time of year by biogeographic range) to the develop branch (https://github.com/Indicia-Team/warehouse/tree/develop/modules/data_cleaner_ebms_phen_biogeoreg). Would you be able to review it at some point?

The phenology data for each region can consist of a number of discontinuous periods as shown below:

![image](https://user-images.githubusercontent.com/9275178/232489858-96f02400-2de6-43a1-a8ab-1b3185cb6351.png)

One thing that concerns me a bit is that when I ran this data cleaner module on an imported dataset of around 4500 records (local docker implementation), it seemed to take quite a long time (see below). I am a bit puzzled by that because when I run equivalent SQL directly in pgAdmin, it runs *much* faster.

![image](https://user-images.githubusercontent.com/9275178/232490820-5460434a-88e1-4a43-95df-6098e78b3f33.png)

**Comment by johnvanbreda** [comment]
Of course. 

For the config file, I think it should be renamed *.php.example, so the person installing the module should copy and rename it, setting the appropriate location type ID when they do so. That way it's not warehouse specific.

Is the group by actually necessary? You may find it's a bit quicker with a WHERE rather than HAVING. 

Regarding the performance, if you were actually only running the one module, then I'd be interested in knowing more! One thing to bear in mind is if you repeat a near-identical query then caching will dramatically improve the performance for the 2nd time it's run. Perhaps you could log the value of microtime(TRUE) at certain points in the data cleaner module code to see how long the actual query run takes, as the scheduled tasks run will be doing other stuff such as build the delta table of records to scan. You could also log the exact query it's running and prepare the occdelta temporary table in the same way so you can replicate the exact query in pgAdmin (as if you were comparing a run in pgAdmin against the cache_occurrences_functional table vs a run in scheduled tasks using the occdelta table, not the latter doesn't have the same indexing).

**Comment by burkmarr** [comment]
Great - thanks John. I will investigate all the above.

**Comment by burkmarr** [comment]
@johnvanbreda - I used GROUP BY in conjunction with the SUM because it was the only way I could think of to identify records where the occurrence date failed against _all_ of the phenology ranges recorded for that taxon and biogeographical region combination. For example if there are three discontinuous phenology ranges for a particular taxon/region (e.g. the Steppic region in the _Melitaea phoebe_ example above), then the SQL has to select the occurrence only if its date is outside the date range expressed in _all three_ associated verification_rule_data records. Is there a way to do that without a GROUP BY?

```
GROUP BY co.id, vr.error_message, co.taxa_taxon_list_external_key, co.verification_checks_enabled, co.record_status
     HAVING SUM((EXTRACT(doy from co.date_start) >= EXTRACT(doy from cast('2012' || vrdStartDate.value as date)) AND
          EXTRACT(doy from co.date_end) <= EXTRACT(doy from cast('2012' || vrdEndDate.value as date)))::integer) = 0
```

**Comment by johnvanbreda** [comment]
Ah - I see. It may or may not be worth doing any more on this anyway as the current technique is fine unless it's preventing the query optimiser doing a good job. If the query does seem to need further optimisation, then I would have thought you could do something like the following:

```sql
...
LEFT JOIN verification_rule_data vrdStartDate ON 
          vrdStartDate.verification_rule_id = vr.id AND 
          vrdStartDate.key = 'StartDate' AND
          vrdStartDate.deleted = false
LEFT JOIN verification_rule_data vrdEndDate ON 
          vrdEndDate.verification_rule_id = vr.id AND 
          vrdEndDate.key = 'EndDate' AND 
          vrdEndDate.data_group = vrdStartDate.data_group AND
          vrdEndDate.deleted = false AND
          EXTRACT(doy from co.date_start) >= EXTRACT(doy from cast('2012' || vrdStartDate.value as date)) AND
          EXTRACT(doy from co.date_end) <= EXTRACT(doy from cast('2012' || vrdEndDate.value as date)
...
```
Then put "vrdEndDate IS NULL" into the where clause. This isn't tested though but I think it should work.

2 additional thoughts:
Does the query need to account for the verification_rules.reverse_rule flag?
Is indexing the Biogegraphical regions an option?

**Comment by burkmarr** [comment]
@johnvanbreda - the performance difference between pgAdmin and the data_cleaner query was, as you anticipated, due to the fact that I was joining on cache_occurrences_functional in pgAmin rather than occdelta. When I reproduced in pgAdmin with an occdelta join, the performance was the same. 

Actually I found that in the previous test mentioned above a lot of the test data was in the wrong place (I mixed up W & E of longitude when generating it!) and much of it fell outside any biogeographical regions. With fixed data (with all the records overlapping a biogeographical region) the performance is even slower.

So I looked at your SQL suggestion above, but using the LEFT JOINS without the GTROUP BY doesn't work because it identifies any record where the date falls outside *any* of the discrete date ranges used in a single rule. But to fail the rule check, it has to fall outside *all* of them.

I turned to your idea of using the warehouse's spatial indexing module to index the occurrences against biogeographical regions. When I do that and replace the spatial query with a simple join (`join cache_occurrences_functional cof on cof.id = co.id AND l.id = ANY (cof.location_ids)`) the query is over 25 times faster. So that would seem to be the way to go.

But there something I am unclear of here. When I import a CSV of records into the warehouse, entries for `task_spatial_index_builder_sample` and `task_spatial_index_builder_occurrence` are added to the work_queue, but I'm struggling to understand how or if I can guarantee that those tasks are processed by the work_queue scheduled task before the record_cleaner scheduled task runs for the affected occurrences. Isn't there a danger (even a likelihood) that the record_cleaner task will run before some of the occurrences have been spatially indexed (given that they are batched up and all)?

Regarding the verification_rules.reverse_rule flag, I didn't account for it because I have coded it only for the eBMS phenology within biogeographical region use case (in the interests of releasing it as soon as I can) and the rule data supplied to me are always positive (i.e. date ranges in which the butterfly *does* occur). I suppose there is potential for a general phenology within location type rule which would require a bit more generalisation, including making use of the reverse_rule flag. Right now I'd rather press on and get this released. If there was ever a similar requirement from another use case, we could then perhaps replace this with a more generalised version?

**Comment by johnvanbreda** [comment]
@burkmarr I agree with your assessment of the reverse_rule use case not being important here - certainly if it delays things or makes them more complicated/slower, then it doesn't seem worthwhile.

Are there any indexes used when the query runs against cache_occurrences_functional that are not available when using occdelta? E.g. there is a spatial index ix_cache_occurrences_functional_public_geom which might come into play. Adding the indexes to occdelta might be an option. You can use explain analyze before the query (plus a handy site for viewing the results - https://explain.depesz.com/).

The scheduled tasks process does include functionality so that the records processed only include those up to where the spatial indexer has got to. So your concerns shouldn't be a problem. Look near the top of the scheduled_tasks class runScheduledPlugins method if you want to check how this works.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda.

>  Adding the indexes to occdelta might be an option. 

That had occurred to me and I already tried adding a spatial index to occdelta - actually I tried indexing a number of the fields - and to my great surprise it didn't make much difference. I didn't get to the bottom of *why* joining to cache_occurrences_functional was so much quicker than occdelta - I will take another look at that.

> The scheduled tasks process does include functionality so that the records processed only include those up to where the spatial indexer has got to

That's great! So using spatially indexed biogeographical regions is a real possibility then. I see from the config file for the spatial index builder than indexing for a given location type can be restricted to certain datasets so we could restrict spatial indexing  on biogeographical region to records in eBMS datasets. If I don't make any progress with significantly improving the performance of the spatial join, I will go with this method.

**Comment by burkmarr** [comment]
@johnvanbreda

> I didn't get to the bottom of why joining to cache_occurrences_functional was so much quicker than occdelta - I will take another look at that. 

Thanks to your tip about using explain analyze, I found that the spatial index I created on occdelta.public_geom in pgAdmin wasn't being used. A bit of googling told me that I had to run analyze on occdelta in order to make the new index available to the query planner. Once I'd done that, the timings were the same.

I ran a new test on around 4000 records which took only around 210 seconds using the spatial join with a usable index - so a considerable improvement on before (around 940 seconds with similar number of records). However using the warehouse spatial indexing with `l.id = ANY (co.location_ids)` instead of the spatial join took only 16 second for the same records.

So I think using the latter method is probably better - not only because it will allow these data cleaner rules to run much faster, but because it doesn't involved messing with the existing data_cleaner code in order to build a usable spatial index on occdata. What do you think?

**Comment by johnvanbreda** [comment]
I agree - 210 seconds to process 4000 records is quite slow. I think the biogeographical region could actually be a useful location boundary across the board anyway, so indexing it makes sense I think.

**Comment by burkmarr** [comment]
@johnvanbreda @JimBacon - I'm pretty sure that these eBMS rules may need updating from time to time. I've been looking into the mechanism for doing that. 

Currently I have specified the rules as text files (input into the warehouse as a zipfile). I thought that if I uploaded a new zipfile with rules with the same text filenames, then the original rules would be updated, but instead new ones are created. Is that expected behaviour?

If instead I code the rules in a CSV file and use the RuleID column to specify a unique identifier, then re-submitting rules via a CSV with the same identifiers does update the existing rules. But I'm having trouble getting rule *data* to upload via this method - either the instructions are not right or there is a problem with the code (which I'm trying to figure out). Furthermore, I'm not sure if the CSV method can handle groups in the data section like the individual text files can.

Any insights from either of you would be helpful.

**Comment by burkmarr** [comment]
Hang on. It seems that the actual zipfile has to have the same name - not just the rule files within it. I've managed to update a rule that way.

**Comment by burkmarr** [comment]
But I don't understand it - the zipfile name doesn't appearn to be stored in source_filename in the rules table.

**Comment by burkmarr** [comment]
Oh but there it is in source_url!

**Comment by burkmarr** [comment]
@johnvanbreda - is it okay to deploy this new record cleaner module as a hotfix since there are no changes to existing code?

**Comment by burkmarr** [comment]
@chrisvanswaay - in order to make the rules in Indicia as succinct as possible, I recompose the data you supplied here - https://github.com/BiologicalRecordsCentre/ABLE/issues/511#issuecomment-1378607442 -  so that contiguous date ranges are expressed in a single range. These ranges are summarised here: 
[rules-summary.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/11275240/rules-summary.csv)

It might be a handy document to check if there are any obvious gaps. For example I noticed that for _Aglais io_ in the Atlantic region, there is a gap in the first half of June which doesn't seem right.

**Comment by johnvanbreda** [comment]
@burkmarr I don't see why not, but worth checking the scheduled task processes are all running smoothly an hour or two afterwards.
The import process for rules was written to make use of the existing servers for Record Cleaner rules, rather than to make it easy for manual import. That's probably why there are a few oddities as you've found.

**Comment by burkmarr** [comment]
Pull request for hotfeature: https://github.com/Indicia-Team/warehouse/pull/478

**Comment by chrisvanswaay** [comment]
@burkmarr Thanks. As I took the 95% limit, for a very common and widespread species as Aglais io in the Atlantic that might still generate a lot of records to check. As it's a simple R script, I can also change the percentage to 98% or 99% and run it again. We might have a look first, if too many errors of such moments turn up, I can run the script again. Hope it's not too difficult to turn my output into the rules.

**Comment by burkmarr** [comment]
@chrisvanswaay - no its fine I have a script to automate it. So if you do decide to provide an update at some point, it is an easy job for me to run the scripts to regenerate the rules. When these are imported again into the warehouse, any changes will be applied. So as long as you supply the rule CSV in the same format again, it is not a problem.

**Comment by burkmarr** [comment]
@DavidRoy - we're ready to go with both of these now.

1. checks against species' range
2. checks against time of year by biogeographic range

For number 1 I just need to upload a prepared temporary table into the cache_verification_rules_without_polygon table and the species range rules will be active. For number 2 I will need to configure the warehouse to use the new phenology within biogeographical region data cleaner module, import the prepared rule data and configure the spatial indexing (see below). Once I've done that, the rules will be active against any new occurrences coming in with eBMS exeternal keys. Let me know if you want me to go ahead with that.

@johnvanbreda shall I limit the spatial indexing for biogeographical regions to eBMS datasets or make it more general. Also do you think there's any need to re-index existing samples/occurrences?

**Comment by johnvanbreda** [comment]
@DavidRoy you may have an opinion on whether the bioregions are of wider use so should be indexed across all the data?

If the purpose of the bioregion data is limited to applying verification rule checks to incoming data, then re-indexing all the existing data would be a large overhead for no reason. But if we are seeing the bioregion as having wider value then it would be worth doing the existing data.

**Comment by DavidRoy** [comment]
@johnvanbreda The bioregions do not have a wider use at the moment.
Are you ready to go now?

**Comment by burkmarr** [comment]
@DavidRoy - I am ready to go. If we are going to restrict the spatial indexing to eBMS datasets, I just need to know which ones. 
![image](https://user-images.githubusercontent.com/9275178/233966887-f9b97400-2601-4851-a492-cc97282d1d25.png)

**Comment by DavidRoy** [comment]
@burkmarr These ones to start with:
421
565
563
562
589
645

**Comment by burkmarr** [comment]
Both the species range and the phenology within biogeographical region should now be operational for eBMS.

**Comment by DavidRoy** [comment]
@burkmarr should I be seeing the rule-check results already?  e.g. on https://butterfly-monitoring.net/elastic/all-records

**Comment by burkmarr** [comment]
@DavidRoy - the verification checks will only fire against new records entered since I enabled the rules. Do you want me to run them against all the records created this year in the datasets listed above? If so, I think that I would just need to select them and update their 'updated_on' field.

**Comment by DavidRoy** [comment]
@burkmarr that would be great, thanks!  We 'may' want to go back further in time but we'd need to manage impact on the background processes?

**Comment by burkmarr** [comment]
@DavidRoy - I've changed the updated flag on the records from those surveys with a record date in 2023, so they should start getting validated against the rules.

**Comment by burkmarr** [comment]
@johnvanbreda and @JimBacon. I could use a sanity check here. I have added the 'European Biogeographical Regions 2016' region type to the spatial_index_builder configuration file (limiting to eBMS datasets) and it appears to be working correctly for all records added since I enabled it.

But I realised that I need to trigger a spatial index build for all the eBMS records entered this year (because we want to run the new phenology in biogeographical region data clear rules against these too and this requires that they are spatially indexed against the biogeography regions). So I added task_spatial_index_builder_occurrence tasks to the work_queue for these records (around 20,000 of them). They appear to have been processed okay - they've gone from the work_queue. However, when I check the location_ids attribute, only a couple of hundred of these 20,000 records have been indexed against a biogeographical region (and those may well have been entered after I enabled the spatial indexing). 

This is the SQL I used to add tasks to the work queue:
```
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)  
select distinct 'task_spatial_index_builder_occurrence', 'occurrence', o.id, 60, 2, now()  
from occurrences o 
join samples s on s.id = o.sample_id 
join cache_taxa_taxon_lists cttl on cttl.id = o.taxa_taxon_list_id 
where s.survey_id in (421, 565, 563, 562, 589, 645) -- a record from an eBMS survey 
and cttl.external_key like 'eBMS%' -- an eBMS external key 
and extract('year' from s.date_start) = 2023 -- a record from this year 
and o.created_on<'2023-04-25' -- created before biogeographical regions added to spatial cache builder 
```
After the work_queue tasks cleared, I ran this SQL to see if occurrences which should have indexed against the biogeographical regions have been missed. (I know that there is a more efficient way of doing this than the subselect, but I resorted to this to be absolutely sure I was querying the records which were entered into the work queue.)
```
select cof.location_ids, l.id, l.name 
from cache_occurrences_functional cof 
join locations l on st_intersects(cof.public_geom, l.boundary_geom) and l.location_type_id = 20642 
where cof.id in ( 
  select o.id from occurrences o 
    join samples s on s.id = o.sample_id 
    join cache_taxa_taxon_lists cttl on cttl.id = o.taxa_taxon_list_id 
    where s.survey_id in (421, 565, 563, 562, 589, 645) -- a record from an eBMS survey 
    and cttl.external_key like 'eBMS%' -- an eBMS external key 
    and extract('year' from s.date_start) = 2023 -- a record from this year 
    and o.created_on<'2023-04-25' -- created before biogeographical regions added to spatial cache builder 
  ) 
-- the array lists the location ids of all the European biogeographical regions
and not (cof.location_ids && array[307265,307254,307255,307256,307257,307258,307259,307260,307261,307262,307263,307264])
limit 100 
```
This shouldn't find any records if the location indexing has worked, but it produces output like this:
![image](https://user-images.githubusercontent.com/9275178/234284223-daeeae8d-6410-40d0-9614-9e2b3938edfb.png)

**Comment by JimBacon** [comment]
Hi Rich,
You need to do `task_spatial_index_builder_sample` first because the occurrence locations are copied from the samples.

**Comment by burkmarr** [comment]
Thanks very much @JimBacon - I was just coming to that conclusion looking at the spatial index builder code. I should have looked first.

**Comment by burkmarr** [comment]
@DavidRoy - my apologies, the new data cleaner module is failing to generate occurrence comments even though the problem with biogeographical regions is sorted. I am looking into it.

**Comment by burkmarr** [comment]
I had neglected to tick the 'Enable auto-verification checks' checkbox for eBMS website in the Warehouse. Once I'd done that I had to rebuild the cache tables for this year's eBMS records in order to propagate that new setting to the cache_occurrences_functional table. And once that was complete I updated the updated_on field on the occurrences records, the rules started to run against them.

From around 32,000 records entered so far this year 3,659 have been flagged as being outside the known phenology for the biogeographical region in which they were recorded. I've checked a good few of these and they correctly failed the checks according to the data in @chrisvanswaay's phenology CSV.

Also 1,959 records have been flagged as being outside the known European range for the species. But on closer inspection, many of these may be because the species range data we have used are not very accurate around the coasts the image below shows the species range for _Aglais urticae_ together with records of that species that failed the check. 

![image](https://user-images.githubusercontent.com/9275178/234598200-ed1f05ca-09a4-4cf6-9f70-211d5043fbac.png)

One record is outside Europe but the one in the Netherlands is due to this digitising as the second image shows.

![image](https://user-images.githubusercontent.com/9275178/234598571-bf8d9515-067a-41d3-90ee-19bec59b27e0.png)

@DavidRoy - I think that I should probably buffer the species range polygons in these rules. I think a buffer of around 5 km would be safe. What do you think?

**Comment by chrisvanswaay** [comment]
If these are my maps, then indeed I simplified them. In this case I agree a buffer of 5 or 10km seems appropriate.

**Comment by burkmarr** [comment]
Okay thanks @chrisvanswaay - I will buffer to 10km.

**Comment by burkmarr** [comment]
The polygons in the species range rules are now buffered to 10km.

**Comment by DavidRoy** [comment]
Thanks @burkmarr. A couple of questions:
1. Should we run the checks again on existing data?
2. Can we restrict the checks to butterflies only?  Some of the surveys allow other taxa and I notice that Bombus species got a green tick (i.e. didn't fail any rulechecks)
3. Can we restrict geographically as I noticed that data from Turkey was flagged as 'out-of-range' presumably because our range maps don't extend that far

**Comment by chrisvanswaay** [comment]
All my polygons are only working in the RL Europe area. Attached a shape of the total area.
[UNCountries2010Europe_SIS_updated.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/11342642/UNCountries2010Europe_SIS_updated.zip)

**Comment by burkmarr** [comment]
@DavidRoy

> 1. Should we run the checks again on existing data?

I can re-run the rules against the records entered this year, but until points 2 and 3 are resolved, I should probably hold off on that.

> 2. Can we restrict the checks to butterflies only? Some of the surveys allow other taxa and I notice that Bombus species got a green tick (i.e. didn't fail any rulechecks)

The rules themselves are only applied to butterflies. I guess that the 'didn't fail rulechecks' tick is applied by other code to any records coming from a website that has enabled auto verification checks and which don't fail data cleaner checks. @johnvanbreda - is there anything I can do about that within the existing data structure/code logic?

> 3. Can we restrict geographically as I noticed that data from Turkey was flagged as 'out-of-range' presumably because our range maps don't extend that far

This can't be done using the approach we've taken which is to make use of the existing _without polygon_ rule after inserting the species range polygons directly into the `cache_verification_rules_without_polygon` table. If we want to restrict the species range rules to occurrences that fall within some larger polygon, then we'd have to abandon the current approach and create another new data cleaner module.

However, I wonder if this is really a problem. The species range error messages are of this format: _Location is outside the known European range of [...]_.  Since the data cleaner rules are only there to assist verifiers and the comment explicitly refers to Europe, then verifiers of records outside Europe should feel comfortable ignoring them. So if this will affect relatively few records, is it really a problem?

**Comment by DavidRoy** [comment]
Thanks @burkmarr 
We can live with number 3 but something to consider in future.
Similarly, we can live with number 3 if John can't suggest a simple fix.  Maybe an incentive to build up rule-sets for the other taxon groups.

**Comment by burkmarr** [comment]
@DavidRoy Okay - I'll go ahead and rerun checks on existing data.

**Comment by DavidRoy** [comment]
@burkmarr the rule checks are not being applied to data submitted in the last few days.  Should it be?

**Comment by burkmarr** [comment]
Yes they should be – I’ll have a look.

**Comment by burkmarr** [comment]
@DavidRoy - the last checks were run on Sunday morning. It looks to me that no data cleaner rules have been applied since that time. The warehouse is reporting that some scheduled tasks appear not to be running (http://warehouse1.indicia.org.uk/index.php/) - which could include the data cleaner. @BirenRathod - any idea what might be going on there?

**Comment by BirenRathod** [comment]
@burkmarr Not sure, so let me check and let you know.

**Comment by JimBacon** [comment]
It's usually the spatial index builder skipping a record causing everything to come to a halt. Something like this happens every few weeks.

**Comment by BirenRathod** [comment]
@burkmarr Scheduled_tasks not running properly since yesterday morning. I got below message logged in scheduled_tasks. 
-- Task Scheduler did not launch task "\Indicia Scheduled Task"  because instance "{cd74b39e-0132-4c19-812d-fabed8cf743e}"  of the same task is already running.

I have stopped scheduled_tasks and restarted but it is not completing the task properly.

**Comment by JimBacon** [comment]
@BirenRathod, try the following which John emailed us last November

> If you get this problem, then the following query can be run on the warehouse. First, run a query like the following to find an ID of a record just before the timestamp that it’s stuck on (keep running the query with a different offset until you find one - it doesn’t have to be accurate, it’s just to save a table scan on the whole table):
> 
> select id, updated_on from cache_samples_functional order by id desc limit 1 offset 40000;
> 
> Then you can run the following, replacing the ID with the one you found:
> 
> insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
> select 'task_spatial_index_builder_sample', 'sample', s.id, 100, 2, now()
> from cache_samples_functional s
> left join work_queue q on q.task='task_spatial_index_builder_sample' and q.record_id=s.id
> where s.location_ids is null and s.id>20500911 -- replace this ID
> and q.id is null;
> 
> That will re-queue the samples so they get indexed.
>

**Comment by BirenRathod** [comment]
@JimBacon Yes, that is what I'm trying at present as I have seen a warning on the warehouse UI home page about priority task taking longer to finish query.

**Comment by BirenRathod** [comment]
@johnvanbreda @JimBacon & @burkmarr 
Just to let know the scheduled task took 51 minutes to finish the whole task after running manually. Below is the log I found alert: Scheduled tasks for notifications, work_queue, all_modules took 3067.713093996 seconds.

Not sure, what is causing of delaying that but there could be some alerts related ecobat module which might be the primary cause of this. See here -> https://github.com/BiologicalRecordsCentre/iRecord/issues/1463

**Comment by burkmarr** [comment]
@BirenRathod there still don't appear to be any record cleaner checks happening and the system table has the `last_scheduled_task_check` field set to `2023-04-30 11:18:14` for many of the tasks including the data_cleaner.

**Comment by johnvanbreda** [comment]
This is likely to be an issue we've seen before with the spatial indexer missing a record batch, so they aren't then ever in a state where the record cleaner can process them. I'll take a look now - also note that I'm half way through some code updates so this sort of thing will self-repair.

**Comment by BirenRathod** [comment]
@johnvanbreda I stopped the scheduled_tasks, so let me know once you sort out this.

**Comment by johnvanbreda** [comment]
@BirenRathod OK - I've just triggered it again and will monitor to see if that fixes the problem.

**Comment by JimBacon** [comment]
@johnvanbreda are you still working on this? task_cache_builder_update appears to still have a problem from what I observe at https://warehouse1.indicia.org.uk/index.php/diagnostics.

**Comment by BirenRathod** [comment]
@johnvanbreda Also, I missed letting you know yesterday that there were warnings generated in scheduled_tasks yesterday but that is not the same. it works absolutely fine.

**Comment by johnvanbreda** [comment]
@JimBacon thanks - there was a batch of tasks which had been "claimed", i.e. processing had started, but they never finished (claimed_by and claimed_on was not null - if claimed_on is more than an hour old it is likely something went wrong). There is nothing obvious in the logs so I've just cleared these 2 fields so they get reprocessed.

The original issue with spatial indexing not completing has been sorted though.

@BirenRathod what warnings are you referring to?

**Comment by BirenRathod** [comment]
@johnvanbreda Same as this one -> https://github.com/BiologicalRecordsCentre/ABLE/issues/511#issuecomment-1531250197
but that is not a problem anymore, so don't worry.

**Comment by johnvanbreda** [comment]
Ah - that's OK then, that is correct behaviour if the tasks are taking a while to finish.
