### ISSUE TITLE
URGENT - Walk Data Entry eBMS not working

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#513]
@DavidRoy 

A volunteer reported and I checked with several masqueraded users on the Walk Data Entry page https://butterfly-monitoring.net/walk-data-entry?location_type_id=777&date=03/01/2023 is not possible to select the transects, so the transect visit cannot be saved and records cannot be entered. Not transects show on the drop-down list (as screenshot below).
![entry data error](https://user-images.githubusercontent.com/25052478/211282012-99ab8baa-0a18-4db6-85d1-3d5728c3506b.png)

Please solve this as soon as possible.

**Comment by DavidRoy** [comment]
@andrewvanbreda can you look into this, including @Gary-van-Breda if needed

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I will look now

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
Could you get me this result please. Cheers

select * from indicia.location_attribute_values
where location_attribute_id = 234 and location_id = 240245;

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, no problem.

**Comment by andrewvanbreda** [comment]
Hi @johnvanbreda @Gary-van-Breda
It is hard for me to debug this exactly, as am new to project (so no experience of what it did before), but also the dev/test sites point to live, which are not in debug mode on the logs.
However I can see the issue occurs when someone isn't a Super Manager.

In this case, the first part of the code below runs where the CMS User ID is added to the report params. This causes nothing to be returned even though actually the CMS User ID (1535) is present for the attribute for the user in question.
As I say I don't have any experience of what the website used to do.
John: locations_list is just a general report, and doesn't have an explicit attr_location_cms_user_id param, is this something that would get automatically picked up by the report?
Presumably yes else it would have no effect.
Given that, and this website seems to have had no recent updates (apart from a small unrelated one I just deployed), has the warehouse been changed at all in such a way that might stop this working.

      $siteParams = self::$auth['read'] + array('website_id' => $args['website_id'], 'location_type_id'=>$locationType[0]['id']);
      if ((!isset($args['user_locations_filter']) || $args['user_locations_filter']) &&
          (!isset($args['managerPermission']) || !hostsite_user_has_permission($args['managerPermission']))) {
        $siteParams += array('locattrs'=>'CMS User ID', 'attr_location_cms_user_id'=>hostsite_get_user_field('id'));
      } else
        $siteParams += array('locattrs'=>'');
      $availableSites = data_entry_helper::get_population_data(array(
        'report'=>'library/locations/locations_list',
        'extraParams' => $siteParams,
        'nocache' => true
      ));

**Comment by andrewvanbreda** [comment]
@johnvanbreda @Gary-van-Breda
Checking this further on my own box, if I supply attr_location_branch_cms_user_id in code to locations_list as a param (in a hacked version of the same code), the Warehouse completely ignores the param as if it is not there. So I am at a bit of a loss as to what is happening here.
As say, I don't have access to what the Warehouse is attempting to run.

**Comment by johnvanbreda** [comment]
Looking at the code in Github (e.g. in Sectioned_transects_input_sample) there seems to be an assumption that if locattrs is set to 'CMS User ID' to include a system function column then it can be referred to as 'attr_location_cms_user_id' as a parameter. I need to do some testing to see if I can work out if this works and where the branch version of this attribute came from.

**Comment by DavidRoy** [comment]
@Gary-van-Breda is working on #255 which is adding a layer of regional co-ordinator access (i.e. 'branch').  This may explain the issue occurring now?

**Comment by andrewvanbreda** [comment]
Hi @johnvanbreda 
I hadn't actually noticed there were two similar parameters in the logs.
Regardless, actually attr_location_cms_user_id actually does the same thing on my box and is ignored by my Warehouse as well, but prob way I have setup the attribute.
My test isn't very useful anyway, as live isn't doing that anyway, and you have confirmed it should work.
Live isn't ignoring the param, but is filtering, but is filtering down to nothing.
It is also the case it suddenly started doing that, it didn't use to.

The problem is the test sites are also pointing at live, so I can't see any logs at all.
At the moment I can't reproduce it on my box, and I can't see any logs.....so am a bit stuck.
The only thing I can thing of is to put live's logging into debug mode, so we can see literally what it is trying to run

**Comment by johnvanbreda** [comment]
That's what I'd suggest doing at this point - just put live into log threshold 4 for the shortest time possible to capture the required logging.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
These queries are not appearing in the logs.
I have also tried with a Super Manager who does get a list of locations returned, and no sql appears in the logs for them either.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Am sure it must be to do with Warehouse. According to Pantheon this site has hardly changed recently.
Also all the dev/test/live are behaving same way, so it can't be accidental configuration change on edit tab.

**Comment by johnvanbreda** [comment]
I can turn on logging for you but would want to do that when you are ready to run the query so we don't leave the logs running. Do you want to Skype me?

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja @DavidRoy 
We have fixed EBMS.
The problem is that there are two attributes with the same name being used by SPRING and EBMS, and a sharing agreement setup between the two websites has confused the system.
This is technically a bug in the Warehouse as agreements shouldn't cause this to happen.
I will raise that in Github.
For now, I have changed the name of the attribute associated with the SPRING site.
This means EBMS is now back to functioning normally.
However I now need to change the SPRING site to take into account the parameter name change (which I will do as soon as I can this evening).

**Comment by DavidRoy** [comment]
Thanks for tracking this down @andrewvanbreda @johnvanbreda 
I setup the sharing agreement so that the SPRING butterfly data was available to EBMS co-ordinators

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I have checked SPRING and it isnt actively using the attribute at the moment, and it looks to be working, so have put that online.
I will may need to take this into account when coding this
https://github.com/BiologicalRecordsCentre/SPRING/issues/102

Please close this (513) when you are satisfied EBMS is working.

**Comment by CrisSevilleja** [comment]
Thank you, Andrew, John and David for resolving this so fast. Now eBMS website is working well and allows selecting the transect route to save records.
