### ISSUE TITLE
French BMS - import locations

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#514]
linestrings are in WKT format, supplied by Reto Schmucki

**Comment by JimBacon** [comment]
Notes:

- The WKT is in EPSG: 4326 
- The section_id is not unique.
- Some sections in transects are labelled unused/abandonned in the section_name so should probably be removed to avoid them being presented to recorders.

Querying the latter point by email.

**Comment by JimBacon** [comment]
The transects were imported from the file provided, without modifications, as follows.

The received CSV file contains columns for
transect_id, section_id, transect_name, section_name, geometry_section
There is one row per transect section.

To create each transect, the results of the following query (having imported the supplied csv file into a table, temp_french_ebms_transects) were exported as a csv file and then imported using the warehouse website interface.

```sql
WITH sections_per_transect AS (
	SELECT transect_id, COUNT(*) AS nr_sections
	FROM temp_french_ebms_transects
	GROUP BY transect_id
),
length_of_sections AS (
	SELECT transect_id, section_id, ST_Length(ST_GeogFromText(geometry_section), true) AS section_length
	FROM temp_french_ebms_transects
),
length_of_transects AS (
	SELECT transect_id, SUM(section_length) AS transect_length
	FROM length_of_sections
	GROUP BY transect_id
),
centroid_of_transects AS (
   SELECT
   transect_id, 
   ST_Y(ST_Centroid(ST_Collect(ARRAY_AGG(ST_GeomFromText(geometry_section, 4326))))) lat,
   ST_X(ST_Centroid(ST_Collect(ARRAY_AGG(ST_GeomFromText(geometry_section, 4326))))) lon
   FROM temp_french_ebms_transects
   GROUP BY transect_id
),
transects AS (
	SELECT DISTINCT
		transects.transect_id AS external_key, 
		transects.transect_name AS name,
		concat(round(lat::numeric, 5), ' ', round(lon::numeric, 5)) AS centroid_sref,
		nr_sections,
		round(transect_length) AS transect_length,
		216023 AS country
	FROM temp_french_ebms_transects AS transects
	JOIN centroid_of_transects AS centroids
		ON centroids.transect_id = transects.transect_id
	JOIN sections_per_transect AS sections
		ON sections.transect_id = transects.transect_id
	JOIN length_of_transects AS lengths	
		ON lengths.transect_id = transects.transect_id
)
SELECT 
	transects.*,
	'EBMS:France:' || (ROW_NUMBER() OVER(ORDER BY transects.name) + 32) AS code
FROM transects
ORDER BY transects.name
```

32 was added to the row number to create the transect code as there were already 32 French transects in existence.

Similarly the transect sections were generated from the output of the following query.
During the csv import a parent location type of transect was selected and the transect_id was mapped to Parent Location External Key

```sql
WITH length_of_sections AS (
	SELECT 
		transect_id, 
		section_id, 
		ST_Length(ST_GeogFromText(geometry_section), true) AS section_length
	FROM temp_french_ebms_transects
),
centroid_of_sections AS (
   SELECT
	   transect_id, 
	   section_id, 
	   ST_Y(ST_Centroid(ST_GeomFromText(geometry_section, 4326))) lat,
	   ST_X(ST_Centroid(ST_GeomFromText(geometry_section, 4326))) lon
   FROM temp_french_ebms_transects
)
SELECT
	transects.transect_id AS parent_location_external_key,
	transects.section_id AS external_key, 
	transects.transect_name,
	transects.section_name AS name,
	'S' || ROW_NUMBER() OVER (
		PARTITION BY transects.transect_id 
		ORDER BY 	
			COALESCE(SUBSTRING(transects.section_name FROM '([0-9]+)')::BIGINT, 9999999),
			COALESCE(SUBSTRING(transects.section_name FROM '_([0-9]+)')::BIGINT, 9999999),
			COALESCE(SUBSTRING(transects.section_name FROM '([0-9]+)$')::BIGINT, 9999999),
			SUBSTRING(transects.section_name FROM '[a-zA-z_-]+')
	) AS code,
	concat(round(lat::numeric, 5), ' ', round(lon::numeric, 5)) AS centroid_sref,
	round(section_length) AS section_length
FROM temp_french_ebms_transects AS transects
JOIN centroid_of_sections AS centroids
	ON centroids.transect_id = transects.transect_id
	AND centroids.section_id = transects.section_id
JOIN length_of_sections AS lengths	
	ON lengths.transect_id = transects.transect_id
	AND lengths.section_id = transects.section_id
ORDER BY 
	transects.transect_name, 
	COALESCE(SUBSTRING(transects.section_name FROM '([0-9]+)')::BIGINT, 9999999),
	COALESCE(SUBSTRING(transects.section_name FROM '_([0-9]+)')::BIGINT, 9999999),
	COALESCE(SUBSTRING(transects.section_name FROM '([0-9]+)$')::BIGINT, 9999999),
	SUBSTRING(transects.section_name FROM '[a-zA-z_-]+')
```

The complicated ORDER BY for creating the code is because a variety of standards exist within the section names.
The lines work, respectively, for section names like
 - T1_Vacquerolles, T2_Vacquerolles, T3_Vacquerolles, ...
 - 1032_1, 1032_2, 1032_3
 - Buhy-2 1, Buhy-2 2, Buhy-2 3, ...
 - 1228_1, 1228_1b
 
Now it remains to set the boundary_geom for each section. This was done with the following query.

```sql
UPDATE locations AS section
SET boundary_geom = ST_Transform(ST_GeomFromText(geometry_section, 4326), 900913)
FROM locations AS transect, temp_french_ebms_transects AS f
WHERE transect.id = section.parent_id
	AND transect.location_type_id = 777
	AND transect.code LIKE 'EBMS:France:%'
	AND f.transect_id = transect.external_key::integer
	AND f.section_id = section.external_key::integer
```

**Comment by JimBacon** [comment]
If historic data is imported, it is important not to simply join on the original section_id (stored in the external_key) as it was non-unique. A combination of transect_id (also stored in the external_key) and the section_id must be used.

**Comment by JimBacon** [comment]
It is not assumed this issue is closed because the matter of how we handle abandoned sections has probably not been adequately dealt with. Correspondence with Benoît Fontaine continuing by email.

**Comment by JimBacon** [comment]
A note on the the French survey method and terminology.

- The parent location is known as a 'site' which might be, for example, a grid square. Geometrically it is a polygon. I have not received those polygon boundaries.
- Within the site, multiple, unconnected lines are surveyed, which are known as 'transects'.

This is in contrast to the British terminology I have been using where the parent location is known as a transect and is a line. This line is divided in to sections which are the child locations.

I will use the French terminology to continue the commentary on this issue.

**Comment by JimBacon** [comment]
As noted already, there are sites where transects have been abandoned and alternative transects have been added. So far, all sites have been imported with all transects. They are needed so that historic records can be imported against them. However, to enable online recording without presenting abandoned transects I need to 

1. Rename sites with abandoned transects with 'inutilisé' in the title so that recorders will not use them.
2. Duplicate those sites with the abandonned transects removed.

This has resulted in the following actions

- **Site 978**, with unused transects, renamed [978  inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310032) and [978](https://butterfly-monitoring.net/ebms-site-details?id=316212) created.
- **Site 1160**, with 6 and 6bis transects, renamed [1160 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=309986) and [1160](https://butterfly-monitoring.net/ebms-site-details?id=316202) created.
- **Site 1228**, with 1 and 1b transects renamed [1228 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=309990) and [1228](https://butterfly-monitoring.net/ebms-site-details?id=316203) created.
- **Site 1297**, with unused transects, renamed [1297 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=309992) and [1297](https://butterfly-monitoring.net/ebms-site-details?id=316204) created.
- **Site 1463**, with abandoned transects, renamed [1463 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=309998) and [1463](https://butterfly-monitoring.net/ebms-site-details?id=316205) created.
- **site 1755**, with unused transect, renamed [1755 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310003) and [1755](https://butterfly-monitoring.net/ebms-site-details?id=316206) created.
- **Site 1756**, with unused transects, renamed [1756 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310004) and [1756](https://butterfly-monitoring.net/ebms-site-details?id=316207) created.
- **Site 1777**, with 1 and 1b transects, renamed [1777 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310005) and [1777](https://butterfly-monitoring.net/ebms-site-details?id=316208) created.
- **Site 2049**, with abandoned transects, renamed [2049 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310012) and [2049](https://butterfly-monitoring.net/ebms-site-details?id=316209) created. *
- **Site 2050**, with abandoned transects, renamed [2050 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310013) and [2050](https://butterfly-monitoring.net/ebms-site-details?id=316210) created. *
- **Site 2622**, with abandoned transect, renamed [2622 inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310021) and [2622](https://butterfly-monitoring.net/ebms-site-details?id=316211) created. *
- **Site Ustaritz**, with 1 and 1bis transects, renamed [Ustaritz inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310448) and [Ustaritz](https://butterfly-monitoring.net/ebms-site-details?id=316214) created.
- **Site RN Marais d'orx**, with bis transects renamed [RN Marais d'orx inutilisé](https://butterfly-monitoring.net/ebms-site-details?id=310433) and [RN Marais d'orx](https://butterfly-monitoring.net/ebms-site-details?id=316213) created.

(*) Sites 2049, 2050, and 2622 had transects removed which resulted in the transect numbering and the EBMS section numbering being different which has the potential to cause confusion.

For [site 1601](https://butterfly-monitoring.net/ebms-site-details?id=310000), with transects 2/2b and 3/3b where 2 and 3 have never been used, deleted 2 and 3 and renamed 2b/3b as 2 and 3.

In addition, where typographical errors in transect names seemed to be present causing the section numbers to appear unreasonable, I performed some alterations as follows:

- [Site 1449](https://butterfly-monitoring.net/ebms-site-details?id=309997), transect with name 1149_8 renamed 1449_8 and all transect codes updated to be in logical order.
- [Site 2106](https://butterfly-monitoring.net/ebms-site-details?id=310014), transects with names 2016_5 and 2016_6 renamed as 2106_5 and 2106_6. All transect codes updated to be in logical order.

In order to import the revised sites and to distinguish them from the ones replaced, I added '.01' to the external_key of the new sites. This may need changing in the future.

**Comment by JimBacon** [comment]
Currently I am awaiting a response to the following email, sent on 19th April:

> There is still one outstanding question I’d like you to check, if you can.
> 
> There are a few transects which appear on two different sites.
> 
> For example, 
> the site  with name 1815 has transects named 1755_3, 1755_5, 1755_6, 1815_1, 1815_2, 1815_3, 1815_4, 1815_5.
> the site named 1755 has transects named 1755_1, 1755_2, 1755_3, 1755_4.
> 
> Transect 1755_3 appears in both sites and is exactly the same path. It has the transect id of 11541.
> 
> Is this correct?

**Comment by JimBacon** [comment]
Response received by email

> I have checked the transects you listed. Indeed, transects 1755_3, 1755_5 and 1755_6 are in the perimeter of two different overlapping sites. For the sake of clarity, I think they should be attachedc to site 1755 in the eBMS database.
> And yes as well, there are two transects named 1755_4 , both with observations. Maybe you could call them 1755_4a and 1755_4b  in the eBMS database ?

**Comment by JimBacon** [comment]
I've just modified  sites 1815 and 1755 as proposed by Benoît in the email referenced above. I think this completes the task.
