### ISSUE TITLE
Slow reports to investigate

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#57]
reports_for_prebuilt_forms/UKBMS/ukbms_taxon_meanings_at_transect.xml
reports_for_prebuilt_forms/UKBMS/ukbms_occurrences_list_for_parent_sample.xml

reviewing server logs reveals these two reports as being slow.

@Gary-van-Breda @johnvanbreda to evaluate options for improvement (i.e. using ElasticSearch) as they will be used for ABLE

**Comment by johnvanbreda** [comment]
Both the above reports are averaging now at < 2s. It's possible that at the point you checked the request log it had been recently cleared, so your results may have been skewed by whatever was happening in the few hours preceding. I occasionally clear it, particularly if I've updated a report or made a change that will affect overall performance significantly so that we get a fresh look at the performance as it is after the changes were applied. 

Looking at the data now (which has a few days worth in it) I have identified the following reports as being worth exploring:
* reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list.xml
* reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list_mapping_lores.xml
* reports_for_prebuilt_forms/UKBMS/ebms_region_locations.xml
* reports_for_prebuilt_forms/UKBMS/ukbms_visits_and_sites_summary.xml

**Comment by johnvanbreda** [comment]
I'll raise separate issues for these to keep the discussions tidy.

**Comment by DavidRoy** [comment]
Thanks.  I'll close this general issue as now being picked up separately
