### ISSUE TITLE
Slovak coordinator not able to register transects on eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#578]
The user Indicia Warehouse User ID: 351462, the Slovak coordinator is not able to register new transects and enter on eBMS pages related to data entering or visualization. When entering the pages the message shown is: "The website encountered an unexpected error. Please try again later." 

The pages with error for this user: My transect sites: https://butterfly-monitoring.net/my-sites, My walks page: https://butterfly-monitoring.net/my-walks and My annual report page: https://butterfly-monitoring.net/annual-report

For other users, this is not happening although the coordinator is reporting other users under Slovak BMS are suffering the same. 
She found this error last Thursday 2nd of June. 

Any clue what is going on @andrewvanbreda @johnvanbreda ? thanks

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Just finishing another task, but I will look at this today.

**Comment by andrewvanbreda** [comment]
@BirenRathod
This is being caused by that Language drop-down issue I mentioned (I think other users are getting this too).

I am going to try another iForm upate. iForms are a bit difficult on the site at the moment as I need to exclude a lot of the forms from it. However I will try my best again.
I also do not know if that will help.
If you have any ideas let us know.

Message | Error: Call to a member function getName() on null in Drupal\lang_dropdown\Form\LanguageDropdownForm->buildForm() (line 229 of /code/web/modules/custom/lang_dropdown/src/Form/LanguageDropdownForm.php)

**Comment by JimBacon** [comment]
@andrewvanbreda would you like to try out https://github.com/Indicia-Team/drupal-module-iform-custom-forms. It should allow all the custom forms to be taken out of the iForm module and managed properly, freeing you up to install the latest and greatest version of the iForm module.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Thanks for the link.
This looks precisely what we need after I have finished organising EBMS/UKBMS.
The problem I have at the moment is that both projects share forms, that are different between the two projects (and are also different to what is committed in Indicia teams).
I have done work to merge the forms, but they are still in the branch that Gary is developing on, although that is due to be deployed, so hopefully this will all be sorted out soon.
I will see if can start using that module with one of the simpler projects to start.

**Comment by BirenRathod** [comment]
> @BirenRathod This is being caused by that Language drop-down issue I mentioned (I think other users are getting this too).
> 
> I am going to try another iForm upate. iForms are a bit difficult on the site at the moment as I need to exclude a lot of the forms from it. However I will try my best again. I also do not know if that will help. If you have any ideas let us know.
> 
> Message | Error: Call to a member function getName() on null in Drupal\lang_dropdown\Form\LanguageDropdownForm->buildForm() (line 229 of /code/web/modules/custom/lang_dropdown/src/Form/LanguageDropdownForm.php)

@andrewvanbreda This error generates after lang_dropdown module updated. There is no bug in the new release but it is now checking every block or menu of missing with translation. if it is then it should be translated in that language. It will not stop accessing the page unless that whole language is not available.

**Comment by andrewvanbreda** [comment]
@BirenRathod @JimBacon 
I am not so sure about this.
If that is the case we have a bit problem because I think lots of the languages aren't complete translations.
Actually I think the issue might be that the Czech Site Language selection made on the My Account page, there is no Czech selection availbale in the language drop-down selector that is appearing on the pages.
This appears to be the different to the other languages that are working.
Although this is a theory, it seems to hold up in testing.
However I do not know why the not all the countires are available in the language selector drop-down that are available in on the account page.

**Comment by DavidRoy** [comment]
@andrewvanbreda please add in any missing languages. There is no reason to have them, just not been implemented yet

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @BirenRathod 
OK, I see what is happening.
The error occurs when the you go to a page and there is no version of the page in the list of translated pages.
Here you will see I added Czech (even if it is just a clone of the english) and it fixed the problem on that page for Czech users.
https://butterfly-monitoring.net/node/42/translations
So to fix this entirely in all circumstances, I think I need to add a version of each page for every language on the site.
Biren: Does that match up with the way you are thinking about this?
Anyone see a reason I shouldn't be doing that?
I have to say if is not great the module throws a fatal error under these circumstances.

**Comment by DavidRoy** [comment]
@andrewvanbreda I agree on implementing that solution. This is a change to how the module behaves as we've always had untranslated pages?

**Comment by CrisSevilleja** [comment]
@andrewvanbreda when there is a page without translation, like in the case of the Czech language, I include the English version. In that way, the system has a "translation" added even is still English and it doesn't give errors. 
It looks like we need to add the version for the Czech in this page to avoid issues, is that right?

I am in contact with the Czech and Slovak coordinators to apply their translations soon.

**Comment by BirenRathod** [comment]
> Hi @DavidRoy @BirenRathod OK, I see what is happening. The error occurs when the you go to a page and there is no version of the page in the list of translated pages. Here you will see I added Czech (even if it is just a clone of the english) and it fixed the problem on that page for Czech users. https://butterfly-monitoring.net/node/42/translations So to fix this entirely in all circumstances, I think I need to add a version of each page for every language on the site. Biren: Does that match up with the way you are thinking about this? Anyone see a reason I shouldn't be doing that? I have to say if is not great the module throws a fatal error under these circumstances.

@andrewvanbreda Yes, that is exactly my meaning of the word translation used. the page/block/menu should be available in that language.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Yes, this is right.
Each page can have a version for each language, as you see in the screenshot below.
It didn't used to matter if some were missing, but now it seems to. The the proposed solution is to add these in, as you can see in this example I have added Czech (even though it is actually in English) but it does get rids of the errors.
I will go ahead with this right now as everyone is in agreement.
 
![Screen Shot 2023-06-05 at 12 36 58](https://github.com/BiologicalRecordsCentre/ABLE/assets/2463614/4076aa92-b6fa-4163-b5da-9994a0ba5e5a)

**Comment by andrewvanbreda** [comment]
@CrisSevilleja 
This is fixed now site wide, have tested the example user you gave. 
Please close the issue once you are happy everything is ok. 
Hope that helps.

**Comment by andrewvanbreda** [comment]
Note for reference: 
Some pages only have the English page translation enabled and no other translations. 
These pages seem to work ok, so have left them for now. 
The list of these pages is attached.
[English only pages.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/11654690/English.only.pages.txt)

**Comment by CrisSevilleja** [comment]
thank you @andrewvanbreda now this issue is solved
