### ISSUE TITLE
Import South Africa butterfly list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#603]
- [x] add taxon attribute for South Africa
- [x] add South Africa as scheme on butterfly-monitoring.net
- [x] import species list into warehouse
- [x] make list available in the ButterflyCount app

SA tab in: 
[STATISTICS - JUL 2023.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/12079020/STATISTICS.-.JUL.2023.xlsx)

**Comment by JimBacon** [comment]
@DavidRoy There is no SA tab in the attached file... no species list to import.

**Comment by DavidRoy** [comment]
@JimBacon here it is
[Butterflies  AFRICA LIST - JULY 2023 as amended for iNat.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/12646342/Butterflies.AFRICA.LIST.-.JULY.2023.as.amended.for.iNat.xlsx)

**Comment by JimBacon** [comment]
@DavidRoy what do you want to do about external_keys for these species? I did "ABMS" + \<spreadsheet row number\> for Botswana but can't do exactly the same here as that would cause duplicates.

**Comment by DavidRoy** [comment]
@jimBacon - good question.  I'm happy to go with your advice on this.  Maybe for SA use "ABMS-SA" and for the Botswana list "ABMS-BW" (changing the ones already in the system?)

**Comment by JimBacon** [comment]
Using the warehouse user interface,
- Added one subfamily, Cyrestinae, 
- Reassigned 38 existing genera to subfamilies where they were previously direct descendants of families,
- Imported 43 new genera from file.
[new-genera.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/12651286/new-genera.txt)

Noted the genus Sevenia, used in this list, is present in the existing EBMS species list as a synonym of Sallya.

**Comment by JimBacon** [comment]
Of 807 taxa in the list 
 - 231 matched existing records on taxon name and authority so a taxon attribute was set indicating presence in South Africa,
 - 231 matched new genera so were imported from csv file
 - 320 matched existing genera but were new names so were imported from csv file
[new-taxa-present.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/12663352/new-taxa-present.csv)
 - 16 matched existing records on taxon name but not authority so need review
 - 4 were near matches to taxon names of existing records so need review
 - 5 matched existing synonyms so need review

The 16 records  matching on taxon name but not authority are 

taxa_taxon_list_id | Taxon |  Existing authority| New authority
--- | --- | --- | ---
432141 | Pelopidas thrax | (Hübner, 1821) | (Hübner, [1821])
432282 | Azanus ubaldus | (Stoll, 1782) | (Stoll, [1782])
432317 | Freyeria trochylus | (Freyer, 1844) | (Freyer, [1844])
548726 | Acraea neobule | Doubleday, 1847 | Doubleday, [1847]
548790 | Byblia ilithyia | Drury, 1773 | (Drury, 1773)
548813 | Charaxes candiope | Godart, 1824 | (Godart, [1824])
548870 | Charaxes zoolina | Westwood, 1850 | (Westwood, [1850])
548880 | Coeliades keithloa | Wallengren, 1857 | (Wallengren, 1857)
548882 | Coeliades pisistratus | Fabricius, 1793 | (Fabricius, 1793)
548924 | Colotis ione | (Godart, 1819) | (Godart, [1819])
548985 | Euryphura achlys | Hopffer, 1855 | (Hopffer, 1855)
548998 | Graphium antheus | (Cramer, 1779) | (Cramer, [1779])
549085 | Melanitis leda | Linnaeus, 1758 | (Linnaeus, 1758)
549152 | Pardopsis punctatissima | Boisduval, 1833 | (Boisduval, 1833)
549173 | Precis antilope | Feisthamel, 1850 | (Feisthamel, 1850)
549223 | Tirumala petiverana | (Doubleday, 1847) | (Doubleday, [1847])

The 4 records which are near matches to existing taxa are

taxa_taxon_list_id | Existing taxon | New taxon
--- | --- | ---
548704 | Acada biseriatus | Acada biseriata
548797 | Charaxes achaemeres | Charaxes achaemenes
549188 | Pseudacraea boisduvali | Pseudacraea boisduvalii
548943 | Cupidopsis iobates | Cupidopsis jobates

The 5 records which are currently affected by synonyms are 
taxa_taxon_list_id | Existing taxon | New taxon
--- | --- | ---
548945 | Cymothoe coronus | Cymothoe coranus coranus
549203| Salamis parhassus | Protogoniomorpha parhassus
549214 | Sallya boisduvali | Sevenia boisduvali boisduvali
549217 | Sallya natalensis | Sevenia natalensis
 |  | Sevenia rosa

In addition Sevenia morantii (taxa_taxon_list_id = 619251) also needs review. It was imported as an existing taxon, originating from the Botswana list which also includes Sevenia amulia intermedia (619564) and Sevenia trimeni trimeni (619511).

**Comment by stevewoodhall** [comment]
The 4 records which are near matches to existing taxa - explanations:

_Acada biseriata_ is correct; _Acada_ is feminine in Latin so the specific name takes the same gender. It was originally described as _Pamphila biseriata_ Mabille, 1893, and Dickson & Kroon mis-spelled it as _Acada biseriatus_ in their 1978 publication.

_achaemenes_ is correct: original description is _Charaxes achaemenes_ Felder & Felder, [1867] in Felder & Felder, [1865-7].  Reise der Österreichischen Fregatte Novara 446 (549 pp.). Wien. _achaemeres_ is a mis-spelling,

_Pseudacraea boisduvali_ is a Spelling mistake by Bernard D'Abrera. Ref: _Diadema boisduvalii_ Doubleday, 1845.  Annals and Magazine of Natural History (1) 16: 180 (176-182). _Pseudacraea boisduvali boisduvali_ [sic] Doubleday, 1845. D’Abrera, 2004. 

_Cupidopsis jobates_ is correct. The specific name has, in the past, often been misspelt as _iobates_.

**Comment by stevewoodhall** [comment]
Regarding the 16 records matching on taxon name but not authority: I don't know why Prof Williams used square brackets thus: '(Hübner, [1821])'. I can't ask him since he recently died, alas. I've asked Dr Edge, Editor of our Journal, _Metamorphosis_.

**Comment by stevewoodhall** [comment]
5 Records affected by synonyms: 

_Cymothoe coronus_ is a mis-spelling. _Cymothoe coranus coranus_ Grose-Smith, 1889 is the nominate subspecies of four (_Cymothoe coranus dowsetti_ Beaurain, 1988, _Cymothoe coranus kiellandi_ Beaurain, 1988, and _Cymothoe coranus murphyi_ Beaurain, 1988). NB the 'e' in 'Cymothoe carries an umlaut but I can't work out how to insert special characters in this app!

_Protogoniomorpha_ (Mother-of-Pearls) is an Afrotropical genus containing five species. Removed from synonymy with _Salamis_ by Wahlberg et al. (2005). _Protogoniomorpha parhassus_ is correct,

Ackery et al. (1995: 359) follow Jenkins 1990 (Bulletin of the Allyn Museum No. 131: 177 pp.) in treating _Sallya_ [= _Sevenia_] as generically distinct; the more usual convention has been to regard _Sallya_ as a subgenus of the otherwise New World genus _Eunica_ Hübner. Lees et al. (2003) treat _Sevenia_ as a subgenus of _Eunica_ but Larsen (2005a) treats it as a genus distinct from _Eunica_.  The genus _Sevenia_ belongs to the Family Nymphalidae Rafinesque, 1815; Subfamily Biblidinae Boisduval, 1833; Tribe Epicaliini Guenée, 1865. There are no other genera in the Tribe Epicaliini in the Afrotropical Region.  _Sevenia_ (Tree Nymphs) is an Afrotropical genus containing 17 species. 

_Sevenia boisduvali boisduvali_ and _Sevenia natalensis_ are correct.

_Crenis rosa_ Hewitson, 1877.  Entomologist’s Monthly Magazine 14: 82 (81-83).
 _Crenis rosa_ Hewitson, 1877.  Trimen & Bowker, 1887a. 
_Crenis rosa_ Hewitson.  Swanepoel, 1953a. 
_Sallya amulia rosa_ (Hewitson, 1877).  Dickson & Kroon, 1978. 
_Sallya rosa_ (Hewitson, 1877).  Pringle et al., 1994: 112.  [Not seen by Ackery et al., 1995] 
_Sallya  amulia rosa_ (Hewitson, 1877).  Ackery et al., 1995: 359. 
_Sevenia rosa_ (Hewitson, 1877).  Koçak, 1996. This is the current name for the taxon.

_Sevenia morantii_ (Trimen, 1881).  Koçak, 1996. Occurs in Botswana, Mokokwane, Tswapong Hills (A. Gardiner [2001] vide Larsen, 1991l). 

_Sevenia trimeni trimeni_ according to Williams does _not_ occur in Botswana. The _Sevenia amulia intermedia_ record from there is probably a vagrant,

**Comment by DavidRoy** [comment]
@JimBacon please give preference to the ABMS names based on further details:

_1) Taxon names: The Afrotropical Butterflies taxon names are correct. The spellings of species names in the "existing" checklist are incorrect. These errors were probably typographical in origin, and were not picked up during proof reading.

Authorities: It seems that the differences between the "existing" checklist and the "new" one are all because of the (correct) usage of square brackets in the Afrotropical Butterflies checklist. Square brackets around a date of publication indicate that the publication itself was written over a period of some years, and the year given in the square brackets is the inferred actual year of publication. The IUZN Code allows only a single year, not multiple years. This can be important in determining the priority of names._

**Comment by JimBacon** [comment]
Updates to the taxon list were made as follows:

- _Acada biseriatus_ changed to _Acada biseriata_ as there are no existing records of this taxon.
- _Charaxes achaemeres_ changed to _Charaxes achaemenes_ as there are no existing records of this taxon and _Charaxes achaemenes achaemenes_ added as a subspecies.
- _Pseudacraea boisduvali_ changed to _Pseudacraea boisduvalii_ as there are no existing records of this taxon and _Pseudacraea boisduvalii trimenii_ added as a subspecies.
- _Cupidopsis iobates_ changed to _Cupidopsis jobates_ as there are no existing records of this taxon and _Cupidopsis jobates jobates_ added as a subspecies
- _Cymothoe coronus_ changed to _Cymothoe coranus_ as there are no existing records of this taxon and _Cymothoe coranus coranus_ added as a subspecies
- _Salamis parhassus_ changed to _Protogoniomorpha parhassus_ as there are no existing records of this taxon
- Authorities for all 16 species were updated. 13 had no records but there were records for _Pelopidas thrax_, _Freyeria trochylus_, and _Charaxes candiope_. Three of the changes affected species from the European list (_Pelopidas thrax_, _Freyeria trochylus_, _Azanus ubaldus_)
- The genus Sallya was changed to Sevenia as there are no reocrds against it or any descendant taxa.
- _Sevenia rosa_ was added
- _Sallya boisduvali_ made a synonym and _Sevenia boisduvali_ the preferred name. _Sevenia boisduvali boisduvali_ added as subspecies.
- _Sallya natalensis_ made a synonym and _Sevenia natalensis_ the preferred name.
- _Sallya umbrina_ made a synonym and _Sevenia umbrina_ the preferred name.
- _Sallya amulia_ made a synonym and _Sevenia amulia_ the preferred name.

A further synonym, not previously noticed, was _Afrodryas leda_ = _Eronia leda_. As there were no records of _E. leda_ and we are giving preference to the ABMS list I made _A. leda_ preferred.

**Comment by DavidRoy** [comment]
@kazlauskis can you implement SA for the app?

**Comment by stevewoodhall** [comment]
Hi Jim,

Thanks for this – I’ve copied in David Roy and the three people in LepSoc Africa who are working on curating our names database. This change was necessitated because the man who was running the Afrotropical Butterflies Encyclopaedia, Prof Mark Williams, sadly died recently and unexpectedly. He was incredibly active and hardworking, and replacing him is not going to be straightforward. Jeremy Dobson is the President of the Lepidopterists’ Society and Dave Edge edits our Journal, Metamorphosis. Tom Desloges has been working extensively on a project we have to harmonise Africa’s butterfly common names and is a very active ‘Identifyer’ on iNaturalist. 

I see that David has emailed me whilst I was writing this, let me have a look!

Best Regards
Steve Woodhall

**Comment by stevewoodhall** [comment]
Hi David,

Synchronicity is an amazing thing. Word has got out about the ‘ABMS’ and I’ve just had a local estate manager on the phone bending my ear with ‘when can we start?’!

Best Regards
Steve Woodhall

**Comment by JimBacon** [comment]
Hi @stevewoodhall 

All the updates I mentioned in my last comment are to our existing list to make it consistent with the list you provided. Thanks for the great work and attention to detail. The only change I made which we hadn't previously discussed was making _Afrodryas leda_ the preferred name over the synonym _Eronia leda_.

Just so you understand, I am the database gopher, with minimal taxonomic knowledge, so put me right if you see anything that looks wrong. I'm off for the weekend now.

Best wishes,
Jim Bacon.

**Comment by stevewoodhall** [comment]
Thanks Jim,

 

Yes, Afrodryas leda is the new name. It looks as if we’re good to go, but that’s not for me to decide – Jeremy needs to press the ‘go’ button as our Pres. and Dave needs to let us all know he’s happy too.

 

Best Regards

 

Steve Woodhall

ButterflyGear 082 825 8450

2 Madeleine Drive Gillitts

 ***@***.***> ***@***.***

**Comment by kazlauskis** [comment]
> can you implement SA for the app?

Yes. Is the species list finalised now?

**Comment by stevewoodhall** [comment]
Hi Karolis,

 

As far as I know the list is as complete as it can be at this moment in time although taxonomy is always developing especially with all the DNA studies on the go right now. We will simply have to keep you updated as we become aware of new changes.

 

I can’t greenlight this from LepSoc Africa’s standpoint – that’s the prerogative of Dave Edge and Jeremy Dobson.

 

Best Regards

 

Steve Woodhall

ButterflyGear 082 825 8450

2 Madeleine Drive Gillitts

 ***@***.***> ***@***.***

**Comment by stevewoodhall** [comment]
Hi SteveAn updated African butterfly list is circulated bimonthly via the LepSoc Africa newsletter. There will always be small changes; for example while developing common names for Liptena, I noticed two subspecies that had been recently raised to full species. I’d included the new species but had forgotten to delete the former subspecies. In addition, there are regular updates to the English common names.We haven’t resolved details, but the Afrotropical Butterflies encyclopaedia will be revised annually and posted on the LepSoc Africa / Metamorphosis websites.All the bestJeremySent from my iPhoneOn 05 Oct 2023, at 22:02, ***@***.*** ***@***.*** { font-family: "Cambria Math"; }
@font-face { font-family: Calibri; }
p.MsoNormal, li.MsoNormal, div.MsoNormal { margin: 0cm; font-size: 11pt; font-family: Calibri, sans-serif; }
a:link, span.MsoHyperlink { color: blue; text-decoration: underline; }
span.EmailStyle20 { font-family: Calibri, sans-serif; color: windowtext; }
.MsoChpDefault { font-family: Calibri, sans-serif; }
@page WordSection1 { size: 612pt 792pt; margin: 72pt; }
div.WordSection1 { page: WordSection1; }Hi Karolis, As far as I know the list is as complete as it can be at this moment in time although taxonomy is always developing especially with all the DNA studies on the go right now. We will simply have to keep you updated as we become aware of new changes. I can’t greenlight this from LepSoc Africa’s standpoint – that’s the prerogative of Dave Edge and Jeremy Dobson. Best Regards Steve WoodhallButterflyGear 082 825 84502 Madeleine Drive ***@***.*** <image001.jpg> From: Karolis Kazlauskis ***@***.***> Sent: Thursday, October 5, 2023 8:09 PMTo: BiologicalRecordsCentre/ABLE ***@***.***>Cc: stevewoodhall ***@***.***>; Mention ***@***.***>Subject: Re: [BiologicalRecordsCentre/ABLE] Import South Africa butterfly list (Issue #603) can you implement SA for the app?Yes. Is the species list finalised now?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by stevewoodhall** [comment]
Hi Jeremy,

 

This is good news and I’m sure the BMS people will be reassured that the names in the encyclopaedia will continue to be curated going forward. I’d like a view from David Roy and his colleagues – will an annual update be acceptable, or would they prefer to be alerted every time a name change/addition occurs?

 

As far as iNaturalist is concerned, you (or maybe Dave?) can give me the details of any name change and I (or Tom, who is also active on iNat) can ‘flag’ it for curation. All they need is the old names (if applicable), the linked (if applicable) new names, and the citation of the paper in which the change was published. We don’t have to wait until year end.

 

What I was alluding to in this mail was, are we ready to ‘go-live’ with the ‘ABMS’ right now? The understanding I have is that once the databases have been harmonised there will be two ‘country lists’ available with more to follow. I would suggest that David Roy makes the transect app available for SA and Botswana as soon as possible and we can start ‘beta testing’ them. During this period LepSoc can decide on how best to roll it out and give it the stamp of approval – and then when it’s launched, publicise the heck out of it. 

 

Best Regards

 

Steve Woodhall

ButterflyGear 082 825 8450

2 Madeleine Drive Gillitts

 ***@***.***> ***@***.***

**Comment by DavidRoy** [comment]
@stevewoodhall we can update the taxonomy as you need, and can fit in with your schedule of updates. 
Are we ok to go live for SA and Botswana?

**Comment by stevewoodhall** [comment]
Hi David,

 

From my side, yes! I can start beta testing almost immediately.

 

I’d be happy to see an official reply from LepSoc though. 

 

Best Regards

 

Steve Woodhall

ButterflyGear 082 825 8450

2 Madeleine Drive Gillitts

 ***@***.***> ***@***.***

**Comment by stevewoodhall** [comment]
Hi SteveThe checklist is freely available to LepSoc Africa members; there no issue should you wish to share it, although LSA would like accreditation where appropriate.We discussed you being our ABMS representative at a Council meeting, so go for it!All the bestJeremySent from my iPhoneOn 07 Oct 2023, at 09:16, ***@***.*** ***@***.*** { font-family: "Cambria Math"; }
@font-face { font-family: Calibri; }
p.MsoNormal, li.MsoNormal, div.MsoNormal { margin: 0cm; font-size: 11pt; font-family: Calibri, sans-serif; }
a:link, span.MsoHyperlink { color: blue; text-decoration: underline; }
span.EmailStyle20 { font-family: Calibri, sans-serif; color: windowtext; }
.MsoChpDefault { font-family: Calibri, sans-serif; }
@page WordSection1 { size: 612pt 792pt; margin: 72pt; }
div.WordSection1 { page: WordSection1; }Hi David, From my side, yes! I can start beta testing almost immediately. I’d be happy to see an official reply from LepSoc though.  Best Regards Steve WoodhallButterflyGear 082 825 84502 Madeleine Drive ***@***.*** <image001.jpg> From: David Roy (CEH) ***@***.***> Sent: Saturday, October 7, 2023 6:38 AMTo: BiologicalRecordsCentre/ABLE ***@***.***>Cc: stevewoodhall ***@***.***>; Mention ***@***.***>Subject: Re: [BiologicalRecordsCentre/ABLE] Import South Africa butterfly list (Issue ***@***.*** we can update the taxonomy as you need, and can fit in with your schedule of updates.Are we ok to go live for SA and Botswana?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by DavidRoy** [comment]
@kazlauskis can you update the app species list and include South Africa and Botswana as options in settings
@stevewoodhall we will also update the app credits.  Can you provide some material for ABMS, e.g. a short description and a logo if appropriate

**Comment by kazlauskis** [comment]
OK, I'll do it this week.

**Comment by stevewoodhall** [comment]
Hi David,

Thanks for this. I see that Jeremy has just got back from holidaying in Turkey so that’s probably why he’s been a bit thin on the ground in this respect!

We should ask LepSoc Africa to approve a logo. For Dave and Jeremy’s benefit the eBMS site has its logo here https://butterfly-monitoring.net/ and UKBMS, here https://ukbms.org/ both are attractive logos, and I already have a couple of ideas. But at the beta stage we don’t need one immediately. I already have the app on my phone. Perhaps send Jeremy and Dave a link so they can play with it as well.

Under ‘How to use the app’ I would simply replace ‘Europe’ with ‘Africa’ but I’m not sure what to say about the database. Will the results be entered into the existing EBMS DB, or will it be changed to ‘Global Butterfly Monitoring database? 

(Interestingly, we have a Painted Lady migration gathering steam rapidly right now here in SA and Gerard Talavera knows about it. Should I simply log my sightings when I’m out in the field?)

In ‘About’, I would say something like ‘This app enables you to contribute to the recording and conservation of Africa’s butterflies. The app is not part of the Big Butterfly Count that is run in the UK by Butterfly Conservation each summer. The entire African butterfly list as published in the ‘Afrotropical Butterfly Encyclopaedia’ of LepSoc Africa (https://www.lepsocafrica.org/) has been captured in the (EBMS? GBMS?) database. Currently the butterfly lists for South Africa and Botswana have been noted in the database and you will be able to use this app to log counts for any species on those lists. There is no electronic field guide yet as is used in the UKBMS and EBMS apps. We recommend that you download ‘Woodhall’s Butterflies of South Africa’ (https://www.penguinrandomhouse.co.za/app/woodhall%E2%80%99s-butterflies-south-africa) and refer to that on your phone whilst you make your count. (I am already in comms with the publisher about linking them). 

We would have to say something about how to do counts, but I don’t know what to write right now and want to get cracking with the beta testing so that I do!

Something we should think about is out-of-range alerts. The problem here is that the current in-range database is scattered across LepiMAP and iNaturalist. I think the data are accessible via GBIF but I’m not sure how we would go about testing ABMS records against them to flag unlikely records. It’s not because I’m worried about the ‘stringing’ that plagues birders. It’s that so many African butterflies cannot be identified to species level by eye or even by photograph with expert input. Would we have to allow genus-level ID? The genera Afrogegenes and Leptotes already have that in iNaturalist. I am leaning towards doing something similar for Chrysoritis, Aloeides, Tarsocera, Lepidochrysops etc. Because the new app won’t work on photos like iNaturalist or LepiMAP do we’re going to have to take users’ word for it that what they are reporting is true data. This sort of thing causes problems with bird counting apps like Birdlasser; even if we don’t yet know what to do about it, we should at least have a policy in place before we go live. Maybe limit it to taxa we know to be easy to ID?

Best Regards

 

Steve Woodhall

ButterflyGear 082 825 8450

2 Madeleine Drive Gillitts

 ***@***.***> ***@***.***

**Comment by kazlauskis** [comment]
I've added South Africa to the app now. It will be ready in v1.23.0 release sometime this week.
