### ISSUE TITLE
Improve Region filter on the Scheme transect allocation page - ebms website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#610]
I like a lot the new filter "Region" in the Scheme transect allocation page https://butterfly-monitoring.net/scheme-transects-allocation, it is quite useful thanks. 

Checking it a bit, there are a few things to correct:

- [x] In the Spanish regions filter is included the Area Metropolitana de Lisboa. This belongs to Portugal and it is missing in that country.  ![incorrect regions Spain](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/abb66cd9-e9a3-4569-a0ad-c660f2418f8d)
- [x] Also Portugal is missing the Azores islands. 
- [x] If possible, the Scheme filter has twice Finland BMS and it is not ordered alphabetically. Remove one Finland BMS and order the list alphabetically. 

checking other country regions, I think they are correct.

I assigned @Gary-van-Breda considering he is doing the main work of the Regional coordinator role. Thanks for this, really good job with the Regional coordinator role.

**Comment by Gary-van-Breda** [comment]
New report deployed which uses direct link from Country->Nuts1->Nuts2, rather than comparing geometries. Form updated to use new report and ordering of schemes fixed.
Deployed to Live and checked: Points 1, 2 and 3 (second part) fixed, 
Point 3 (first part): I have unpublished the second unused Finnish BMS scheme content.

Bouncing back to @CrisSevilleja for review/closure

**Comment by CrisSevilleja** [comment]
thank you @Gary-van-Breda now the filter is better and working well showing the correct regions.
