### ISSUE TITLE
Wrong displayed Bulgarian language into Japanese - eBMS website translation

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#614]
Hi @JimBacon 
I found something strange regarding the translation of Bulgarian on the website. On the Walk Data Entry page https://butterfly-monitoring.net/bg/node/153?location_type_id=777&sample_id=21438862, the term "Species name display type: " at the end of the first page appears in Japanese when the selected language is Bulgarian. 
![data entry BG2](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/b778e80c-634c-41b4-8b4e-313c51f09277)

I checked the translation, and indeed this sentence is translated for both languages but it has been exchanged, I don't know why. 
![translation BG-JP](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/c18c37bb-5b40-4fa4-aa2f-826d2b7cf227)

I didn't push this sentence to be translated to Transifex, so I don't know what is going on.

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

I don't understand how the translation process works very well.
I can see that the sentence is not on Transifex so perhaps the Japanese translations have come by another method.
I can see that you can fix the problem by going to Configuration > Regional and Language > User interface translation.
Search for 'Species name display type' with Bulgarian as the translation language then delete the erroneous Japanese.
With no translation it will revert to English.
There is a possibility you may have to clear the Drupal cache for the change to take effect.
I left it for you to do so that you can learn how to do it.
Maybe it is just an accident made by somebody. 

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/9f6fea88-8a17-498e-a1ad-57f8ce044297)

**Comment by DavidRoy** [comment]
Yes, we've used this direct editing for some of the Japanese translations.  I suspect that this was mistakenly added for Bulgaria. @CrisSevilleja can you correct via this page on the site?

**Comment by CrisSevilleja** [comment]
corrected! thanks for the explanations and for allowing me to do it. Now the Bulgarian translation shows the English default term. Thanks. 
Can I use this direct editing for doing some translation @DavidRoy ? The Slovak wants to have the entry data for the transect completely translated, due to the issues with Transifex we have still to solve, I think this can be a good and fast way to do it.

**Comment by DavidRoy** [comment]
@CrisSevilleja - yes, you can use this page for entering translations
