### ISSUE TITLE
South Africa sample not showing on explore all page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#634]
https://butterfly-monitoring.net/elastic/all-records does not show results for this sample from south africa
https://butterfly-monitoring.net/mydata/samples/details?sample_id=24093930

@johnvanbreda Is there some setup we've overlooked for this?

Marked high priority as we want to launch the app for use in South Africa

**Comment by johnvanbreda** [comment]
The Indicia module code is quite out of date and there was a bug fix to support Southern Hemisphere mapping for Saint Helena (https://github.com/Indicia-Team/media/commit/9c57c252750a7085435f9716270af6015f0d1a49). This hasn't made its way onto butterfly-monitoring.net yet. I've patched just this change into the source code but it's only on the dev site at the moment, because there are a few other changes from both @andrewvanbreda and @Gary-van-Breda in the queue which have not been deployed yet so I don't want to deploy those inadvertently.

**Comment by DavidRoy** [comment]
ok, thanks.  Keep me posted when deployed

**Comment by johnvanbreda** [comment]
@andrewvanbreda @Gary-van-Breda can your changes be deployed or is that risky?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda I'm happy with my changes being pushed to live. That said it looks like Biren has done it anyway in last few hours....

**Comment by johnvanbreda** [comment]
@DavidRoy the code has now been deployed so Southern Hemisphere mapping will work.
