### ISSUE TITLE
Uploaded surveys not visualised on the app with internet: ButterflyCount

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#661]
### Describe the issue

I have recently done three 15min counts with the ButterflyCount app. While checking the uploaded 15min counts, I noticed that on the survey page, in Uploaded surveys, nothing was there, even though I have submitted several surveys recently. 
What was even more surprising was that when I turned off the internet, the Uploaded page worked again and showed me all my uploaded surveys, including the most recent ones. 

### Expected behaviour

The ButterflyCount app shows all my uploaded surveys on the Uploaded page under Surveys, with and without the internet.

### To Reproduce

I do as usual (video attached showing this):
 1. I start a 15-minute count and introduce the butterflies I see
 2. when the time's up, I finish the survey by clicking on the finish button
 3. Then I upload the survey directly. 
 4. I wanted to check if the survey was uploaded well, I go to Uploaded Surveys and no surveys appear there. Despite I just uploaded one. 
 5. If I switch off the internet from the phone, the uploaded surveys appear, even the most recent ones. 

### App Version

v1.24.3(312)

### Device

iPhone SE, iOs 15.6

### When did this happen

yesterday and today, 12th March 

### Screenshots

video recording my screen, sorry in Spanish the app. First I click on finish, then go to Pending surveys page, and click on Upload. Then go to Uploaded page. Later, I turn off the internet and go again to Uploaded surveys page. I hope it is clear.
https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/4aeaca75-ffbe-4c8d-8ebf-9f926468723b

### Additional context
All the surveys have been uploaded without issues to the website. I can see and edit them there.

**Comment by kazlauskis** [comment]
@CrisSevilleja, thanks for reporting this, and especially for doing the screen recording 🙂 

Since last year, the app has shown ALL of the user's uploaded records if the user is online. To do that, it uses a database that refreshes every 15 minutes. So, after you upload a record, it takes a maximum of 15 minutes to see that record in the uploaded tab. If a user is offline, we don't use the database. Offline users can only see the records that are actually present on the device, but it is instantaneous. In this first iteration of the functionality, we have built it so that it avoids the complexities of listing records from the database and also those stored locally. But as you've shown, it can be confusing, and we should improve this further.

**Comment by kazlauskis** [comment]
I've realised that NONE of your uploaded records showed up in the video. I have looked into this and found that while fetching your uploaded records, one record didn't have a field the app was expecting. This prevented other records from showing up. I have fixed this now and will release it in the next app version.

**Comment by CrisSevilleja** [comment]
okay, thank you for the explanations. I understand that works well but my issue was that no records were shown at all but without the internet yes, even the recent ones. 

Anyway, good that you already found what the error was and corrected it for the next version. Thank you so much!

PD: just a reminder, please always include the updates and changes for the translations done on the new app versions. For sure you do it but just to mention it.
