### ISSUE TITLE
Improvements Walk Data Entry page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#68]
- Start and End time allow to include any hour for the visit, even during the night. The time should be restricted between 8:00 AM and 6:00 PM to avoid mistakes

- It is placed % Sun, the majority of countries use % Cloud. Should be include both option or just calculate the opposite?

@DavidRoy @Gary-van-Breda

**Comment by DavidRoy** [comment]
Thanks @CrisSevilleja.

I agree on the start/end time restrictions

For the %Sun/%Cloud I suggest the following for @Gary-van-Breda to implement so that the past and future data is consistent:
1. Add a new sample attribute for %Cloud
2. Update existing data so that %Sun + % Cloud = 100.  Current data will have %Sun value only.
3. Replace field on walk entry field to %Cloud
4. When visit data is saved, enter relevant values for **both** %sun and %cloud for completeness
5. Data downloads should include both %sun and %cloud

**Comment by CrisSevilleja** [comment]
@DavidRoy @Gary-van-Breda 
There is one volunteer in the South of Spain was counting butterflies in November and he will continue if the weather allows him. He was a bit confused with the Sun cover, due to in BMS Spain they use Cloud cover. 

Could be possible to include the %Cloud? I imagine he will start including data at the end of January, early February. 

Thanks!

**Comment by DavidRoy** [comment]
@CrisSevilleja the plan is to have both a %sun and %cloud value and the two to be interchangeable so that cloud+sun = 100.  Since some schemes use sun and some use cloud ;-)

**Comment by CrisSevilleja** [comment]
@DavidRoy Ok, I like to have both %sun and %cloud. I would like to give it priority due to many Spanish volunteers are registering on eBMS and they are asking.

**Comment by Gary-van-Breda** [comment]
% Cloud deployed to Live.
% Cloud + % Sun = 100%, at a section level. Added to Occurrrence download from Annual summary. Re-editing a walk and going to the Butterflies tab will populate the % cloud data for an existing walk.
 
Do you need "% Cloud" at a walk level as well? (pt 3 above is not clear)
Do you need a data fix to set the value for all existing sections/walks?

**Comment by DavidRoy** [comment]
Thanks @Gary-van-Breda .  In answer to the two questions.
YES = Do you need "% Cloud" at a walk level as well? (pt 3 above is not clear)
YES = Do you need a data fix to set the value for all existing sections/walks?

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

My Walks and Scheme Walks have been reconfigured to point to this URL

The time check has been deployed to Live. Due to the node based method of implementation, we can only apply it to the new form once we have the Live node number.

**Comment by Gary-van-Breda** [comment]
I've revisited this, and pulled these time checks (which were in a node.js file) and the new check (see #277) into the form JS.
Deployed to Dev as part of the new walk data entry form:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
