### ISSUE TITLE
App doesn't show all transects for regional coordinators

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#681]
From #679 

@johnvanbreda I am trying to figure out how best to solve this one. In the past, we have used the `projects/ebms/ebms_app_sites_list.xml` report to fetch user's transects but changed it to the standard REST locations endpoint (`/index.php/services/rest/locations?location_type_id=777`) because all of the other surveys in the app use that, e.g. for moth traps and project locations etc. Now I understand that regional coordinators should also have access to other people's transects, which are not returned using the standard locations endpoint. Is there a particular parameter I can use to fetch all locations available to the user? 

I can revert functionality to the report, but it makes sense that the locations endpoint would return models that the user can access by default.

**Comment by johnvanbreda** [comment]
Agreed, but because the warehouse doesn't hold information about the regional coordinator role (that's done in Drupal) this is not trivial. Would need @DavidRoy to decide if this is a priority.

**Comment by DavidRoy** [comment]
@kazlauskis where is this requirement coming from? As the app is for recording, I'm not sure why the regional co-ordinators need to see all the transects in the region. An alternative is for the app to show all (non-sensitive) transects, ordered by proximity.
@CrisSevilleja to advise

**Comment by kazlauskis** [comment]
@DavidRoy This report has existed for a few years, and I am trying to remember the original requirement to create a report listing all transects.

@johnvanbreda thanks, I see this isn't straightforward. As part of a longer-term strategy, I am trying to align our app's internal data models to the warehouse ones as closely as possible. This is so that the apps can have a more connected data sync with the warehouse, like setting up and editing existing locations, etc. I am OK with using reports for data that needs custom access logic. Still, this same issue comes up now and again - last month, for the NPMS plots, Andy set up several custom reports, which essentially return a bunch of warehouse locations filtered with some custom access logic. So, if this can be improved at the standard REST level, that would be great.

@johnvanbreda, if Cristina says we need to support this and we don't want to change the REST, it would help if this existing `ebms_app_sites_list.xml` report returned all the location attributes—mirroring the linked warehouse locations. Just add all the existing location attributes that the REST returns and I can then switch it back to the old report. Would that be OK?

**Comment by johnvanbreda** [comment]
The problems with doing this sort of thing at the REST level are two-fold. Firstly the warehouse does not know about the Drupal roles, but I could envisage synching the roles to the warehouse being a very useful thing to do so that could be fixed. The second issue is the logic required for these sort of things is often different per project so not easy to standardise into the REST logic. I see the report system as a good way to handle these sorts of bespoke requests.

To get all the attributes, you can use the locattrs parameter with a comma separated list of IDs, or just use the value "#all_survey_attrs" and supply an additional parameter survey_id=n where n is the survey to load all attributes for.

**Comment by CrisSevilleja** [comment]
Sorry I didn't see this before and for the confusion with the regional coordinator. Actually, it is not necessary for the roles to be present in the app, this regional coordinator has assigned many transects to her account because she especially wants to see these transects in the field, but I don't think it is necessary to show all transects to the regional coordinator. 

I would focus on showing all the transects and sections that are not working at the moment. The Danish coordinator reported that there are problems with users using the app and not showing their transects and missing sections. 

Sorry for complicating the role of regional coordinator, I did not expect this.

**Comment by kazlauskis** [comment]
Thanks, I am closing this one and will continue looking into the transect issue in #682
