### ISSUE TITLE
Extend user report to include 15-minute surveys

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#685]
https://butterfly-monitoring.net/scheme-users-information

Currently only includes users who have entered data for transect survey:
562

The report needs to be extended to include additional surveys with Id:
565
645

**Comment by CrisSevilleja** [comment]
Current columns on the scheme user information page are related to the transect (562). The new surveys need a column with the survey type and name. Currently, there are columns related to training surveys, it would be good to keep them to control who is monitoring under training or not, but not sure how to organize it when including more surveys.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @CrisSevilleja ,

I have double-checked the structure of these surveys.
All 3 are similar with sub-samples, but the main difference is that the two 15 minute count surveys do not have a location attached, they just use a spatial reference.
I assume an equivalent to the "Sites (number of transects)" column won't be needed on the other two surveys, as mentioned, they just seem to use spatial references.

I am also getting the impression from Cristina's comment you actually want this data separately for each survey rather than as one big total.

Given the above, can I suggest one of 3 options

1. 
The first option is to use 3 grids?
It might make it more elegant than a grid with something like 14 columns.
They could all be downloaded separately.
A wide grid could be very confusing to develop and use.

The disadvantage of 3 grids would be if you wanted a list of users, and on each row you did want to see the data from all 3 surveys at once.

2.
As mentioned above, use one very wide grid

3.
Or an alternatively, but perhaps unusual solution, might be instead of having lots of columns and multiple grids, to instead include multiple rows for each user up to the maximum of 3.
The disadvantage here is that all you data for the different surveys would be jumbled up, but I guess you could do a sort by survey name if we include a column for that

Let me know your thoughts.

**Comment by CrisSevilleja** [comment]
Hi @andrewvanbreda 
I have been thinking about the three options you gave and what is best for the coordinators. I think the best option is number 1, to have three separate grids for the three current surveys (transect, 15min counts and moth traps). I understand the disadvantage, but we can try to have the same structure on the three grids so that the coordinator can combine them after downloading the reports if they want to.

Grid structure
- 1st column site name (as at present)
- 2nd column Sites (as currently, but depending on the grid it will change the survey. However, for 15min counts there are no real samples, only the number of 15min counts... although we are working on establishing a fixed 15min count survey.
- Samples this year (non-training) (as at present)
- Total samples (non-training) (as at present)
- Training samples this year (as at present)
- Total training samples (as at present)

If possible, and if it doesn't complicate things, I would include the year the user started registering data. Not urgent, just in case, is not difficult for the three grids. 

This way the coordinators can keep better track of the users per year and in total for their schemes. Also, as we will have different coordinators for different surveys (not all coordinators for all surveys in all countries), it is good to have it separated. 
@DavidRoy do you like this idea?

**Comment by DavidRoy** [comment]
Thanks for thinking this through @CrisSevilleja. Good suggestions
@andrewvanbreda - if these requests are complex we could potentially simplify

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja @DavidRoy 
Yes we should be able to add the start year, I have done similar for another project at some point in the past I vaguely remember.

I think the 3 grids is a nice solution.

In terms of the Sites column, I will likely have questions about this when I implement the code, I will let you know.

@DavidRoy 
I guess my main question about this is its priority level.
(In particular I would like to get back to the French data import sometime soon, which has been delayed longer than I would have liked).

**Comment by andrewvanbreda** [comment]
@DavidRoy @CrisSevilleja 
How about this? (which is currently on my test site only)
https://avb-loc-rep-brc-ebms-d10.pantheonsite.io/scheme-users-information

Just to clarify, the count of samples this report currently shows are the main parent samples, not sub-samples.
Also note that the "Year of first sample" is the earliest year of data entry on the website, it is not the field recording date (although I guess most of the time these are likely the same).

**Comment by CrisSevilleja** [comment]
@andrewvanbreda thanks for going further with this. I am not able to see the page on the test site. 

Anyway, what is the difference between main parent samples and sub-samples?

Also, regarding the 'year of first sample', this should be the date of the field record, not when these data were added to the website. Several schemes have included earlier data when they joined, so transects with data from 2012, for example, will appear as data from 2018, when this is incorrect. Is there a way to make the "year of first sample" the year of the field record?

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja ,

I have changed the date column to use the sampling date field instead. I have changed the name of the column to make this clearer.

You should be able to access the page, I can actually access it masquerading as you.
If you see an Access Denied message, make sure you login before you use the link.
Alternatively just go to the login page here, then access the page from the menu system as usual.

https://avb-loc-rep-brc-ebms-d10.pantheonsite.io/user/login

I notice you will not see any users on this report as you have no scheme on your account.
I guess we could change the report so you are set as manager who could see data across all schemes if you want?
For now if you want to see the report working, you could go to the People section of the site, click on a user and click on the link to masquerade as them.

In terms of your question about samples, this relates to the way the data is stored in the database.

So in the example of the EBMS Transects survey, the main sample is what the transect location is attached to, and the subsamples are what the sections and occurrences are attached to.

I see the other surveys also have this parent/child sample structure also.

Hope that helps

Andy

**Comment by andrewvanbreda** [comment]
Note: this is now live.

Please leave GIthub issue open for now as their is an issue already reported where the email address column was not working (and has been hidden from view until fixed)

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja @DavidRoy 
I cannot remember which user had problems seeing the email address as I think it was noted in another Github issue.
However I have checked, and the email address columns is actually working correctly.
For security reasons, the email address column is only ever filled in if the Scheme Coodinator's EBMS site role is set to Editor or above on the Warehouse's user page.
(that is a separate permission to their Scheme Coordinator role on the EBMS website).

For now, I have reinstated the email column and put a note on the page that if someone needs the email address information to contact eBMS support.
I think actually only 1 of the Scheme Coordinators has the Editor permission level set to Editor at the moment (Andras from Hungary BMS)

I have not changed any of the permissions for the Scheme Coordinators, as this has other implications beyond this report page.

@DavidRoy 

I think we have several options

1. Leave it as it is and wait for individual Scheme Coordinators to make contact if they need the email addresses.
2. Change a selection (or all) of the Scheme Coordinators to have the required Editor permission. This does affect what they can do if they were to login to the Warehouse (such as they could add terms to termlists). However, for this to be a problem they would need to know about the Warehouse login, and they would need to intend to do something we don't want them to.
Given that, I think this is unlikely, and therefore this is perhaps the best solution?

I did contact John and he suggested the following if the above solutions are not acceptable:
3. Create a new site role, which grants data viewing access for private data like emails, but not to log into the warehouse.
4. Add a feature to sync user Drupal roles to a new table on the warehouse so we can write reports that are aware of the user’s Drupal roles.

I would only suggest using John's suggestions 3 or 4 if numbers 1 and 2 really are unacceptable, as obviously there is a lot of other work that needs doing on EBMS at the moment.

Andy

**Comment by CrisSevilleja** [comment]
Hi @andrewvanbreda sorry that I didn't reply before, thank you so much for the creation of the page as we agreed. I really like it and it is super useful to see all that information with a few clicks. 

The email issue is not a big thing and maybe we can stay on number 1, waiting until the coordinators complain or do number 2. On the page, the coordinators can see the name and look for that specific person to contact them and see the email, so I don't think it is a big priority.

Regarding that I cannot see this page filled with data because I am not a coordinator of any, it would be awesome if I could select in a dropdown list and select the scheme I want to see. Of course, I can continue as now and masquerade as a coordinator and go to this page to see its scheme data, but with the dropdown, it would facilitate my work. In case it is easier to add that option, it is not an urgent and essential feature. 

Thanks a lot for improving this page :D

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja
Glad you like the new page.
I think your suggestion will involve creating a new version of the page for administrators only.
I will write this down on my task list at low priority but I will close this issue now, as the original aim is complete.
