### ISSUE TITLE
Unable to allocate an observer from Luxembourg scheme to a transect

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#690]
I am trying to allocate a transect (Mensdorf Brill) to a user (Anabela Neves ; username nevesan; anabelacfneves@gmail.com).

This user do not appear in the list of user within the Scheme Transect Allocation

**Comment by CrisSevilleja** [comment]
Hi @xaviermestdagh this issue would be better to write me directly. This is because this user was not under the Luxembourg scheme, therefore she cannot appear under the Scheme Transect Allocation. 
I have already included her in the Luxembourg scheme, so now you can allocate her to the transect Mensdorf Brill. However, the website is not working well giving some errors, so the allocation has to wait until the website is working well. 

FYI, including the name and email of a user here, in a public platform is not the best, try to avoid that.

**Comment by xaviermestdagh** [comment]
many thanks and sorry, I had seen Luxembourg in here profile but it was for the time zone... 
sorry for the GDPR issue.
