### ISSUE TITLE
Performance - reports_for_prebuilt_forms/UKBMS/ebms_region_locations.xml

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/ABLE#71]
See #57. 

@Gary-van-Breda looking at reports_for_prebuilt_forms/UKBMS/ebms_region_locations.xml first - this one averages at 26 seconds. The obvious point of complexity is where it intersects the geometry of each transect with the geometries of the regions to find the correct region to output in the report. It seems to output the full list of transects every time it is called so there are lots of regions to find and this takes time, even though the boundaries are indexed. I've experimented with a few indexing tweaks (e.g. partial indexes) but I don't think there are any quick fixes that will make a huge difference.

Some thoughts:
* Not really appropriate for Elasticsearch as we aren't storing location boundaries in it (yet).
* If the output of this report is constant, could it be cached (setting a high cache timeout to make it last a day or two)? This won't work if the data needs to be current.
* Presumably there is a reason why it is outputting the full list of transects each time and this isn't a mistake? If it were doing just a page of data at a time I think it would be much faster.
* If the data can be slightly out of date (e.g. 30 mins) we could use the custom_cache_tables module to build a simple join table between UKBMS/ABLE transects and their regions. This can be triggered to fire only when a new transect is added.
* Longer term thought - a cache_locations table, with location_ids (indexed as per samples/occurrences) as well as attrs_json which might help with other reports.

My hunch is that the custom_cache_tables module may be the way to go here.

**Comment by Gary-van-Breda** [comment]
**Background:**
This is used in 2 places on the Transect allocation form, that is used for both UKBMS and EBMS/ABLE.

1. To populate the drop down of Transects as a result of selecting the Country/Branch in the Parent control. When there is a non-empty value in the Country/Branch control, the above scenario is not applicable.
2. To return the Transects to be included in the main table. This can only be done when the Country/Branch is filled in, so the scenario above is not applicable here.

The only time the unfettered use of this report takes place is when the page is initially loaded for the supermanagers, (when the region/branch is not selected).

@johnvanbreda : can you confirm that the real problem at the moment is actually with UKBMS, rather than EBMS/ABLE? UKBMS has far more Transects, though I suppose ABLE/EBMS has far more country/regions.
That said, for EBMS/ABLE the use of a country attribute means we have an alternative means of doing the site to country mapping, so I'll change the report (and form?) for ABLE/EBMS to use this rather that the st_intersects on the geometry - this should be a lot faster.
@DavidRoy : For UKBMS I can change the report so that it returns no sites if the branch is not filled in (rather than all of them). This may affect our ability to assign sites outside a branch using this form: but we can still do it on the actual site entry form as well. Are you OK with this? (hopefully sites outside branches should not be a problem following the fixing of UKBMS issue 79)

**Comment by DavidRoy** [comment]
@Gary-van-Breda yes, I agree to the change to the report.  Assigning sites to branch/country outside the spatial layers is a minor problem now the layers are complete

Although this is currently an issue with UKBMS, we work on the principle that EBMS will grow to similar levels and therefore improve performance wherever

**Comment by johnvanbreda** [comment]
@gary yes, I can confirm that this is an issue currently on UKBMS (avg 11s per report) rather than ABLE (avg 0.25s per report). It is not as much of an issue as when first noticed though, presumably as the server is not so heavily loaded.

**Comment by Gary-van-Breda** [comment]
@BirenRathod or @johnvanbreda : can you deploy the latest brc indicia-reports into warehouse 1? 
I have added new versions of this report for UKBMS and EBMS. Once they are in place, I'll push a new version of the form for EBMS, and then UKBMS.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
All reports have now been pulled down on to live warehouse.

**Comment by Gary-van-Breda** [comment]
Updated form version deployed to EBMS Live, and configured to use the new report.
Seems to be very quick.
Still to do: updated version of the form for UKBMS.

**Comment by DavidRoy** [comment]
Closing as now fixed for ABLE
