### ISSUE TITLE
Enable training mode within www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#95]
To support the mobile app, we need training mode implemented, in two places:
1. as an optional setting on 'my account'
2. for my-records report to show training records

Also need to consider the implications of this for the transect monitoring elements of the site

**Comment by johnvanbreda** [comment]
This just needs a user account field added called training (via Configuration > Account Settings > Manage Fields) which is of type Boolean and where the machine name is field_training (which it will be if you leave the default).
I guess it would be worth applying to the test site first to try this out in case there are any side effects, but I don't have Pantheon access. 
The training flag current setting will automatically affect the my-records report, but not the Elasticsearch version. Currently the Elasticsearch index alias used automatically filters out training records. We should either remove this filter and implement it in the proxy, or add a new alias and implement code to switch the alias. I'll explore these options - the first may be preferable as it avoids proliferation of index aliases.

**Comment by DavidRoy** [comment]
I don't think having training records visible via the elastic-search version is a high priority.  Is one option to revert to the standard my-records report when in training mode?

**Comment by johnvanbreda** [comment]
Option 1 then is to update the Elasticsearch proxy code to integrate with the training setting in the user account. This is about 3 hours work and would also benefit iRecord and other sites that use training mode + Elasticsearch.
Option 2 is to to add a custom script to the Elasticsearch My Records page which detects the training mode setting and redirects to an alternative page. This is about 1 hour's work but would be a specific fix rather than one that all sites could benefit from. It also means we end up maintaining 2 explore pages.

Thoughts?

**Comment by DavidRoy** [comment]
Option 1 is best, thanks

**Comment by johnvanbreda** [comment]
I've done the following:
1) Update the Elasticsearch proxy code in the Drupal client to apply the current training mode as a filter to ES requests. 
2) Applied this to iRecord. The code is in the master branch so will appear on ABLE when updated.
3) Altered the aliases on the Elasticsearch server to allow non-training records to appear since they were being filtered out before.
4) Update the reports used to extract records into Elasticsearch so that training records are included as they were previously being excluded.
5) Changed the tracking ID on all the existing training records, causing them to be re-indexed as they were excluded from indexing before.
6) Added a training flag to the user profile on the ABLE dev site version. 

In doing the last point, I noticed the following issues:
1) If you register as a new user on ABLE, you are allowed to type in your own warehouse user ID. This field should presumably be removed from the form using Display Suite (e.g. for dev, at https://dev-butterfly-monitoring.pantheonsite.io/admin/config/people/accounts/form-display)?
2) A small CSS glitch on the training profile field with the checkbox overlaying the label.

**Comment by DavidRoy** [comment]
Thanks John.  This issue is now for @Gary-van-Breda to finish outstanding tasks?

**Comment by johnvanbreda** [comment]
Yes I think so.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda , @DavidRoy : sorry, what do you need me to do?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I think these points are outstanding on the dev site version:

* If you register as a new user on ABLE, you are allowed to type in your own warehouse user ID. This field should presumably be removed from the form using Display Suite (e.g. for dev, at https://dev-butterfly-monitoring.pantheonsite.io/admin/config/people/accounts/form-display)?
* A small CSS glitch on the training profile field with the checkbox overlaying the label.

**Comment by Gary-van-Breda** [comment]
Set all the warehouse IDs (all 3 environments) to not present on the form - leftover from the user migration.

**Comment by Gary-van-Breda** [comment]
The CSS issue stems from an absolute position on the fontawesome bootstrap plugin. Where did this come from? This may impact the display of radio buttons / checkboxes in the main pages.
Bouncing to @BirenRathod as theming is in his court. 
(This relates to the normal theme, not the admin theme, so to see it you must edit a user as an editor who does not have access to the admin theme).

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I have implemented style in CSS. Please check for other forms , it should be OK.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : I've checked the CSS issue on Dev, and that looks to me like it is now OK. Bouncing back to you now, given that this and the Indicia Warehouse field are now sorted.
I assume you now need to push it through to Test (and Live?).

**Comment by johnvanbreda** [comment]
Hi @Gary-van-Breda I've pushed through to Test along with one other change. There are a whole load of your own changes in Test ready to go to Live - are you happy for these to be deployed? If not I'll leave my changes until you are ready to deploy. I've reviewed my 2 changes, they should only affect the Elasticsearch code so you can deploy them safely without affecting anything else.

**Comment by Gary-van-Breda** [comment]
Yes - I'm happy for them to go. The scheme module is not enabled on Live yet, but I'm happy with the contents, and I'm now happy for everything I've done for #60 and #71 to go through as well.

**Comment by johnvanbreda** [comment]
Ok, everything pushed through now so closing.
