### ISSUE TITLE
Add English names to eBMS species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#97]
extend species list to include English names.  Using list exported via issue #13, English names added
[eBMS list plus Eng Name.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/3387853/eBMS.list.plus.Eng.Name.txt)

Then provide an export to enable @kazlauskis to add to the eBMS app

**Comment by larspett** [comment]
What is the plan for common names in other countries? I could supply a full list of Swedish common names quickly. Regular users in Sweden would not know English common names and most would not be comfortable with the scientific ones

**Comment by DavidRoy** [comment]
Additional common names are very welcome.  Can you create a new file, adding Swedish names to the file in this post.

**Comment by larspett** [comment]
taxon_meaning_id 186872 appears to have an encoding error in taxon  (Oberth++r's/Oliver Grizzled Skipper) and I assume the English name should be Oberthür's/Olive Grizzled Skipper

**Comment by larspett** [comment]
Here is the list with Swedish names added, saved as UTF-8

[eBMS.list.plus.Eng.and Swe.Name.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/3392625/eBMS.list.plus.Eng.and.Swe.Name.txt)

**Comment by johnvanbreda** [comment]
@Gary-van-Breda Oberthür's/Olive Grizzled Skipper seems correct in the database. Is this an encoding error somewhere in the client code?

**Comment by DavidRoy** [comment]
It's likely an error introduced when I worked on the list to add English names?  There are no Common names for the EBMS species list currently in Indicia?

**Comment by johnvanbreda** [comment]
There are just the following 4 names in the database ABLE list - I do remember there being a handful:
"Pale/Berger's Clouded Yellow"
"Purple/Lesser Purple Emporer"
"Wood White/Real's Wood White"
"Oberthür's/Oliver Grizzled Skipper"

The encoding is OK though, so it's an error on the client rather than the import.

**Comment by johnvanbreda** [comment]
@DavidRoy - the following existing common names in the ABLE list will be dropped and replaced as follows:
"Purple/Lesser Purple Emporer" => "Lesser/Purple Emperor"
"Wood White/Real's Wood White" => "Wood/Cryptic Wood White"
"Oberthür's/Oliver Grizzled Skipper" => "Oberthür's/Olive Grizzled Skipper" (drop r from Oliver)

I think these are all OK but can you confirm please?

**Comment by DavidRoy** [comment]
yes, all ok

**Comment by larspett** [comment]
I would read the first as Lesser Emperor or Purple Emperor, though

**Comment by DavidRoy** [comment]
Do you think the order of the component species in a recording aggregate is important?

**Comment by larspett** [comment]
Not really, in the Swedish BMS I have just tried to be consistent when constructing them (if I remember correctly, I always add them in alphabetical order). I used to have fairly abbreviated aggregates but now have full names with a / between for almost all of them. That tends to mess up menus, though. In the case of the Lesser/Purple E, I read it as the / meaning two different versions of the first part of the string rather than LPE/PE

**Comment by DavidRoy** [comment]
Yes, for consistency let's go for:
"Purple/Lesser Purple Emporer" => "Lesser Purple/Purple Emperor"
"Wood White/Real's Wood White" => "Real's Wood/ Wood White"
"Oberthür's/Oliver Grizzled Skipper" => "Oberthür's/Olive Grizzled Skipper" (drop r from Oliver)

@larspett do you agree?

**Comment by larspett** [comment]
yes, looks good

**Comment by larspett** [comment]
But were not "Wood White/Real's Wood White" going to become "Cryptic Wood/Wood White"?

**Comment by johnvanbreda** [comment]
Thanks @larspett - I was just going to ask about that. We can have 2 common names for a taxon if required.

**Comment by DavidRoy** [comment]
yes, 
Leptidea sinapis/juvernica

has common name:
Cryptic Wood/Wood White

**Comment by johnvanbreda** [comment]
Sorry - need to make sure I am clear. Currently there is only 1 aggregate concept in the Leptidea genus, sinapsis/juvernica. This has a common name "Wood White/Real's Wood White" in the database at the moment. 
Is this concept now going to have a single common name "Cryptic Wood/Wood White", replacing both the current "Wood White/Real's Wood White" and the proposed name from about an hour ago "Real's Wood/ Wood White"? Or should it have both "Cryptic Wood/Wood White" and "Real's Wood/ Wood White"?

**Comment by DavidRoy** [comment]
I confirm that we use 'Cryptic Wood/Wood White' for Leptidea sinapsis/juvernica.
'Wood White/Real's Wood White' should be removed for this aggregate.

@larspett do we need further aggregates for Leptidea, i.e. for Sweden

**Comment by larspett** [comment]
No these are the only two species present in Sweden (before the most recent split, L. juvernica was called L. reali in Sweden, but then that species became juvernica). Btw if we sort aggregate common names alphabetically then we should probably double-check the order of the scientific aggregate names so that they follow the sort order of the common names

**Comment by johnvanbreda** [comment]
Ok, I've done the merge of the common names now into list ID 251, ABLE Butterflies. One thing I've noticed though - there is a stray row for taxa_taxon_list_id=432713, for Pale/Berger's Clouded Yellow which is also the common name attached to Colias hyale/alfacariensis. This caused the common name to appear as a preferred name since it has it's own row in the list - I've undone this now so just noting for future reference.

**Comment by johnvanbreda** [comment]
Also for future reference, here's a summary of the steps required:
1. Make sure any new languages are registered in the Indicia Languages list (under Lookup lists on the warehouse).
2. Create a spreadsheet with the following columns, only for the rows which have a common name:
  * taxa_taxon_list_id
  * common name (English)
  * common name (Swedish)
3. Add a "Common Names" column containing this formula:
   `=CONCATENATE(IF(ISBLANK(B2),"",CONCATENATE(B2," | eng",CHAR(10))),IF(ISBLANK(C2),"",CONCATENATE(C2," | swe",CHAR(10))))`
   This gives output like the following:
   `English | eng`
   `Swedish | swe`
4. Save as a CSV file.
5. From the Taxa tab on list 251, choose the CSV file and import it.
6. On the first page of the import tool, set Taxon Group to insect - butterfly and leave other settings as they are.
7. On the next step, map taxa_taxon_list_id to the *Taxa Taxon List* table's *Id* column and also map the Common Names column to *Other Fields > CommonNames*.
8. Under *Lookup of existing records*, select *Species List and taxa taxon list ID" then import the data.

**Comment by DavidRoy** [comment]
Reopening.  The final step is:
Then provide an export to enable @kazlauskis to add to the eBMS app

**Comment by johnvanbreda** [comment]
There is now a report, projects/ebms/taxa_list_for_app.xml (title List of taxa for the ABLE app). Pass the parameter taxon_list_id=251 to get the correct list data.

@kazlauskis Does this give you all the info you need to run the report and extract the names. Plus, are the report columns sufficient or do you need additional info?

**Comment by kazlauskis** [comment]
@johnvanbreda this looks good thanks.
